import { INGREDIENT_TAG_SLUGS, type IngredientTagSlug } from './tag-slugs'

export const INGREDIENT_TAG_CATEGORIES = [
  'concern',
  'skin_type',
  'ingredient_attribute',
  'skin_effect',
  'shared_label',
] as const

export type IngredientTagCategory = (typeof INGREDIENT_TAG_CATEGORIES)[number]

export interface IngredientTagMeta {
  category: IngredientTagCategory
}

const CONCERN: IngredientTagSlug[] = [
  INGREDIENT_TAG_SLUGS.ANTI_ROUGEURS,
  INGREDIENT_TAG_SLUGS.ROSACEE,
  INGREDIENT_TAG_SLUGS.COUPEROSE,
  INGREDIENT_TAG_SLUGS.FLUSHS,
  INGREDIENT_TAG_SLUGS.BARRIERE_CUTANEE,
  INGREDIENT_TAG_SLUGS.ANTI_TACHES,
  INGREDIENT_TAG_SLUGS.ANTI_ACNE,
  INGREDIENT_TAG_SLUGS.ANTI_AGE,
  INGREDIENT_TAG_SLUGS.HYPERPIGMENTATION,
  INGREDIENT_TAG_SLUGS.DESHYDRATATION,
  INGREDIENT_TAG_SLUGS.PORES_DILATES,
  INGREDIENT_TAG_SLUGS.CERNES_POCHES,
  INGREDIENT_TAG_SLUGS.BRILLANCE,
  INGREDIENT_TAG_SLUGS.ECLAT,
  INGREDIENT_TAG_SLUGS.POST_ACNE,
  INGREDIENT_TAG_SLUGS.CICATRISATION,
  INGREDIENT_TAG_SLUGS.MICROBIOME,
  INGREDIENT_TAG_SLUGS.PHOTO_VIEILLISSEMENT,
  INGREDIENT_TAG_SLUGS.TEINT_TERNE,
  INGREDIENT_TAG_SLUGS.LUMIERE_BLEUE,
  INGREDIENT_TAG_SLUGS.POLLUTION,
  INGREDIENT_TAG_SLUGS.ECZEMA,
  INGREDIENT_TAG_SLUGS.GRAIN_PEAU,
  INGREDIENT_TAG_SLUGS.KERATOSE_PILAIRE,
  INGREDIENT_TAG_SLUGS.PHOTO_PROTECTION,
  INGREDIENT_TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
]

const SKIN_TYPE: IngredientTagSlug[] = [
  INGREDIENT_TAG_SLUGS.PEAU_SECHE,
  INGREDIENT_TAG_SLUGS.PEAU_MIXTE,
  INGREDIENT_TAG_SLUGS.PEAU_GRASSE,
  INGREDIENT_TAG_SLUGS.PEAU_REACTIVE,
  INGREDIENT_TAG_SLUGS.PEAU_SENSIBLE,
  INGREDIENT_TAG_SLUGS.PEAU_NORMALE,
  INGREDIENT_TAG_SLUGS.PEAU_ATOPIQUE,
  INGREDIENT_TAG_SLUGS.PEAU_RUGUEUSE,
  INGREDIENT_TAG_SLUGS.PEAU_TOUS_TYPES,
]

const INGREDIENT_ATTRIBUTE: IngredientTagSlug[] = [
  INGREDIENT_TAG_SLUGS.ANTI_OXYDANT,
  INGREDIENT_TAG_SLUGS.HUMECTANT,
  INGREDIENT_TAG_SLUGS.EMOLLIENT,
  INGREDIENT_TAG_SLUGS.REPARATEUR,
  INGREDIENT_TAG_SLUGS.ANTISEPTIQUE,
  INGREDIENT_TAG_SLUGS.KERATOLYTIQUE,
  INGREDIENT_TAG_SLUGS.SEBO_REGULATEUR,
  INGREDIENT_TAG_SLUGS.ASTRINGENT,
  INGREDIENT_TAG_SLUGS.ANTI_BACTERIEN,
  INGREDIENT_TAG_SLUGS.BIOMIMETIQUE,
  INGREDIENT_TAG_SLUGS.APAISANT,
  INGREDIENT_TAG_SLUGS.PREBIOTIQUE,
  INGREDIENT_TAG_SLUGS.ANTI_INFLAMMATOIRE,
  INGREDIENT_TAG_SLUGS.PURIFIANT,
  INGREDIENT_TAG_SLUGS.FILTRE_UV,
  INGREDIENT_TAG_SLUGS.FILTRES_CHIMIQUES,
  INGREDIENT_TAG_SLUGS.FILTRES_MINERAUX,
  INGREDIENT_TAG_SLUGS.TENSIOACTIF,
  INGREDIENT_TAG_SLUGS.EXCIPIENT,
  INGREDIENT_TAG_SLUGS.ACTIF,
]

const SKIN_EFFECT: IngredientTagSlug[] = [
  INGREDIENT_TAG_SLUGS.OCCLUSIF,
  INGREDIENT_TAG_SLUGS.REPULPANT,
  INGREDIENT_TAG_SLUGS.MATIFIANT,
  INGREDIENT_TAG_SLUGS.PROTECTION_CUTANEE,
]

const SHARED_LABEL: IngredientTagSlug[] = [
  INGREDIENT_TAG_SLUGS.COMEDOGENE,
  INGREDIENT_TAG_SLUGS.NON_COMEDOGENE,
  INGREDIENT_TAG_SLUGS.GROSSESSE_COMPATIBLE,
]

const entries: [IngredientTagSlug, IngredientTagMeta][] = [
  ...CONCERN.map((s): [IngredientTagSlug, IngredientTagMeta] => [s, { category: 'concern' }]),
  ...SKIN_TYPE.map((s): [IngredientTagSlug, IngredientTagMeta] => [s, { category: 'skin_type' }]),
  ...INGREDIENT_ATTRIBUTE.map((s): [IngredientTagSlug, IngredientTagMeta] => [
    s,
    { category: 'ingredient_attribute' },
  ]),
  ...SKIN_EFFECT.map((s): [IngredientTagSlug, IngredientTagMeta] => [
    s,
    { category: 'skin_effect' },
  ]),
  ...SHARED_LABEL.map((s): [IngredientTagSlug, IngredientTagMeta] => [
    s,
    { category: 'shared_label' },
  ]),
]

export const INGREDIENT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  IngredientTagSlug,
  IngredientTagMeta
>

export function getIngredientTagCategory(
  slug: IngredientTagSlug
): IngredientTagCategory | undefined {
  return INGREDIENT_TAG_TAXONOMY[slug]?.category
}
