import { TAG_SLUGS } from '../../tags/seed-tags'
import { CORPS_PRODUCT_SLUGS } from './corps'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const CORPS_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES]: {
    primary: [
      TAG_SLUGS.PEAU_RUGUEUSE,
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.EXFOLIATION,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BAUME,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
  },

  
  [CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  
  [CORPS_PRODUCT_SLUGS.CERAVE_LAIT_HYDRATANT]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  
  [CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10]: {
    primary: [
      TAG_SLUGS.PEAU_RUGUEUSE,
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.DESHYDRATATION,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  
  [CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME]: {
    primary: [
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BAUME,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
  },

  
  [CORPS_PRODUCT_SLUGS.AMLACTIN_DAILY_NOURISH_12_AHA]: {
    primary: [
      TAG_SLUGS.PEAU_RUGUEUSE,
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.DESHYDRATATION,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.PAULAS_CHOICE_LAIT_CORPS_10_AHA]: {
    primary: [
      TAG_SLUGS.PEAU_RUGUEUSE,
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.ANTI_TACHES,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.REMEDY_KP_BODY_MOISTURIZER]: {
    primary: [
      TAG_SLUGS.PEAU_RUGUEUSE,
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.ANTI_AGE,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.BYOMA_BLEMISH_CONTROL_BODY_LOTION]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BRILLANCE],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  [CORPS_PRODUCT_SLUGS.XEROLYS_50]: {
    primary: [
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.OCCLUSIF,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.URIAGE_KERATOSANE_30]: {
    primary: [TAG_SLUGS.KERATOSE_PILAIRE, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  
  [CORPS_PRODUCT_SLUGS.ISISPHARMA_URELIA_50]: {
    primary: [
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.ECZEMA,
    ],
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  
  [CORPS_PRODUCT_SLUGS.TOPICREM_UR_10]: {
    primary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.TOPICREM_ULTRA_HYDRATANT_RICHE]: {
    primary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.TEINT_TERNE,
    ],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    avoid: [],
  },

  
  [CORPS_PRODUCT_SLUGS.SKINCEUTICALS_LIP_REPAIR]: {
    primary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.ANTI_AGE,
    ],
    secondary: [
      TAG_SLUGS.SOIN_LEVRES,
      TAG_SLUGS.ZONE_LEVRES,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ],
    avoid: [],
  },

  
  [CORPS_PRODUCT_SLUGS.THE_INKEY_LIST_UREA_10]: {
    primary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
    ],
  },

  

  [CORPS_PRODUCT_SLUGS.ISDIN_UREADIN_ULTRA_20]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
    ],
  },

  
  [CORPS_PRODUCT_SLUGS.ISDIN_UREADIN_ULTRA_30]: {
    primary: [
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },

  

  [CORPS_PRODUCT_SLUGS.ISDIN_UREADIN_ULTRA_10_LOTION]: {
    primary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_ATOPIQUE,
    ],
    avoid: [],
  },

  

  [CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_30]: {
    primary: [
      TAG_SLUGS.KERATOSE_PILAIRE,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.PEAU_ATOPIQUE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },
}
