import { TAG_SLUGS } from "../../tags/seed-tags";
import { INGREDIENT_SLUGS } from "../../ingredients/ingredient-slugs";
import type { UnifiedProductSeed } from "../unified-types";

export const VICHY_LABORATORIES_SEED: UnifiedProductSeed[] = [
  {
    slug: "vichy-laboratories-mineral-89-moisturizer",
    name: "Mineral 89 Hyaluronic Acid Face Moisturizer",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum hydratant et repulpant quotidien qui renforce la barrière cutanée.",
    inci: "BIOSACCHARIDE GUM-1, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, CARBOMER, CITRIC ACID, GLYCERIN, METHYL GLUCETH-20, PEG/PPG/POLYBUTYLENE GLYCOL-8/5/3 GLYCERIN, PHENOXYETHANOL, SODIUM HYALURONATE, WATER",
    url: "https://www.skinsafeproducts.com/vichy-mineral-89-hydrating-face-serum-with-hyaluronic-acid",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/D96A34FE9CF347/large_1594778544.jpeg?1594778544",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.SANS_PARFUM,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, notes: "Forme d'acide hyaluronique" },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
      { slug: INGREDIENT_SLUGS.BIOSACCHARIDE_GUM_1 },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-vitamin-c-serum",
    name: "LiftActiv Vitamin C Serum",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "dropper",
    totalAmount: 20,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum à 15% de Vitamine C pure pour booster l'éclat et protéger la peau du stress oxydatif.",
    inci: "ALCOHOL DENAT, WATER, ASCORBIC ACID, DIPROPYLENE GLYCOL, GLYCERIN, HYDROLYZED HYALURONIC ACID, LAURETH-23, NEOHESPERIDIN DIHYDROCHALCONE, PINUS PINASTER BARK/BUD EXTRACT, SODIUM HYDROXIDE, TOCOPHEROL",
    url: "https://www.skinsafeproducts.com/vichy-liftactiv-vitamin-c-serum-0-67-fl-oz-20-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/2ABE30CE6010B6/large_1673212132.jpeg?1673212132",
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.ANTI_OXYDANT,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.VITAMIN_C, notes: "15% Acide Ascorbique" },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: "Vitamine E" },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-collagen-specialist-serum",
    name: "Liftactiv Collagen Specialist 16 Serum",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum anti-âge formulé pour corriger la perte de collagène et raffermir la peau.",
    inci: "ADENOSINE, ALCOHOL DENAT, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, WATER, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, CARBOMER, CITRIC ACID, DIMETHICONE, GLYCERIN, GRIFOLA FRONDOSA FRUITING BODY EXTRACT, HYDROLYZED RICE PROTEIN, HYDROXYACETOPHENONE, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, MALTODEXTRIN, NIACINAMIDE, PALMITOYL TETRAPEPTIDE-7, PALMITOYL TRIPEPTIDE-1, PARFUM, PEG-20 METHYL GLUCOSE SESQUISTEARATE, PENTYLENE GLYCOL, POLYSORBATE 20, RHAMNOSE, SH-POLYPEPTIDE-69, SILICA, SODIUM CHLORIDE, SODIUM HYALURONATE, SODIUM LACTATE, SODIUM PHOSPHATE, TETRASODIUM GLUTAMATE DIACETATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-laboratories-liftactiv-collagen-specialist-16-serum-30-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/6CFC6C6AD527DF/large_1747117850.pngpng?1747117850",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1 },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7 },
      { slug: INGREDIENT_SLUGS.ADENOSINE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
    ],
  },
  {
    slug: "vichy-laboratories-aqualia-thermal-fragrance-free-cream",
    name: "Aqualia Thermal Fragrance Free Cream",
    brand: "Vichy Laboratories",
    kind: "moisturizer",
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Crème hydratante sans parfum pour peaux sèches à très sèches.",
    inci: "ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, ALCOHOL DENAT., AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, WATER, BUTYROSPERMUM PARKII BUTTER, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CETEARYL ALCOHOL, CETEARYL GLUCOSIDE, CITRIC ACID, GLYCERIN, GLYCERYL ISOSTEARATE, ISOPROPYL PALMITATE, MANNOSE, P-ANISIC ACID, PROPANEDIOL, SODIUM HYALURONATE, SODIUM HYDROXIDE, SODIUM PCA, ZEA MAYS STARCH",
    url: "https://www.skinsafeproducts.com/vichy-laboratories-aqualia-thermal-fragrance-free-cream-1-69-fl-oz-50-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/A0D3B36DE88E92/large_1647113773.jpeg?1647113773",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.SANS_PARFUM,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.SODIUM_PCA },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
    ],
  },
  {
    slug: "vichy-laboratories-normaderm-phytoaction-cleansing-gel",
    name: "NormaDerm PhytoAction Daily Deep Cleansing Gel",
    brand: "Vichy Laboratories",
    kind: "cleanser",
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 0,
    description: "Nettoyant quotidien à l'acide salicylique pour les peaux à tendance acnéique.",
    inci: "BIFIDA FERMENT LYSATE, CAPRYLYL GLYCOL, COCO-BETAINE, COPPER GLUCONATE, DIPROPYLENE GLYCOL, FRAGRANCE, PEG-120 METHYL GLUCOSE DIOLEATE, PHENOXYETHANOL, PROPANEDIOL, SALICYLIC ACID, SODIUM BENZOATE, SODIUM CHLORIDE, SODIUM COCOYL GLYCINATE, SODIUM HYDROXIDE, TETRASODIUM GLUTAMATE DIACETATE, WATER, ZINC GLUCONATE",
    url: "https://www.skinsafeproducts.com/vichy-normaderm-phytoaction-daily-deep-cleansing-gel-acne-treatment-salicylic-acid-13-52-fl-oz-400-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/837F961A8FB056/large_1726869488.jpeg?1726869488",
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE],
      secondary: [
        TAG_SLUGS.GEL_NETTOYANT,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID, notes: "BHA" },
      { slug: INGREDIENT_SLUGS.ZINC_GLUCONATE },
      { slug: INGREDIENT_SLUGS.COPPER_GLUCONATE },
    ],
  },
  {
    slug: "vichy-laboratories-capital-soleil-spf50-foaming-lotion",
    name: "Capital Soleil SPF 50 Lightweight Foaming Lotion",
    brand: "Vichy Laboratories",
    kind: "sunscreen",
    unit: "aerosol",
    totalAmount: 140,
    amountUnit: "g",
    priceCents: 0,
    description: "Protection solaire SPF 50 sous forme de mousse légère.",
    inci: "AVOBENZONE, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, DISODIUM EDTA, FRAGRANCE, GLYCERIN, HDI/TRIMETHYLOL HEXYLLACTONE CROSSPOLYMER, HOMOSALATE, HYDROLYZED TRITICUM MONOCOCCUM SEED EXTRACT, ISOBUTANE, OCTISALATE, OCTOCRYLENE, OCTYLDODECYL MYRISTATE, OXYBENZONE, P-ANISIC ACID, PEG-12 DIMETHICONE, PEG-8 LAURATE, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYCINNAMATE, PHENOXYETHANOL, SILICA, SODIUM HYALURONATE, STYRENE/ACRYLATES COPOLYMER, TOCOPHEROL, VITIS VINIFERA FRUIT EXTRACT, WATER, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-capital-soleil-spf-50-lightweight-foaming-lotion-4-97-oz-0",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/9BDAC268340055/large_1492728406.jpeg?1492728406",
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.FILTRES_CHIMIQUES,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AVOBENZONE },
      { slug: INGREDIENT_SLUGS.HOMOSALATE },
      { slug: INGREDIENT_SLUGS.OCTOCRYLENE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
    ],
  },
  {
    slug: "vichy-laboratories-neovadiol-meno-5-serum",
    name: "Neovadiol Anti Aging Serum, Meno 5",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum global anti-âge pour les peaux matures en période de péri et post-ménopause.",
    inci: "ADENOSINE, ALCOHOL DENAT., WATER, ASCORBYL GLUCOSIDE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLOYL SALICYLIC ACID, CASSIA ANGUSTIFOLIA SEED POLYSACCHARIDE, DICAPRYLYL ETHER, DIPROPYLENE GLYCOL, GLYCERIN, GLYCOLIC ACID, HAEMATOCOCCUS PLUVIALIS EXTRACT, HYDROXYACETOPHENONE, HYDROXYPROPYL TETRAHYDROPYRANTRIOL, ISOPROPYL ISOSTEARATE, ISOPROPYL LAUROYL SARCOSINATE, NIACINAMIDE, PARFUM, PROPYLENE GLYCOL, PRUNUS ARMENIACA KERNEL OIL, SODIUM HYDROXIDE, SQUALANE, TOCOPHEROL",
    url: "https://www.skinsafeproducts.com/vichy-neovadiol-anti-aging-serum-meno-5-1-01-fl-oz-30-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/AFA375344659E4/large_1708632390.jpeg?1708632390",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.GLYCOLIC_ACID },
      { slug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE },
      { slug: INGREDIENT_SLUGS.SQUALANE },
      { slug: INGREDIENT_SLUGS.ADENOSINE },
    ],
  },
  {
    slug: "vichy-laboratories-purete-thermale-cleansing-gel",
    name: "Purete Thermale Fresh Cleansing Gel",
    brand: "Vichy Laboratories",
    kind: "cleanser",
    unit: "pump",
    totalAmount: 200,
    amountUnit: "ml",
    priceCents: 0,
    description: "Gel nettoyant frais qui élimine les impuretés et les particules de pollution.",
    inci: "WATER, CAPRYLYL GLYCOL, COCO-BETAINE, GLYCERIN, HYDROXYACETOPHENONE, NIACINAMIDE, PARFUM, PEG-120 METHYL GLUCOSE DIOLEATE, PROPANEDIOL, SALICYLIC ACID, SODIUM CHLORIDE, SODIUM COCOYL GLYCINATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE",
    url: "https://www.skinsafeproducts.com/vichy-purete-thermale-fresh-cleansing-gel-b3-niacinamide-6-76-fl-oz-200-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/DDC9A76259C5E8/large_1715628254.jpeg?1715628254",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.GEL_NETTOYANT,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID },
    ],
  },
  {
    slug: "vichy-laboratories-mineral-89-matte-sorbet",
    name: "Mineral 89 48H Moisture Matte Sorbet",
    brand: "Vichy Laboratories",
    kind: "moisturizer",
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Gel-crème hydratant matifiant pour les peaux mixtes à grasses.",
    inci: "ALCOHOL DENAT, WATER, BIOSACCHARIDE GUM-1, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, CITRIC ACID, DIPOTASSIUM GLYCYRRHIZATE, GLYCERIN, GLYCERYL ISOSTEARATE, HYDROXYACETOPHENONE, MALTODEXTRIN, NIACINAMIDE, SALICYLIC ACID, SILICA, SODIUM CARBOMER, SODIUM HYALURONATE, SODIUM HYDROXIDE, SQUALANE, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-mineral-89-48h-moisture-matte-sorbet-1-69-fl-oz-50-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/82ED5A2F04879E/large_1726085246.jpeg?1726085246",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.BRILLANCE],
      secondary: [
        TAG_SLUGS.GEL_CREME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.MATIFIANT,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.SQUALANE },
      { slug: INGREDIENT_SLUGS.DIPOTASSIUM_GLYCYRRHIZATE },
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-night-supreme",
    name: "LiftActiv Night Supreme Anti-Wrinkle and Firming Night Cream",
    brand: "Vichy Laboratories",
    kind: "moisturizer",
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Soin de nuit raffermissant et anti-rides global.",
    inci: "ADENOSINE, ASCORBYL GLUCOSIDE, BUTYROSPERMUM PARKII BUTTER, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CERA ALBA, CETYL ALCOHOL, DIMETHICONE, DIMETHICONOL, GLYCERIN, GLYCERYL STEARATE, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, MAGNESIUM ASCORBYL PHOSPHATE, MYRISTYL ALCOHOL, PARFUM, PEG-40 STEARATE, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, PENTAERYTHRITYL TETRAETHYLHEXANOATE, PENTYLENE GLYCOL, PETROLATUM, PHENOXYETHANOL, POLOXAMER 338, PRUNUS ARMENIACA KERNEL OIL, RHAMNOSE, SORBITAN TRISTEARATE, STEARYL ALCOHOL, TRIETHANOLAMINE, WATER, XANTHAN GUM, ZEA MAYS STARCH",
    url: "https://www.skinsafeproducts.com/liftactiv-night-cream",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/3lcYThZPYJrAglKc1NVPRw/large_1469903679.jpegJPG?1469903679",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.CREME_DE_NUIT,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RHAMNOSE },
      { slug: INGREDIENT_SLUGS.ADENOSINE },
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER },
      { slug: INGREDIENT_SLUGS.APRICOT_KERNEL_OIL },
      { slug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE },
    ],
  },
  {
    slug: "vichy-laboratories-mineral-89-boosting-cream",
    name: "Mineral 89 Boosting Cream",
    brand: "Vichy Laboratories",
    kind: "moisturizer",
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Crème hydratante riche en minéraux, vitamines B3 & E et squalane.",
    inci: "ADENOSINE, ALCOHOL DENAT., WATER, ARACHIDYL ALCOHOL, ARACHIDYL GLUCOSIDE, BEHENYL ALCOHOL, BUTYROSPERMUM PARKII BUTTER, CAPRYLYL GLYCOL, CARBOMER, CETEARYL ISONONANOATE, CITRIC ACID, DICAPRYLYL ETHER, GLYCERIN, MANNOSE, NIACINAMIDE, PALMITIC ACID, PARFUM, PENTYLENE GLYCOL, POLYGLYCERYL-3 METHYLGLUCOSE DISTEARATE, SALICYLIC ACID, SIMMONDSIA CHINENSIS SEED OIL, SODIUM HYALURONATE, SODIUM HYDROXIDE, SODIUM PCA, SODIUM STEAROYL GLUTAMATE, SQUALANE, STEARIC ACID, STEARYL ALCOHOL, TOCOPHEROL, VITREOSCILLA FERMENT, XANTHAN GUM, ZEA MAYS STARCH",
    url: "https://www.skinsafeproducts.com/vichy-laboratories-mineral-89-boosting-cream-vitamines-b3-e-squalane-50-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/4387055D07910D/large_1704737458.jpeg?1704737458",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.SQUALANE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER },
      { slug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA },
      { slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT },
    ],
  },
  {
    slug: "vichy-laboratories-mineral-89-booster",
    name: "Mineral 89 Fortifying & Plumping Daily Booster",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "pump",
    totalAmount: 75,
    amountUnit: "ml",
    priceCents: 0,
    description: "Booster quotidien fortifiant et repulpant à 89% d'eau volcanique de Vichy.",
    inci: "WATER, BIOSACCHARIDE GUM-1, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, CARBOMER, CITRIC ACID, GLYCERIN, HYDROXYACETOPHENONE, MALTODEXTRIN, METHYL GLUCETH-20, PEG/PPG/POLYBUTYLENE GLYCOL-8/5/3 GLYCERIN, PROPANEDIOL, SODIUM HYALURONATE",
    url: "https://www.skinsafeproducts.com/vichy-laboratories-mineral-89-fortifying-plumping-daily-booster-2-53-fl-oz-75-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/0DD9FAB176620B/large_1698229081.pngpng?1698229081",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.SANS_PARFUM,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
    ],
  },
  {
    slug: "vichy-laboratories-purete-thermale-micellar-water",
    name: "Purete Thermale Mineral Micellar Water",
    brand: "Vichy Laboratories",
    kind: "cleanser",
    unit: "bottle",
    totalAmount: 200,
    amountUnit: "ml",
    priceCents: 0,
    description: "Eau micellaire minérale pour nettoyer et démaquiller les peaux sensibles.",
    inci: "WATER, DISODIUM EDTA, GLYCERIN, HEXYLENE GLYCOL, MYRTRIMONIUM BROMIDE, PANTHENOL, PARFUM, POLOXAMER 184, SODIUM CHLORIDE, SODIUM COCOAMPHOACETATE",
    url: "https://www.skinsafeproducts.com/vichy-purete-thermale-mineral-micellar-water-sensitive-skin-6-76-fl-oz-200-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/9CC5FFB28EB73C/large_1600469163.jpeg?1600469163",
    tags: {
      primary: [TAG_SLUGS.HYDRATATION],
      secondary: [
        TAG_SLUGS.EAU_MICELLAIRE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.PANTHENOL },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-serum-10-supreme",
    name: "LiftActiv Serum 10 Supreme",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum anti-âge puissant à l'acide hyaluronique et au rhamnose.",
    inci: "ADENOSINE, ALCOHOL DENAT., AMMONIUM POLYACRYLDIMETHYLTAURAMIDE, BHT, BUTYLENE GLYCOL, C13-14 ISOPARAFFIN, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, CYCLOHEXASILOXANE, DISODIUM EDTA, DIMETHICONE, GLYCERIN, LAURETH-7, OCTYLDODECANOL, PARFUM, PEG-20 METHYL GLUCOSE SESQUISTEARATE, PENTAERYTHRITYL TETRAETHYLHEXANOATE, POLOXAMER 338, POLYACRYLAMIDE, POLYMETHYLSILSESQUIOXANE, POLYSILICONE-11, RHAMNOSE, SODIUM HYALURONATE, SODIUM HYDROXIDE, WATER, TOCOPHEROL",
    url: "https://www.skinsafeproducts.com/vichy-liftactiv-serum-10-supreme-anti-aging-serum-with-hyaluronic-acid-1-01-fl-oz",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/2CD28B9FFFC789/large_1484422789.jpeg?1484422789",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RHAMNOSE, notes: "10%" },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.ADENOSINE },
    ],
  },
  {
    slug: "vichy-laboratories-aqualia-thermal-eye-cream",
    name: "Aqualia Thermal Awakening Eye Cream",
    brand: "Vichy Laboratories",
    kind: "eye-cream",
    unit: "tube",
    totalAmount: 15,
    amountUnit: "ml",
    priceCents: 0,
    description: "Soin contour des yeux hydratant à la caféine pure pour réduire les cernes et poches.",
    inci: "ALGAE EXTRACT, BIOSACCHARIDE GUM-1, BLUE NO. 1 (CI 42090), CAFFEINE, CITRIC ACID, DIMETHICONE, DIMETHICONE/PEG-10/15 CROSSPOLYMER, DISODIUM EDTA, GLYCERIN, P-ANISIC ACID, PHENOXYETHANOL, POLYMETHYLSILSESQUIOXANE, PROPANEDIOL, SODIUM CHLORIDE, SODIUM CITRATE, SODIUM HYALURONATE, SODIUM HYDROXIDE, WATER",
    url: "https://www.skinsafeproducts.com/vichy-aqualia-thermal-awakening-eye-cream-with-pure-caffeine-for-dark-circles-and-puffiness-0-5-fluid-ounce",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/1F8F271A850298/large_1514851693.jpeg?1514851693",
    tags: {
      primary: [TAG_SLUGS.CERNES_POCHES],
      secondary: [
        TAG_SLUGS.CONTOUR_YEUX,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_YEUX,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CAFFEINE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.GLYCERIN },
    ],
  },
  {
    slug: "vichy-laboratories-normaderm-exfoliating-serum",
    name: "Normaderm Exfoliating Serum, BHA",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum exfoliant quotidien pour corriger les imperfections et lisser le grain de peau.",
    inci: "ADENOSINE, ALCOHOL DENAT., AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, ASCORBYL GLUCOSIDE, GLYCERIN, GLYCOLIC ACID, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, MENTHOL, PANTHENOL, PEG/PPG/POLYBUTYLENE GLYCOL-8/5/3 GLYCERIN, PROPANEDIOL, SALICYLIC ACID, SODIUM HYDROXIDE, SODIUM POLYACRYLATE, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, VITREOSCILLA FERMENT, WATER, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-normaderm-exfoliating-serum-bha-1-01-fl-oz-30-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/D04FBCCC22E999/large_1704873007.jpeg?1704873007",
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.GRAIN_PEAU],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID, notes: "BHA" },
      { slug: INGREDIENT_SLUGS.GLYCOLIC_ACID, notes: "AHA" },
      { slug: INGREDIENT_SLUGS.PANTHENOL },
      { slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT },
    ],
  },
  {
    slug: "vichy-laboratories-neovadiol-peri-menopause-day-cream",
    name: "Neovadiol Peri-Menopause Redensifying Plumping Day Cream",
    brand: "Vichy Laboratories",
    kind: "moisturizer",
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 0,
    description: "Crème de jour redensifiante et repulpante pour les peaux matures pendant la péri-ménopause.",
    inci: "ADENOSINE, ALCOHOL DENAT, WATER, CAPRYLYL GLYCOL, CASSIA ANGUSTIFOLIA SEED POLYSACCHARIDE, CI 15985, CI 77891, DIMETHICONE, DIMETHICONE/PEG-10/15 CROSSPOLYMER, DIPROPYLENE GLYCOL, DISTEARDIMONIUM HECTORITE, GLYCERIN, HYDROGENATED POLYISOBUTENE, HYDROXYACETOPHENONE, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, HYDROXYPROPYL TETRAHYDROPYRANTRIOL, NIACINAMIDE, PARFUM, PEG-10 DIMETHICONE, PROPYLENE CARBONATE, PROPYLENE GLYCOL, SILICA, SODIUM CITRATE, SODIUM HYALURONATE, SODIUM POLYACRYLATE, SYNTHETIC FLUORPHLOGOPITE, SYNTHETIC WAX, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE",
    url: "https://www.skinsafeproducts.com/vichy-neovadiol-peri-menopause-redensifying-plumping-day-cream-1-69-fl-oz-50-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/A83207C0F092F7/large_1708737050.jpeg?1708737050",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.ADENOSINE },
      { slug: INGREDIENT_SLUGS.TOCOPHEROL },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-eye-cream",
    name: "Liftactiv Eye Cream, 5 % Complex Pro - Collagen",
    brand: "Vichy Laboratories",
    kind: "eye-cream",
    unit: "tube",
    totalAmount: 15,
    amountUnit: "ml",
    priceCents: 0,
    description: "Soin yeux raffermissant formulé avec un complexe pro-collagène pour corriger les rides et la perte de fermeté.",
    inci: "ACETYL TETRAPEPTIDE-9, ALCOHOL DENAT, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, WATER, ASCORBYL GLUCOSIDE, BORON NITRIDE, BUTYLENE GLYCOL, CAFFEINE, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, CARBOMER, CETYL ALCOHOL, CITRIC ACID, DEXTRIN, DIMETHICONE, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, EPERUA FALCATA BARK EXTRACT, GLYCERIN, GLYCERYL STEARATE, HYDROLYZED RICE PROTEIN, HYDROXYACETOPHENONE, HYDROXYPROPYL TETRAHYDROPYRANTRIOL, ISONONYL ISONONANOATE, MYRISTIC ACID, NIACINAMIDE, OXOTHIAZOLIDINECARBOXYLIC ACID, PALMITIC ACID, PALMITOYL TETRAPEPTIDE-7, PALMITOYL TRIPEPTIDE-1, PEG-100 STEARATE, PENTYLENE GLYCOL, POLYSORBATE 20, PROPYLENE GLYCOL, SODIUM CITRATE, SODIUM LACTATE, SORBITOL, STEARIC ACID, TOCOPHERYL ACETATE, TRIETHANOLAMINE, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, VACCINIUM MYRTILLUS FRUIT EXTRACT, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-laboratories-liftactiv-eye-cream-5-complex-pro-collagen-15-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/794144D96F33E7/large_1716357523.pngpng?1716357523",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CERNES_POCHES],
      secondary: [
        TAG_SLUGS.CONTOUR_YEUX,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_YEUX,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.CAFFEINE },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1 },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7 },
      { slug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE },
    ],
  },
  {
    slug: "vichy-laboratories-liftactiv-pure-retinol-serum",
    name: "LiftActiv Pure Retinol Serum",
    brand: "Vichy Laboratories",
    kind: "serum",
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 0,
    description: "Sérum anti-rides puissant au rétinol pur pour corriger les rides profondes et le teint irrégulier.",
    inci: "ALCOHOL DENAT, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, WATER, BUTYLENE GLYCOL, CAPRYLYL GLYCOL, CARBOMER, DICAPRYLYL CARBONATE, DICAPRYLYL ETHER, GLYCERIN, GLYCERYL ISOSTEARATE, GLYCINE SOJA OIL, HYDROLYZED RICE PROTEIN, HYDROXYACETOPHENONE, ISONONYL ISONONANOATE, PALMITOYL TETRAPEPTIDE-7, PALMITOYL TRIPEPTIDE-1, PEG-6 CAPRYLIC/CAPRIC GLYCERIDES, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, PENTYLENE GLYCOL, POLYSORBATE 20, PPG-6-DECYLTETRADECETH-30, PROPYLENE GLYCOL, RETINOL, SODIUM HYALURONATE, SODIUM HYDROXIDE, SODIUM LACTATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, VITREOSCILLA FERMENT, XANTHAN GUM",
    url: "https://www.skinsafeproducts.com/vichy-liftactiv-pure-retinol-serum-1-01-fl-oz-30-ml",
    imageUrl: "https://cdn1.skinsafeproducts.com/photo/DB280DE187A91C/large_1700193537.jpeg?1700193537",
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINOL, notes: "Pur" },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1 },
      { slug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7 },
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
      { slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT },
    ],
  },
];
