import { TAG_SLUGS } from '../../tags/seed-tags'
import { OCCITANE_PRODUCT_SLUGS } from './occitane'

export interface ProductTagGroups {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const OCCITANE_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_MOUSSE_NETTOYANTE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.DOUBLE_NETTOYAGE_2,
      TAG_SLUGS.MOUSSE_NETTOYANTE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_BAUME_DEMAQUILLANT]: {
    primary: [TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.BAUME_DEMAQUILLANT,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_HUILE_DEMAQUILLANTE]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.HUILE_DEMAQUILLANTE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_EAU_ESSENTIELLE]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_TRIPHASE_ESSENCE_RESET]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.MICROBIOME],
    secondary: [
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.ESSENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_SERUM_PRO_FERMETE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_SERUM_RESET_NUIT]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_HUILE_JEUNESSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.HUILE_VISAGE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_CREME_JEUNESSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES],
    secondary: [
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.GRAIN_PEAU,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_CREME_VISAGE_PRECIEUSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_BAUME_REGARD]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CERNES_POCHES],
    secondary: [
      TAG_SLUGS.SOIN_YEUX,
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.ZONE_YEUX,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_CONTOUR_YEUX_LEVRES]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.SOIN_YEUX,
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.SOIN_LEVRES,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ZONE_YEUX,
      TAG_SLUGS.ZONE_LEVRES,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_CREME_COU]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_HUILE_CORPS_RAFFERMISSANTE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.HUILE_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_BAUME_CORPS_PRO_JEUNESSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },

  

  [OCCITANE_PRODUCT_SLUGS.IMMORTELLE_SERUM_CREME_MAINS]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES],
    secondary: [
      TAG_SLUGS.CREME_MAINS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ZONE_MAINS,
    ],
    avoid: [],
  },
}
