import { TAG_SLUGS } from '../../tags/seed-tags'
import { URIAGE_PRODUCT_SLUGS } from './uriage'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const URIAGE_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  [URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.ECZEMA],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.CREME_CORPS,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },
  
  [URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BRILLANCE],
    secondary: [
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PIGMENTS_VERTS,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.HUILE_NETTOYANTE,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.BAUME,
      TAG_SLUGS.OCCLUSION,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.GEL_NETTOYANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.DOUBLE_NETTOYAGE_2,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PIGMENTS_VERTS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.PROTECTION_SOLAIRE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.PIGMENTS_VERTS,
      TAG_SLUGS.CREME_SOLAIRE_TEINTEE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },
}
