import { TAG_SLUGS } from '../../tags/seed-tags'
import { ADERMA_PRODUCT_SLUGS } from './aDerma'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const ADERMA_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT]: {
    primary: [
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  
  [ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.NETTOYANT],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.HUILE_NETTOYANTE,
      TAG_SLUGS.HUILE_VISAGE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
    avoid: [],
  },

  
  [ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.NETTOYANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.GEL_NETTOYANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  
  [ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ],
    avoid: [],
  },
}
