import { TAG_SLUGS } from '../../tags/seed-tags'
import { SOLAIRES_PRODUCT_SLUGS } from './solaires'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const SOLAIRES_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [SOLAIRES_PRODUCT_SLUGS.ACTINICA_LOTION_SPF50_LOT3]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  
  [SOLAIRES_PRODUCT_SLUGS.EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.EUCERIN_LEB_PROTECT_CREME_GEL_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  
  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_FACE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_URBAN_SHIELD_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.POLLUTION],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_SKIN_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },
}
