import { TAG_SLUGS } from '../../tags/seed-tags'
import { ISISPHARMA_PRODUCT_SLUGS } from './isispharma'

interface ProductTagGroups {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const ISISPHARMA_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_S]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
  },

  
  [ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
    secondary: [
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },
}
