#!/usr/bin/env bun
/**
 * import-candidates.ts — Bulk-import reviewed candidates to data/products/.
 *
 * For each candidate file under output/candidates/:
 *   - dynamic-import the module to get a typed UnifiedProductSeed[]
 *   - skip products with empty primary tags
 *   - skip products whose slug already exists somewhere in data/products/
 *   - normalize name (strip brand prefix, Title Case, preserve short acronyms)
 *   - emit TS into data/products/{topCat}/{brandFsName}/{filename}
 *
 * After all candidates processed, append imports + spreads to data/products/index.ts.
 *
 * Usage:
 *   bun run backend/src/db/seed/scripts/import-candidates.ts            # dry run
 *   bun run backend/src/db/seed/scripts/import-candidates.ts --apply    # write files + index
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

import type { UnifiedProductSeed } from '../data/products/types'
import { INGREDIENT_SLUGS } from '../data/products/types'

const APPLY = process.argv.includes('--apply')

const SEED_ROOT = join(import.meta.dir, '..')
const CANDIDATES_DIR = join(SEED_ROOT, 'output', 'candidates')
const PRODUCTS_DIR = join(SEED_ROOT, 'data', 'products')
const PRODUCTS_INDEX = join(PRODUCTS_DIR, 'index.ts')

// candidate parent dir → data/products/ parent dir.
// data/products/ has only 4 top-level cats (skincare/haircare/dental/supplement).
// bodycare + solaire products live under skincare/, complement under supplement/.
const CATEGORY_TO_PARENT: Record<string, string> = {
  skincare: 'skincare',
  bodycare: 'skincare',
  solaire: 'skincare',
  haircare: 'haircare',
  dental: 'dental',
  complement: 'supplement',
}

// Hand-crafted mapping for brands whose existing dir doesn't normalize to the
// candidate slug (e.g. `laRochePosay` vs candidate `roche-posay`). Filled in
// post first dry-run when console reports a "new" dir that should reuse one.
const BRAND_DIR_OVERRIDES: Record<string, string> = {
  'roche-posay': 'laRochePosay',
  'la-roche-posay': 'laRochePosay',
  vichy: 'vichy-laboratories',
  'laboratoires-de-biarritz': 'labBiarritz',
}

// Pseudo-brands generated by aggregator source files (Atida `douche-bain.ts`,
// `cheveux.ts`, …). Their products lack a real brand attribution. Skip the file
// outright; review manually to attribute brands later.
const SKIP_BRANDS = new Set(['douche-bain'])

// Reverse map: ingredient slug → INGREDIENT_SLUGS const key (for emit).
const SLUG_TO_INGREDIENT_KEY: Record<string, string> = {}
for (const [k, v] of Object.entries(INGREDIENT_SLUGS)) {
  if (typeof v === 'string') SLUG_TO_INGREDIENT_KEY[v] = k
}

// ─── Brand dir resolution ────────────────────────────────────────────────────

function normalizeBrandKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '')
}

function listBrandDirs(parent: string): string[] {
  const dir = join(PRODUCTS_DIR, parent)
  if (!existsSync(dir)) return []
  return readdirSync(dir).filter((n) => statSync(join(dir, n)).isDirectory())
}

const ALL_PARENTS = ['skincare', 'haircare', 'dental', 'supplement']

/**
 * Find the existing brand dir across ALL top-level parents (skincare/haircare/…).
 * Existing convention puts each brand in a single dir, regardless of which categories
 * its products span. So `eucerin` lives under `skincare/eucerin/` even though it has
 * haircare and bodycare products. Returns `{ parent, name }` or null.
 */
function findExistingBrandDir(brandSlug: string): { parent: string; name: string } | null {
  if (BRAND_DIR_OVERRIDES[brandSlug]) {
    // Override gives the dir name; locate which parent owns it.
    const target = BRAND_DIR_OVERRIDES[brandSlug]
    for (const parent of ALL_PARENTS) {
      if (listBrandDirs(parent).includes(target)) return { parent, name: target }
    }
    return null
  }
  const slugKey = normalizeBrandKey(brandSlug)
  for (const parent of ALL_PARENTS) {
    for (const name of listBrandDirs(parent)) {
      if (normalizeBrandKey(name) === slugKey) return { parent, name }
    }
  }
  return null
}

// ─── Existing slug index ─────────────────────────────────────────────────────

const PRODUCT_SLUG_RE = /^ {4}slug:\s*['"]([^'"]+)['"]/gm
const INDEX_NAMED_IMPORT_RE = /import\s+\{\s*([^}]+)\s*\}\s+from '\.\/([^']+)'/g

function indexedProductSeedImports(): Array<{ filePath: string; exportName: string }> {
  if (!existsSync(PRODUCTS_INDEX)) return []
  const text = readFileSync(PRODUCTS_INDEX, 'utf-8')
  return [...text.matchAll(INDEX_NAMED_IMPORT_RE)]
    .map((m) => {
      const exportName = m[1].split(/\s+as\s+/)[0]?.trim()
      return exportName ? { filePath: join(PRODUCTS_DIR, `${m[2]}.ts`), exportName } : null
    })
    .filter((entry): entry is { filePath: string; exportName: string } => entry !== null)
}

function addProductSlugs(slugs: Set<string>, filePath: string): void {
  const text = readFileSync(filePath, 'utf-8')
  for (const m of text.matchAll(PRODUCT_SLUG_RE)) slugs.add(m[1])
}

async function addProductSlugsFromExport(
  slugs: Set<string>,
  filePath: string,
  exportName: string
): Promise<boolean> {
  try {
    const mod = (await import(pathToFileURL(filePath).href)) as Record<string, unknown>
    const products = mod[exportName]
    if (!Array.isArray(products)) return false
    for (const product of products as UnifiedProductSeed[]) {
      if (typeof product.slug === 'string') slugs.add(product.slug)
    }
    return true
  } catch {
    return false
  }
}

async function loadExistingSlugs(): Promise<Set<string>> {
  const slugs = new Set<string>()
  const indexedImports = indexedProductSeedImports()
  if (indexedImports.length > 0) {
    for (const { filePath, exportName } of indexedImports) {
      if (!existsSync(filePath)) continue
      const loaded = await addProductSlugsFromExport(slugs, filePath, exportName)
      if (!loaded) addProductSlugs(slugs, filePath)
    }
    return slugs
  }

  function walk(dir: string): void {
    for (const name of readdirSync(dir)) {
      const full = join(dir, name)
      const st = statSync(full)
      if (st.isDirectory()) walk(full)
      else if (name.endsWith('.seed.ts') || name === 'noreva.ts') {
        addProductSlugs(slugs, full)
      }
    }
  }
  walk(PRODUCTS_DIR)
  return slugs
}

// ─── Name normalization ──────────────────────────────────────────────────────

function titleCaseName(name: string, brand: string): string {
  const tokens = name.split(/\s+/).filter(Boolean)
  if (tokens.length === 0) return name

  // Strip a leading run of tokens that concatenate (lowercased) to the brand key.
  // Handles "ADERMA" (1 token), "LA ROCHE POSAY" (3 tokens), etc.
  const brandKey = normalizeBrandKey(brand)
  let stripped = 0
  let acc = ''
  for (let i = 0; i < tokens.length; i++) {
    acc += tokens[i].toLowerCase().replace(/[^a-z0-9]/g, '')
    if (acc === brandKey) {
      stripped = i + 1
      break
    }
    if (!brandKey.startsWith(acc)) break
  }

  const rest = tokens.slice(stripped)
  return rest.map(normalizeNameToken).join(' ')
}

const UPPERCASE_NAME_TOKENS = new Set([
  'AC',
  'AH',
  'AHA',
  'AP',
  'AR',
  'BB',
  'BHA',
  'CC',
  'CICA',
  'DS',
  'HA',
  'LP',
  'PHA',
  'PSO',
  'SOS',
  'SPF',
  'UVA',
  'UVB',
  'UV',
])

const LOWERCASE_NAME_TOKENS = new Set([
  'a',
  'à',
  'au',
  'aux',
  'avec',
  'd',
  'de',
  'des',
  'du',
  'en',
  'et',
  'la',
  'le',
  'les',
  'l',
  'pour',
  'sans',
  'sur',
])

function normalizeNameToken(token: string, index: number): string {
  if (/^\d/.test(token)) return token.toLowerCase()
  if (/^spf\d*\+?$/i.test(token)) return token.toUpperCase()

  const lower = token.toLocaleLowerCase('fr-FR')
  if (index > 0 && LOWERCASE_NAME_TOKENS.has(lower)) return lower

  const trailing = token.match(/^(.+?)([.,;:!?]*)$/)
  const body = trailing?.[1] ?? token
  const suffix = trailing?.[2] ?? ''
  const upperBody = body.toUpperCase()
  if (UPPERCASE_NAME_TOKENS.has(upperBody)) return `${upperBody}${suffix}`

  return (
    body
      .toLocaleLowerCase('fr-FR')
      .replace(/(^|[-'’])(\p{L})/gu, (_m, sep: string, letter: string) => {
        return `${sep}${letter.toLocaleUpperCase('fr-FR')}`
      }) + suffix
  )
}

// ─── TS emit ─────────────────────────────────────────────────────────────────

function escSingle(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n')
}

function emitProduct(p: UnifiedProductSeed): string {
  const lines: string[] = ['  {']
  lines.push(`    slug: '${escSingle(p.slug)}',`)
  lines.push(`    name: '${escSingle(p.name)}',`)
  lines.push(`    brand: '${escSingle(p.brand)}',`)
  lines.push(`    kind: '${p.kind}',`)
  lines.push(`    unit: '${p.unit}',`)
  lines.push(`    totalAmount: ${p.totalAmount},`)
  lines.push(`    amountUnit: '${escSingle(p.amountUnit)}',`)
  lines.push(`    priceCents: ${p.priceCents},`)
  lines.push(`    description: '${escSingle(p.description)}',`)
  if (p.notes !== undefined) lines.push(`    notes: '${escSingle(p.notes)}',`)
  if (p.inci !== undefined) lines.push(`    inci: '${escSingle(p.inci)}',`)
  if (p.url !== undefined) lines.push(`    url: '${escSingle(p.url)}',`)
  if (p.imageUrl !== undefined) lines.push(`    imageUrl: '${escSingle(p.imageUrl)}',`)
  lines.push('    tags: {')
  lines.push(`      primary: [${p.tags.primary.map((t) => `'${escSingle(t)}'`).join(', ')}],`)
  lines.push(`      secondary: [${p.tags.secondary.map((t) => `'${escSingle(t)}'`).join(', ')}],`)
  lines.push(`      avoid: [${p.tags.avoid.map((t) => `'${escSingle(t)}'`).join(', ')}],`)
  lines.push('    },')
  if (p.keyIngredients && p.keyIngredients.length > 0) {
    lines.push('    keyIngredients: [')
    for (const ki of p.keyIngredients) {
      const slugRef = SLUG_TO_INGREDIENT_KEY[ki.slug]
        ? `INGREDIENT_SLUGS.${SLUG_TO_INGREDIENT_KEY[ki.slug]}`
        : `'${escSingle(ki.slug)}'`
      const parts: string[] = [`slug: ${slugRef}`]
      if (ki.notes) parts.push(`notes: '${escSingle(ki.notes)}'`)
      if (ki.concentrationValue !== undefined)
        parts.push(`concentrationValue: ${ki.concentrationValue}`)
      if (ki.concentrationUnit)
        parts.push(`concentrationUnit: '${escSingle(ki.concentrationUnit)}'`)
      lines.push(`      { ${parts.join(', ')} },`)
    }
    lines.push('    ],')
  }
  lines.push('  },')
  return lines.join('\n')
}

function emitFile(products: UnifiedProductSeed[], exportName: string): string {
  const usesIngSlug = products.some((p) => p.keyIngredients && p.keyIngredients.length > 0)
  const out: string[] = []
  out.push(`import type { UnifiedProductSeed } from '../../types'`)
  if (usesIngSlug) out.push(`import { INGREDIENT_SLUGS } from '../../types'`)
  out.push('')
  out.push(`export const ${exportName}: UnifiedProductSeed[] = [`)
  for (const p of products) out.push(emitProduct(p))
  out.push(']')
  out.push('')
  return out.join('\n')
}

// ─── Main ────────────────────────────────────────────────────────────────────

interface OutputGroup {
  parent: string
  brandFsName: string
  filename: string
  exportName: string
  products: UnifiedProductSeed[]
}

function buildExportName(brandFsName: string, isPharmashop: boolean): string {
  // brandFsName can be camelCase (`aDerma`), kebab (`a-derma`), or compound
  // (`vichy-laboratories`). Normalize to UPPER_SNAKE.
  const base = brandFsName
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase()
  return `${base}_${isPharmashop ? 'PHARMASHOP' : 'ATIDA'}_SEED`
}

async function main(): Promise<void> {
  console.log(`import-candidates — ${APPLY ? 'APPLY' : 'DRY-RUN'}`)

  const seenSlugs = await loadExistingSlugs()
  console.log(`  existing slugs in data/products/: ${seenSlugs.size}`)

  const outputs = new Map<string, OutputGroup>()
  const newDirs = new Set<string>()
  // Track which parent-dir we picked for new brands so subsequent candidate files
  // of the same brand (e.g. mustela skincare + mustela haircare) coalesce into
  // one dir instead of forking by candidate-cat.
  const brandToChosenParent = new Map<string, string>()
  let scanned = 0
  let skippedEmptyPrimary = 0
  let skippedCollision = 0

  const catDirs = readdirSync(CANDIDATES_DIR).sort()
  for (const candidateCat of catDirs) {
    const catDir = join(CANDIDATES_DIR, candidateCat)
    if (!statSync(catDir).isDirectory()) continue
    const fallbackParent = CATEGORY_TO_PARENT[candidateCat]
    if (!fallbackParent) {
      console.warn(`  ⚠ unknown candidate category: ${candidateCat}, skipping`)
      continue
    }

    for (const file of readdirSync(catDir).sort()) {
      if (!file.endsWith('.seed.ts')) continue
      const fullPath = join(catDir, file)
      const isPharmashop = file.endsWith('.pharmashop.seed.ts')
      const brandSlug = file.replace(/\.(?:pharmashop\.)?seed\.ts$/, '')
      if (SKIP_BRANDS.has(brandSlug)) {
        console.warn(`  ⊘ ${candidateCat}/${file}: pseudo-brand, skipping entire file`)
        continue
      }

      // Dynamic import — Bun TS-compiles on the fly
      let mod: Record<string, unknown>
      try {
        mod = (await import(fullPath)) as Record<string, unknown>
      } catch (err) {
        console.warn(`  ⚠ ${candidateCat}/${file}: import failed (${(err as Error).message}), skip`)
        continue
      }
      const exportKey = Object.keys(mod).find((k) => k.endsWith('_SEED'))
      if (!exportKey) {
        console.warn(`  ⚠ ${candidateCat}/${file}: no *_SEED export, skip`)
        continue
      }
      const products = mod[exportKey] as UnifiedProductSeed[]
      if (!Array.isArray(products) || products.length === 0) continue

      // Find brand dir across all parents (existing convention: 1 brand = 1 dir).
      // If no existing dir but we already picked a parent earlier for this brand,
      // reuse it so multi-cat candidates of the same new brand coalesce. Else
      // fall back to the candidate-cat's parent + kebab slug.
      const existing = findExistingBrandDir(brandSlug)
      const previousChoice = brandToChosenParent.get(brandSlug)
      const parent = existing?.parent ?? previousChoice ?? fallbackParent
      const brandFsName = existing?.name ?? brandSlug
      if (!existing) {
        newDirs.add(`${parent}/${brandFsName}`)
        if (!previousChoice) brandToChosenParent.set(brandSlug, parent)
      }

      // All candidate files of (brand, source) merge into ONE output file. The
      // candidate-cat is encoded into the filename only when it differs from the
      // dir's parent — keeps the dir tidy when most products belong there.
      // Always suffix with `.atida` or `.pharmashop` so we never collide with the
      // existing curated `{brand}.seed.ts` file.
      const isCrossCat = parent !== fallbackParent
      const catSuffix = isCrossCat ? `-${candidateCat}` : ''
      const sourceSuffix = isPharmashop ? 'pharmashop' : 'atida'
      const filename = `${brandFsName}${catSuffix}.${sourceSuffix}.seed.ts`
      const groupKey = `${parent}/${brandFsName}/${filename}`
      let group = outputs.get(groupKey)
      if (!group) {
        group = {
          parent,
          brandFsName,
          filename,
          exportName: buildExportName(`${brandFsName}${catSuffix}`, isPharmashop),
          products: [],
        }
        outputs.set(groupKey, group)
      }

      for (const p of products) {
        scanned++
        if (!p.tags?.primary || p.tags.primary.length === 0) {
          skippedEmptyPrimary++
          continue
        }
        if (seenSlugs.has(p.slug)) {
          skippedCollision++
          continue
        }
        seenSlugs.add(p.slug)
        const newName = titleCaseName(p.name, p.brand)
        // Dedupe tags across the three relevance buckets. Auto-tag's NAME_PATTERN can
        // emit a tag (e.g. `peau-sensible` on a "Peaux Sensibles" product) while
        // INCI_TO_AVOID also marks it as avoid via an aggressive acid mapping. Avoid
        // wins over primary, primary wins over secondary.
        const avoidSet = new Set(p.tags.avoid)
        const dedupedPrimary = p.tags.primary.filter((t) => !avoidSet.has(t))
        const primarySet = new Set(dedupedPrimary)
        const dedupedSecondary = p.tags.secondary.filter(
          (t) => !avoidSet.has(t) && !primarySet.has(t)
        )
        group.products.push({
          ...p,
          name: newName,
          tags: { primary: dedupedPrimary, secondary: dedupedSecondary, avoid: p.tags.avoid },
        })
      }
    }
  }

  let totalKept = 0
  let nonEmptyGroups = 0
  for (const g of outputs.values()) {
    if (g.products.length > 0) {
      totalKept += g.products.length
      nonEmptyGroups++
    }
  }

  console.log('')
  console.log(`  scanned          : ${scanned}`)
  console.log(`  skip empty primary: ${skippedEmptyPrimary}`)
  console.log(`  skip slug collision: ${skippedCollision}`)
  console.log(`  kept             : ${totalKept}`)
  console.log(`  output files     : ${nonEmptyGroups}`)
  console.log(`  new brand dirs   : ${newDirs.size}`)
  if (newDirs.size <= 30) {
    for (const d of [...newDirs].sort()) console.log(`    + ${d}/`)
  } else {
    for (const d of [...newDirs].sort().slice(0, 15)) console.log(`    + ${d}/`)
    console.log(`    … +${newDirs.size - 15} more`)
  }

  if (!APPLY) {
    console.log('\n  Dry-run. Re-run with --apply to write.')
    return
  }

  // Write seed files
  let written = 0
  let conflictSkipped = 0
  for (const g of outputs.values()) {
    if (g.products.length === 0) continue
    const dirPath = join(PRODUCTS_DIR, g.parent, g.brandFsName)
    if (!existsSync(dirPath)) mkdirSync(dirPath, { recursive: true })
    const targetPath = join(dirPath, g.filename)
    if (existsSync(targetPath)) {
      console.warn(`  ⊘ ${g.parent}/${g.brandFsName}/${g.filename} (file exists, skip)`)
      conflictSkipped++
      continue
    }
    writeFileSync(targetPath, emitFile(g.products, g.exportName), 'utf-8')
    written++
  }
  console.log(`\n  wrote ${written} files (${conflictSkipped} skipped due to existing file)`)

  // Update index.ts
  const indexText = readFileSync(PRODUCTS_INDEX, 'utf-8')
  const newImports: string[] = []
  const newSpreads: string[] = []
  for (const g of outputs.values()) {
    if (g.products.length === 0) continue
    const importPath = `./${g.parent}/${g.brandFsName}/${g.filename.replace(/\.ts$/, '')}`
    newImports.push(`import { ${g.exportName} } from '${importPath}'`)
    newSpreads.push(`  ...${g.exportName},`)
  }

  const aggMarker = '\n// ── Aggregation'
  const aggIdx = indexText.indexOf(aggMarker)
  if (aggIdx < 0) {
    console.error('  ✗ Could not find "// ── Aggregation" marker in index.ts; please add manually.')
    return
  }
  const allCloseMarker = '\n]\n\n// ── Derived'
  const allCloseIdx = indexText.indexOf(allCloseMarker, aggIdx)
  if (allCloseIdx < 0) {
    console.error('  ✗ Could not find allUnified array close in index.ts; please add manually.')
    return
  }

  const before = indexText.slice(0, aggIdx)
  const middle = indexText.slice(aggIdx, allCloseIdx)
  const after = indexText.slice(allCloseIdx)

  const importBlock =
    '\n// ── Imported candidates (bulk via scripts/import-candidates.ts) ──────────────\n' +
    newImports.join('\n') +
    '\n'
  const spreadBlock = `\n  // imported candidates\n${newSpreads.join('\n')}`

  const next = `${before}${importBlock}${middle}${spreadBlock}${after}`
  writeFileSync(PRODUCTS_INDEX, next, 'utf-8')
  console.log(`  ✓ index.ts updated (+${newImports.length} imports, +${newSpreads.length} spreads)`)
}

main().catch((err) => {
  console.error('\n✗ Import failed:', err)
  process.exit(1)
})
