#!/usr/bin/env bun
/**
 * reset-imported-products.ts — Remove product seed files generated by
 * import-candidates.ts and clean their index.ts imports/spreads.
 *
 * Usage:
 *   bun run backend/src/db/seed/scripts/reset-imported-products.ts
 *   bun run backend/src/db/seed/scripts/reset-imported-products.ts --apply
 */

import { existsSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const APPLY = process.argv.includes('--apply')

const SEED_ROOT = join(import.meta.dir, '..')
const PRODUCTS_DIR = join(SEED_ROOT, 'data', 'products')
const PRODUCTS_INDEX = join(PRODUCTS_DIR, 'index.ts')

const GENERATED_FILE_RE = /\.(?:atida|pharmashop)\.seed\.ts$/
const GENERATED_IMPORT_SOURCE_RE = /\.(?:atida|pharmashop)\.seed$/
const IMPORT_LINE_RE = /^import\s+\{\s*([^}]+)\s*\}\s+from\s+'\.\/([^']+)'$/
const SPREAD_LINE_RE = /^(\s*)\.\.\.([A-Z0-9_]+),\s*(?:\/\/.*)?$/

function importLocalNames(specifier: string): string[] {
  return specifier
    .split(',')
    .map((part) => {
      const alias = part.split(/\s+as\s+/).at(-1)
      return alias?.trim() ?? ''
    })
    .filter(Boolean)
}

function listGeneratedSeedFiles(dir: string): string[] {
  if (!existsSync(dir)) return []

  const files: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const stat = statSync(full)
    if (stat.isDirectory()) {
      files.push(...listGeneratedSeedFiles(full))
      continue
    }
    if (GENERATED_FILE_RE.test(name)) files.push(full)
  }
  return files.sort()
}

function cleanIndex(text: string): {
  nextText: string
  removedImportCount: number
  removedSpreadCount: number
} {
  const generatedExports = new Set<string>()
  const withoutGeneratedImports: string[] = []
  let removedImportCount = 0

  for (const line of text.split('\n')) {
    if (line.includes('Imported candidates (bulk via scripts/import-candidates.ts)')) continue

    const importMatch = line.match(IMPORT_LINE_RE)
    if (importMatch && GENERATED_IMPORT_SOURCE_RE.test(importMatch[2])) {
      for (const name of importLocalNames(importMatch[1])) generatedExports.add(name)
      removedImportCount++
      continue
    }

    withoutGeneratedImports.push(line.replace(/\s+\/\/ imported candidates$/, ''))
  }

  const cleaned: string[] = []
  let removedSpreadCount = 0
  for (const line of withoutGeneratedImports) {
    if (line.trim() === '// imported candidates') continue

    const spreadMatch = line.match(SPREAD_LINE_RE)
    if (spreadMatch && generatedExports.has(spreadMatch[2])) {
      removedSpreadCount++
      continue
    }

    cleaned.push(line)
  }

  return {
    nextText: cleaned.join('\n'),
    removedImportCount,
    removedSpreadCount,
  }
}

function main(): void {
  console.log(`reset-imported-products — ${APPLY ? 'APPLY' : 'DRY-RUN'}`)

  const generatedFiles = listGeneratedSeedFiles(PRODUCTS_DIR)
  const indexText = readFileSync(PRODUCTS_INDEX, 'utf-8')
  const { nextText, removedImportCount, removedSpreadCount } = cleanIndex(indexText)

  console.log(`  generated files : ${generatedFiles.length}`)
  console.log(`  index imports   : ${removedImportCount}`)
  console.log(`  index spreads    : ${removedSpreadCount}`)

  for (const file of generatedFiles.slice(0, 12)) {
    console.log(`    - ${relative(PRODUCTS_DIR, file)}`)
  }
  if (generatedFiles.length > 12) console.log(`    … +${generatedFiles.length - 12} more`)

  if (!APPLY) {
    console.log('\n  Dry-run. Re-run with --apply to delete generated files and update index.ts.')
    return
  }

  writeFileSync(PRODUCTS_INDEX, nextText, 'utf-8')
  for (const file of generatedFiles) unlinkSync(file)

  console.log('\n  ✓ generated imports removed from index.ts')
  console.log(`  ✓ deleted ${generatedFiles.length} generated seed files`)
}

main()
