import { PRODUCT_TAG_SLUGS, type ProductTagSlug } from './tag-slugs'

export const PRODUCT_TAG_CATEGORIES = [
  'concern',
  'skin_type',
  'skin_zone',
  'product_type',
  'routine_step',
  'skin_effect',
  'product_label',
  'shared_label',
] as const

export type ProductTagCategory = (typeof PRODUCT_TAG_CATEGORIES)[number]

export interface ProductTagMeta {
  category: ProductTagCategory
}

const CONCERN: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.ANTI_ROUGEURS,
  PRODUCT_TAG_SLUGS.ROSACEE,
  PRODUCT_TAG_SLUGS.COUPEROSE,
  PRODUCT_TAG_SLUGS.FLUSHS,
  PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE,
  PRODUCT_TAG_SLUGS.ANTI_TACHES,
  PRODUCT_TAG_SLUGS.ANTI_ACNE,
  PRODUCT_TAG_SLUGS.ANTI_AGE,
  PRODUCT_TAG_SLUGS.HYPERPIGMENTATION,
  PRODUCT_TAG_SLUGS.DESHYDRATATION,
  PRODUCT_TAG_SLUGS.PORES_DILATES,
  PRODUCT_TAG_SLUGS.CERNES_POCHES,
  PRODUCT_TAG_SLUGS.BRILLANCE,
  PRODUCT_TAG_SLUGS.ECLAT,
  PRODUCT_TAG_SLUGS.POST_ACNE,
  PRODUCT_TAG_SLUGS.CICATRISATION,
  PRODUCT_TAG_SLUGS.MICROBIOME,
  PRODUCT_TAG_SLUGS.PHOTO_VIEILLISSEMENT,
  PRODUCT_TAG_SLUGS.TEINT_TERNE,
  PRODUCT_TAG_SLUGS.LUMIERE_BLEUE,
  PRODUCT_TAG_SLUGS.POLLUTION,
  PRODUCT_TAG_SLUGS.ECZEMA,
  PRODUCT_TAG_SLUGS.GRAIN_PEAU,
  PRODUCT_TAG_SLUGS.KERATOSE_PILAIRE,
  PRODUCT_TAG_SLUGS.PHOTO_PROTECTION,
  PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
]

const SKIN_TYPE: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.PEAU_SECHE,
  PRODUCT_TAG_SLUGS.PEAU_MIXTE,
  PRODUCT_TAG_SLUGS.PEAU_GRASSE,
  PRODUCT_TAG_SLUGS.PEAU_REACTIVE,
  PRODUCT_TAG_SLUGS.PEAU_SENSIBLE,
  PRODUCT_TAG_SLUGS.PEAU_NORMALE,
  PRODUCT_TAG_SLUGS.PEAU_ATOPIQUE,
  PRODUCT_TAG_SLUGS.PEAU_RUGUEUSE,
  PRODUCT_TAG_SLUGS.PEAU_TOUS_TYPES,
]

const SKIN_ZONE: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.ZONE_VISAGE,
  PRODUCT_TAG_SLUGS.ZONE_CORPS,
  PRODUCT_TAG_SLUGS.ZONE_YEUX,
  PRODUCT_TAG_SLUGS.ZONE_LEVRES,
  PRODUCT_TAG_SLUGS.ZONE_MAINS,
]

const PRODUCT_TYPE: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.BAUME_DEMAQUILLANT,
  PRODUCT_TAG_SLUGS.HUILE_DEMAQUILLANTE,
  PRODUCT_TAG_SLUGS.HUILE_NETTOYANTE,
  PRODUCT_TAG_SLUGS.GEL_NETTOYANT,
  PRODUCT_TAG_SLUGS.MOUSSE_NETTOYANTE,
  PRODUCT_TAG_SLUGS.LAIT_NETTOYANT,
  PRODUCT_TAG_SLUGS.CREME_NETTOYANTE,
  PRODUCT_TAG_SLUGS.EAU_MICELLAIRE,
  PRODUCT_TAG_SLUGS.TONIQUE,
  PRODUCT_TAG_SLUGS.ESSENCE,
  PRODUCT_TAG_SLUGS.LOTION,
  PRODUCT_TAG_SLUGS.BRUME,
  PRODUCT_TAG_SLUGS.PRIMER,
  PRODUCT_TAG_SLUGS.SERUM,
  PRODUCT_TAG_SLUGS.AMPOULE,
  PRODUCT_TAG_SLUGS.HUILE_VISAGE,
  PRODUCT_TAG_SLUGS.SPOT_TREATMENT,
  PRODUCT_TAG_SLUGS.CREME_HYDRATANTE,
  PRODUCT_TAG_SLUGS.GEL_CREME,
  PRODUCT_TAG_SLUGS.CREME_DE_NUIT,
  PRODUCT_TAG_SLUGS.BAUME,
  PRODUCT_TAG_SLUGS.SLEEPING_MASK,
  PRODUCT_TAG_SLUGS.CONTOUR_YEUX,
  PRODUCT_TAG_SLUGS.SOIN_LEVRES,
  PRODUCT_TAG_SLUGS.EXFOLIANT_CHIMIQUE,
  PRODUCT_TAG_SLUGS.EXFOLIANT_PHYSIQUE,
  PRODUCT_TAG_SLUGS.MASQUE_ARGILE,
  PRODUCT_TAG_SLUGS.MASQUE_TISSU,
  PRODUCT_TAG_SLUGS.MASQUE_HYDRATANT,
  PRODUCT_TAG_SLUGS.CREME_SOLAIRE,
  PRODUCT_TAG_SLUGS.CREME_SOLAIRE_TEINTEE,
  PRODUCT_TAG_SLUGS.APRES_SOLEIL,
  PRODUCT_TAG_SLUGS.AUTO_BRONZANT,
  PRODUCT_TAG_SLUGS.LAIT_CORPS,
  PRODUCT_TAG_SLUGS.CREME_CORPS,
  PRODUCT_TAG_SLUGS.CREME_MAINS,
  PRODUCT_TAG_SLUGS.HUILE_CORPS,
  PRODUCT_TAG_SLUGS.GOMMAGE_CORPS,
  PRODUCT_TAG_SLUGS.NETTOYANT_CORPS,
  PRODUCT_TAG_SLUGS.DEODORANT,
  PRODUCT_TAG_SLUGS.CREME_PIEDS,
  PRODUCT_TAG_SLUGS.SHAMPOING,
  PRODUCT_TAG_SLUGS.APRES_SHAMPOING,
  PRODUCT_TAG_SLUGS.MASQUE_CHEVEUX,
  PRODUCT_TAG_SLUGS.SERUM_CHEVEUX,
  PRODUCT_TAG_SLUGS.HUILE_CHEVEUX,
  PRODUCT_TAG_SLUGS.PRODUIT_COIFFANT,
  PRODUCT_TAG_SLUGS.DENTIFRICE,
  PRODUCT_TAG_SLUGS.BAIN_DE_BOUCHE,
  PRODUCT_TAG_SLUGS.BLANCHIMENT_DENTAIRE,
  PRODUCT_TAG_SLUGS.FIL_DENTAIRE,
  PRODUCT_TAG_SLUGS.GELULE,
  PRODUCT_TAG_SLUGS.CAPSULE,
  PRODUCT_TAG_SLUGS.POUDRE,
  PRODUCT_TAG_SLUGS.SIROP,
  PRODUCT_TAG_SLUGS.GUMMY,
  PRODUCT_TAG_SLUGS.PATCH,
  PRODUCT_TAG_SLUGS.OUTIL_MASSAGE,
]

const ROUTINE_STEP: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.MATIN,
  PRODUCT_TAG_SLUGS.SOIR,
  PRODUCT_TAG_SLUGS.NETTOYANT,
  PRODUCT_TAG_SLUGS.DOUBLE_NETTOYAGE_1,
  PRODUCT_TAG_SLUGS.DOUBLE_NETTOYAGE_2,
  PRODUCT_TAG_SLUGS.PREPARATION,
  PRODUCT_TAG_SLUGS.TRAITEMENT,
  PRODUCT_TAG_SLUGS.HYDRATATION,
  PRODUCT_TAG_SLUGS.EMOLLIENCE,
  PRODUCT_TAG_SLUGS.PROTECTION_SOLAIRE,
  PRODUCT_TAG_SLUGS.OCCLUSION,
  PRODUCT_TAG_SLUGS.SOIN_YEUX,
  PRODUCT_TAG_SLUGS.SOIN_LOCALISE,
  PRODUCT_TAG_SLUGS.EXFOLIATION,
  PRODUCT_TAG_SLUGS.MASQUE_HEBDO,
]

const SKIN_EFFECT: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.OCCLUSIF,
  PRODUCT_TAG_SLUGS.REPULPANT,
  PRODUCT_TAG_SLUGS.MATIFIANT,
  PRODUCT_TAG_SLUGS.PROTECTION_CUTANEE,
  PRODUCT_TAG_SLUGS.TEXTURE_RICHE,
  PRODUCT_TAG_SLUGS.TEXTURE_LEGERE,
  PRODUCT_TAG_SLUGS.ANTI_OXYDANT,
  PRODUCT_TAG_SLUGS.APAISANT,
  PRODUCT_TAG_SLUGS.SEBO_REGULATEUR,
  PRODUCT_TAG_SLUGS.REPARATEUR,
  PRODUCT_TAG_SLUGS.PURIFIANT,
  PRODUCT_TAG_SLUGS.PREBIOTIQUE,
  PRODUCT_TAG_SLUGS.KERATOLYTIQUE,
]

const PRODUCT_LABEL: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.SANS_PARFUM,
  PRODUCT_TAG_SLUGS.BIO_NATUREL,
  PRODUCT_TAG_SLUGS.VEGAN,
  PRODUCT_TAG_SLUGS.CRUELTY_FREE,
  PRODUCT_TAG_SLUGS.HYPOALLERGENIQUE,
  PRODUCT_TAG_SLUGS.PIGMENTS_VERTS,
  PRODUCT_TAG_SLUGS.SANS_SAVON,
  PRODUCT_TAG_SLUGS.FILTRES_CHIMIQUES,
  PRODUCT_TAG_SLUGS.FILTRES_MINERAUX,
  PRODUCT_TAG_SLUGS.GROSSESSE_COMPATIBLE,
]

const SHARED_LABEL: ProductTagSlug[] = [
  PRODUCT_TAG_SLUGS.COMEDOGENE,
  PRODUCT_TAG_SLUGS.NON_COMEDOGENE,
]

const entries: [ProductTagSlug, ProductTagMeta][] = [
  ...CONCERN.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'concern' }]),
  ...SKIN_TYPE.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'skin_type' }]),
  ...SKIN_ZONE.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'skin_zone' }]),
  ...PRODUCT_TYPE.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'product_type' }]),
  ...ROUTINE_STEP.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'routine_step' }]),
  ...SKIN_EFFECT.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'skin_effect' }]),
  ...PRODUCT_LABEL.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'product_label' }]),
  ...SHARED_LABEL.map((s): [ProductTagSlug, ProductTagMeta] => [s, { category: 'shared_label' }]),
]

export const PRODUCT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  ProductTagSlug,
  ProductTagMeta
>

export function getProductTagCategory(slug: ProductTagSlug): ProductTagCategory | undefined {
  return PRODUCT_TAG_TAXONOMY[slug]?.category
}
