import { TAG_SLUGS } from '../../tags/seed-tags'
import { TONERS_PRODUCT_SLUGS } from './toners'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const TONERS_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.HYDRATATION, TAG_SLUGS.TEINT_TERNE],
    secondary: [
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  
  [TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.PORES_DILATES],
    secondary: [
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.NUMBUZIN_NO9_NAD_PDRN_GLOW]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.NUMBUZIN_NO1_PURE_FULL_CALMING]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.NUMBUZIN_NO5_GLUTATHIONE_VITAMIN]: {
    primary: [
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ECLAT,
    ],
    secondary: [
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [TONERS_PRODUCT_SLUGS.ROUND_LAB_1025_DOKDO]: {
    primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },
}
