import { TAG_SLUGS } from '../../tags/seed-tags'
import { KOREAN_PRODUCT_SLUGS } from './koreanSkincare'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const KOREAN_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.ESSENCE,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [KOREAN_PRODUCT_SLUGS.SOME_BY_MI_30_DAYS_MIRACLE_PATCH]: {
    primary: [TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.PATCH,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.CRUELTY_FREE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  
  [KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.OCCLUSION,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE],
  },

  
  [KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST]: {
    primary: [TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE],
  },
}
