import { TAG_SLUGS } from "../../tags/seed-tags";
import { INGREDIENT_SLUGS } from "../../ingredients/ingredient-slugs";
import type { UnifiedProductSeed } from "../unified-types";

export const AVENE_SEED: UnifiedProductSeed[] = [
  {
    slug: "avene-hydrance-boost-serum-hydratant",
    name: 'Hydrance BOOST Sérum',
    brand: 'Avène',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 2340,
    description: 'Véritable booster intense d’hydratation du visage qui rétablit l’équilibre des peaux sensibles déshydratées pendant 48H.',
    notes: '96% d’ingrédients d’origine naturelle. Enrichi en Acide Hyaluronique et Vitamine B3 (Niacinamide). Texture gel d’eau ultra-légère et fraîche.',
    inci: 'WATER, PROPANEDIOL, GLYCERIN, PENTYLENE GLYCOL, DIGLYCERIN, 1,2-HEXANEDIOL, NIACINAMIDE, SODIUM HYALURONATE, BETAINE, CITRIC ACID, FRAGRANCE (PARFUM), PCA, POLYGLYCERYL-4 CAPRATE, SCLEROTIUM GUM, SODIUM CITRATE, SODIUM HYDROXIDE, WATER',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.REPULPANT,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.HYDRATATION,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: 'Vitamine B3 hydratante et apaisante',},
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, notes: 'Acide hyaluronique hydratant',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Humectant',},
    ],
  },
  {
    slug: "avene-tolerance-control-baume-relipidant",
    name: 'Tolérance CONTROL Baume apaisant restaurateur',
    brand: 'Avène',
    kind: 'balm',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1765,
    description: 'Baume ultra-calmant riche pour peaux hypersensibles, réactives, intolérantes ou allergiques. Calme la peau en 30 secondes.',
    notes: 'Texture riche pour peaux sèches. Actif postbiotique D-Sensinose™. Sans parfum ni conservateur. Packaging Cosmétique Stérile®.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, CETEARYL ALCOHOL, BUTYROSPERMUM PARKII (SHEA) BUTTER, SQUALANE, BEESWAX (CERA ALBA), CETEARYL GLUCOSIDE, CETYL ESTERS, AQUAPHILUS DOLOMIAE EXTRACT FILTRATE, ARGININE, CITRIC ACID, TROMETHAMINE, WATER, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.PEAU_SECHE],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER, notes: 'Beurre de karité nourrissant',},
      { slug: INGREDIENT_SLUGS.SQUALANE, notes: 'Lipide occlusif apaisant',},
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'D-Sensinose™ — postbiotique ultra-calmant breveté',},
    ],
  },
  {
    slug: "avene-hyaluron-activ-b3-serum-concentre",
    name: 'Hyaluron Activ B3 Sérum Concentré Repulpant',
    brand: 'Avène',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 2589,
    description: 'Sérum hautement concentré en acide hyaluronique pur (1,5%) et niacinamide (6%) pour agir sur la cause du vieillissement et raffermir la peau.',
    notes: 'Formule minimaliste avec seulement 8 ingrédients. 94% d’origine naturelle. Effet tenseur immédiat.',
    inci: 'WATER, NIACINAMIDE, GLYCERIN, PENTYLENE GLYCOL, SODIUM HYALURONATE, ADENOSINE, CITRIC ACID, SODIUM BENZOATE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.REPULPANT,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.HYDRATATION,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, concentrationValue: 6, concentrationUnit: "%", notes: 'Vitamine B3 anti-âge et repulpante',},
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, concentrationValue: 1.5, concentrationUnit: "%", notes: 'Acide hyaluronique pur repulpant',},
      { slug: INGREDIENT_SLUGS.ADENOSINE, notes: 'Actif anti-rides et tenseur',},
    ],
  },
  {
    slug: "avene-cleanance-comedomed-soin-anti-imperfection",
    name: 'Cleanance Comedomed+ Soin Intensif Anti-Imperfections',
    brand: 'Avène',
    kind: 'spot-treatment',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 1450,
    description: 'Soin intensif nouvelle génération ciblant les boutons, points noirs et marques dès la racine avec une action anti-récidive 1 an.',
    notes: 'Efficacité visible dès 5h. Texture gel-crème légère, fini non gras.',
    inci: 'WATER, ISOPROPYL ALCOHOL, PEG-6, GLYCERIN, NIACINAMIDE, SILYBUM MARIANUM FRUIT EXTRACT, SILICA, POLYACRYLATE-13, POLYISOBUTENE, POLYSORBATE 20, SORBITAN ISOSTEARATE, WATER',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE],
      secondary: [
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.SPOT_TREATMENT,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, concentrationValue: 4, concentrationUnit: "%", notes: 'Limite les marques et régule le sébum',},
      { slug: INGREDIENT_SLUGS.CHARDON_MARIE, notes: 'Comedoclastin™ — réduit comédons et pores',},
    ],
  },
  {
    slug: "avene-cleanance-comedomed-serum-intensif",
    name: 'Cleanance Comedomed Sérum Intensif',
    brand: 'Avène',
    kind: 'serum',
    unit: "bottle",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 2999,
    description: `Sérum intensif anti-imperfections et anti-marques cicatricielles pour peaux à tendance acnéique. Formulé avec 30% d'actifs dermatologiques.`,
    notes: `Idéal pour adultes et adolescents. Odeur d'alcool due à l'extraction de la Comedoclastin™.`,
    inci: 'WATER, ISOPROPYL ALCOHOL, PEG-6, GLYCERIN, GLYCOLIC ACID, SILYBUM MARIANUM FRUIT EXTRACT, ASCORBYL GLUCOSIDE, ACACIA SENEGAL GUM, BAKUCHIOL, BETA-CARYOPHYLLENE, CITRIC ACID, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, POLYSORBATE 60, SODIUM CITRATE, SODIUM HYDROXIDE, SORBITAN ISOSTEARATE, TOCOPHEROL, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CHARDON_MARIE, concentrationValue: 25, concentrationUnit: "%", notes: 'Comedoclastin™ : actif breveté issu du Chardon-marie',},
      { slug: INGREDIENT_SLUGS.GLYCOLIC_ACID, notes: 'Exfoliant AHA pour lisser le grain de peau',},
      { slug: INGREDIENT_SLUGS.BAKUCHIOL, notes: 'Alternative végétale au rétinol',},
    ],
  },
  {
    slug: "avene-ultra-fluid-invisible-spf50-plus",
    name: 'Ultra Fluid Invisible SPF50',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "bottle",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1389,
    description: 'Haute protection solaire quotidienne à la texture ultra fluide, aussi légère que de l’eau. Fini 100% invisible et non collant.',
    notes: 'Technologie [waterlike]. Protège contre les UVA, UVB et la lumière bleue (TriasorB).',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER, DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, GLYCERYL LAURATE, GLYCINE SOJA (SOYBEAN) OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENZOATE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.DIETHYLAMINO_HYDROXYBENZOYL_HEXYL_BENZOATE, notes: 'Filtre UVA liposoluble haute protection',},
      { slug: INGREDIENT_SLUGS.ETHYLHEXYL_TRIAZONE, notes: 'Filtre UVB haute protection',},
    ],
  },
  {
    slug: "avene-xeracalm-nutrition-baume-hydratant",
    name: 'XeraCalm Nutrition Baume Hydratant',
    brand: 'Avène',
    kind: 'balm',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 1990,
    description: 'Soin quotidien haute tolérance pour peaux sèches à très sèches de toute la famille. Nourrit, hydrate et renforce la barrière cutanée.',
    notes: '95% d’ingrédients d’origine naturelle. Formule enrichie en huile de Chardon-Marie et Niacinamide.',
    inci: 'WATER, GLYCERIN, CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL, PENTAERYTHRITYL TETRACAPRYLATE/TETRACAPRATE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, ISOPROPYL PALMITATE, NIACINAMIDE, BEHENYL ALCOHOL, BENZOIC ACID, CAPRYYL GLYCOL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYDROXYETHYLCELLULOSE, LAURYL GLUCOSIDE, SILYBUM MARIANUM SEED OIL, SODIUM CITRATE, SODIUM LAURYL GLUCOSE CARBOXYLATE, SODIUM STEAROYL GLUTAMATE, SORBIC ACID, TOCOPHEROL, WATER, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.HUILE_ONAGRE, notes: `Huile d'onagre relipidante riche en GLA`,},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Humectant hydratant',},
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'I-modulia® — réduit les démangeaisons',},
    ],
  },
  {
    slug: "avene-hyaluron-activ-procedure-creme-micro-lift-yeux-levres",
    name: 'Hyaluron Activ Procedure Crème Micro-Lift Yeux & Lèvres',
    brand: 'Avène',
    kind: 'eye-cream',
    unit: "tube",
    totalAmount: 15,
    amountUnit: "ml",
    priceCents: 3099,
    description: 'Soin anti-âge spécifique pour le contour des yeux et des lèvres qui cible et réduit les rides et les ridules.',
    notes: 'Contient 0.05% de Rétinal. Action micro-lift ciblée.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, SQUALANE, BUTYROSPERMUM PARKII (SHEA) BUTTER, CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL, PENTAERYTHRITYL TETRACAPRYLATE/TETRACAPRATE, CETEARYL ALCOHOL, BEHENYL ALCOHOL, NIACINAMIDE, C20-22 ALKYL PHOSPHATE, C20-22 ALCOHOLS, ACACIA SENEGAL GUM, CETEARYL GLUCOSIDE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, RETINAL, SODIUM BENZOATE, SODIUM HYALURONATE, SODIUM HYDROXIDE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.CONTOUR_YEUX, TAG_SLUGS.SOIN_LEVRES, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.ZONE_LEVRES],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, notes: 'Acide hyaluronique repulpant',},
      { slug: INGREDIENT_SLUGS.RETINOL, notes: 'Rétinol lissant — contour yeux et lèvres',},
    ],
  },
  {
    slug: "avene-eau-thermale",
    name: 'Spray d’Eau Thermale Avène',
    brand: 'Avène',
    kind: 'mist',
    unit: "aerosol",
    totalAmount: 300,
    amountUnit: "ml",
    priceCents: 769,
    description: 'Spray apaisant, fortifiant et rééquilibrant pour un confort immédiat.',
    notes: 'Convient à toute la famille (dès 0 mois). Diminue la sensibilité cutanée de 64% dès la première semaine.',
    inci: 'WATER, NITROGEN',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ANTI_ROUGEURS],
      secondary: [
        TAG_SLUGS.BRUME,
        TAG_SLUGS.PREPARATION,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [],
    },
    keyIngredients: [],
  },
  {
    slug: "avene-hyaluron-activ-procedure-creme-lifting-0-1-retinal",
    name: 'Hyaluron Activ Procedure Crème Lifting 0.1% Rétinal',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 4317,
    description: `Crème anti-rides et liftante haute performance. Améliore l'éclat de la peau et réduit les rides grâce à une concentration de 0.1% en rétinal.`,
    notes: 'Très appréciée pour sa tolérance sur peaux sensibles malgré la puissance du rétinal.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, SQUALANE, BUTYROSPERMUM PARKII (SHEA) BUTTER, CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL, PENTAERYTHRITYL TETRACAPRYLATE/TETRACAPRATE, CETEARYL ALCOHOL, BEHENYL ALCOHOL, NIACINAMIDE, C20-22 ALKYL PHOSPHATE, C20-22 ALCOHOLS, ACACIA SENEGAL GUM, ADENOSINE, CETEARYL GLUCOSIDE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, RETINAL, SODIUM BENZOATE, SODIUM HYALURONATE, SODIUM HYDROXIDE, TERMINALIA CHEBULA FRUIT EXTRACT, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.atida.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.REPULPANT,
        TAG_SLUGS.DESHYDRATATION,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINAL, concentrationValue: 0.1, concentrationUnit: "%", notes: `Précurseur direct de l'acide rétinoïque`,},
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, concentrationValue: 2, concentrationUnit: "%", notes: 'Stimule la régénération cellulaire',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: 'Action lissante et hydratante',},
    ],
  },
  {
    slug: "avene-hyaluron-activ-procedure-serum-tenseur",
    name: 'Hyaluron Activ Procedure Sérum Tenseur',
    brand: 'Avène',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 4499,
    description: `Sérum concentré à effet tenseur immédiat formulé avec une solution de 10% d'Hexapeptide.`,
    notes: 'Innovation de la gamme Procedure pour un effet lifting renforcé.',
    inci: 'WATER, GLYCERIN, PENTYLENE GLYCOL, ACETYL HEXAPEPTIDE-8, SODIUM HYALURONATE, CITRIC ACID, SODIUM CITRATE',
    url: 'https://www.atida.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.REPULPANT,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.HYDRATATION,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [{ slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, notes: 'Acide hyaluronique repulpant et tenseur',}],
  },
  {
    slug: "avene-xeracalm-ad-creme-relipidante",
    name: 'XeraCalm A.D Crème Relipidante',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 2099,
    description: 'Crème relipidante pour peaux sèches sujettes aux démangeaisons et irritations dues au dessèchement cutané.',
    notes: 'Diminue les démangeaisons. Nourrit en profondeur. Renforce le film hydrolipidique.',
    inci: 'WATER, GLYCERIN, MINERAL OIL (PARAFFINUM LIQUIDUM), CETEARYL ALCOHOL, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CETEARYL GLUCOSIDE, AQUAPHILUS DOLOMIAE EXTRACT, ARGININE, CARBOMER, EVENING PRIMROSE OIL/PALM OIL AMINOPROPANEDIOL ESTERS, GLYCINE, SODIUM HYDROXIDE, TOCOPHEROL',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ECZEMA],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'I-modulia® : actif biotechnologique anti-démangeaisons',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: 'CER-OMEGA : lipides semblables à ceux de la peau',},
    ],
  },
  {
    slug: "avene-cleanance-gel-nettoyant",
    name: 'Cleanance Gel Nettoyant',
    brand: 'Avène',
    kind: 'cleanser',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 991,
    description: `Gel nettoyant pour peaux grasses à imperfections, purifie et matifie la peau sans l'irriter.`,
    notes: `Pour visage et corps. Réduit l'excès de sébum. Lutte contre boutons et points noirs.`,
    inci: 'WATER, ZINC COCETH SULFATE, LAURYL BETAINE, DECYL GLUCOSIDE, CETEARETH-60 MYRISTYL GLYCOL, PEG-7 GLYCERYL COCOATE, POLYSORBATE 20, CITRIC ACID, FRAGRANCE (PARFUM), GREEN 5 (CI 61570), ISOPROPYL ALCOHOL, PEG-40 HYDROGENATED CASTOR OIL, PEG-6, PPG-26-BUTETH-26, SILYBUM MARIANUM FRUIT EXTRACT, SODIUM BENZOATE, SODIUM CHLORIDE, SODIUM HYDROXIDE, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, YELLOW 5 (CI 19140), ZINC GLUCONATE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
      secondary: [
        TAG_SLUGS.GEL_NETTOYANT,
        TAG_SLUGS.DOUBLE_NETTOYAGE_2,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.BRILLANCE,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.SANS_SAVON,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ZINC_GLUCONATE, notes: 'Action matifiante et anti-irritante',},
      { slug: INGREDIENT_SLUGS.CHARDON_MARIE, notes: 'Comedoclastin™ : aide à réduire les imperfections',},
    ],
  },
  {
    slug: "avene-hydrance-riche-creme-hydratante",
    name: 'Hydrance Riche Crème Hydratante',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1448,
    description: 'Crème hydratante riche pour peaux sensibles sèches à très sèches, offrant hydratation et apaisement.',
    notes: 'Texture onctueuse. Rend la peau souple et lumineuse.',
    inci: 'WATER, MINERAL OIL (PARAFFINUM LIQUIDUM), GLYCERIN, ISOHEXADECANE, DIMETHICONE, CETEARYL ALCOHOL, CARTHAMUS TINCTORIUS SEED OIL, ISOCETYL STEAROYL STEARATE, TRIETHYLHEXANOIN, GLYCERYL STEARATE, PEG-100 STEARATE, 1-2 HEXANEDIOL, BUTYROSPERMUM PARKII (SHEA) BUTTER, CETEARYL GLUCOSIDE, BENZOIC ACID, BETA SITOSTEROL, BHT, DISODIUM EDTA, FRAGRANCE (PARFUM), POLYACRYLATE-13, POLYISOBUTENE, POLYSORBATE 20, SODIUM HYDROXIDE, SORBITAN ISOSTEARATE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.DESHYDRATATION],
      secondary: [
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER, notes: 'Nourrit intensément',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Hydratation des couches supérieures de la peau',},
    ],
  },
  {
    slug: "avene-hydrance-light-creme-hydratante",
    name: 'Hydrance Light Crème Hydratante',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1449,
    description: 'Crème hydratante légère pour peaux sensibles normales à mixtes, offrant hydratation durable.',
    notes: 'Texture légère non collante.',
    inci: 'WATER, GLYCERIN, PROPYLENE GLYCOL DICAPRYLATE/DICAPRATE, C14-22 ALCOHOLS, DIMETHICONE, ISOCETYL STEAROYL STEARATE, TRIETHYLHEXANOIN, 1,2-HEXANEDIOL, MICROCRYSTALLINE CELLULOSE, POTASSIUM CETYL PHOSPHATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BENZOIC ACID, C12-20 ALKYL GLUCOSIDE, FRAGRANCE (PARFUM), HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, PHYTOSTEROLS, POLYSORBATE 60, SCLEROTIUM GUM, SODIUM HYDROXIDE, SORBITAN ISOSTEARATE, SQUALANE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.DESHYDRATATION],
      secondary: [
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.GEL_CREME,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SQUALANE, notes: 'Restaure la souplesse de la peau',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Hydratation durable',},
    ],
  },
  {
    slug: "avene-cicalfate-creme-reparatrice",
    name: 'Cicalfate + Crème Réparatrice Protectrice',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 100,
    amountUnit: "ml",
    priceCents: 1199,
    description: 'Crème réparatrice pour peaux irritées et abîmées, accélère la cicatrisation et protège contre les bactéries.',
    notes: 'Non comédogène. Convient à nourrissons, enfants, adultes. Texture onctueuse.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, MINERAL OIL (PARAFFINUM LIQUIDUM), GLYCERIN, HYDROGENATED VEGETABLE OIL, ZINC OXIDE, PROPYLENE GLYCOL, POLYGLYCERYL-2 SESQUIISOSTEARATE, PEG-22/DODECYL GLYCOL COPOLYMER, ALUMINIUM STEARATE, AQUAPHILUS DOLOMIAE FERMENT FILTRATE, ARGININE, BEESWAX (CERA ALBA), COPPER SULFATE, MAGNESIUM STEARATE, MAGNESIUM SULFATE, MICROCRYSTALLINE WAX (CERA MICROCRISTALLINA), TROMETHAMINE, ZINC SULFATE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_ATOPIQUE],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.ANTI_ROUGEURS,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.SOIN_LOCALISE,
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_FERMENT_FILTRATE, notes: '[C+ Restore]™ : actif postbiotique breveté',},
      { slug: INGREDIENT_SLUGS.ZINC_SULFATE, notes: 'Complexe purifiant Cuivre-Zinc',},
      { slug: INGREDIENT_SLUGS.COPPER_SULFATE, notes: 'Complexe purifiant Cuivre-Zinc',},
    ],
  },
  {
    slug: "avene-hyaluron-activ-b3-creme-regeneration",
    name: 'Hyaluron Activ B3 Crème Régénération Cellulaire',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 3226,
    description: 'Crème régénérante pour peaux vieillissantes, repulpe, lisse et corrige les rides.',
    notes: '0.2% acide hyaluronique. 6% niacinamide. 92% ingrédients naturels.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, NIACINAMIDE, CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL, BUTYROSPERMUM PARKII (SHEA) BUTTER, GLYCOL PALMITATE, ARACHIDYL ALCOHOL, CETEARYL ALCOHOL, CELLULOSE, GLYCERYL STEARATE, SODIUM HYALURONATE, ADENOSINE, ARACHIDYL GLUCOSIDE, BEHENYL ALCOHOL, CAPRYLYL GLYCOL, CETEARYL GLUCOSIDE, CITRIC ACID, DIMETHYL PHENETHYL ACETATE, FRAGRANCE (PARFUM), GERANYL ACETATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, SODIUM BENZOATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, TRIMETHYLCYCLOPENTENYL METHYLISOPENTENOL, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.REPULPANT,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, concentrationValue: 6, concentrationUnit: "%", notes: 'Stimule la régénération cellulaire',},
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, concentrationValue: 0.2, concentrationUnit: "%", notes: 'Acide hyaluronique pur et naturel',},
      { slug: INGREDIENT_SLUGS.ADENOSINE, notes: 'Actif anti-rides',},
    ],
  },
  {
    slug: "avene-xeracalm-huile-lavante",
    name: 'Xeracalm Ad Huile Lavante Relipidante',
    brand: 'Avène',
    kind: 'cleanser',
    unit: "pump",
    totalAmount: 750,
    amountUnit: "ml",
    priceCents: 1800,
    description: `Huile lavante relipidante pour peaux très sèches sujettes à l'eczéma atopique et démangeaisons.`,
    notes: 'Sans savon, sans parfum. pH physiologique. Respecte le microbiome.',
    inci: 'WATER, GLYCERIN, HYDROGENATED STARCH HYDROLYSATE, DISODIUM COCOAMPHODIACETATE, DECYL GLUCOSIDE, POLYSORBATE 20, SODIUM CHLORIDE, CETEARETH-60 MYRISTYL GLYCOL, AQUAPHILUS DOLOMIAE EXTRACT, ARGININE, CITRIC ACID, COCO-GLUCOSIDE, EVENING PRIMROSE OIL/PALM OIL AMINOPROPANEDIOL ESTERS, GLYCERYL OLEATE, GLYCINE, HYDROGENATED VEGETABLE GLYCERIDES CITRATE, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, SODIUM BENZOATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ECZEMA],
      secondary: [
        TAG_SLUGS.HUILE_NETTOYANTE,
        TAG_SLUGS.DOUBLE_NETTOYAGE_1,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.SANS_SAVON,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'I-modulia® : réduit les sensations de démangeaisons',},
      { slug: INGREDIENT_SLUGS.HUILE_ONAGRE, notes: 'CER-OMEGA : relipide la peau',},
    ],
  },
  {
    slug: "avene-vitamin-activ-c-serum-eclat",
    name: 'Vitamin Activ C Sérum Concentré Éclat',
    brand: 'Avène',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3321,
    description: 'Sérum concentré pour illuminer le teint, réduire les tâches brunes et lisser les rides.',
    notes: 'Texture pénétrante non grasse. Convient à tous types de peaux.',
    inci: 'PENTYLENE GLYCOL, CITRIC ACID, ASCORBYL GLUCOSIDE, SODIUM CITRATE, GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, TRIBEHENIN, SODIUM HYALURONATE, PENTAERYTHRITYL TETRACAPRYLATE/TETRACAPRATE, WATER, GLYCERIN, 1,2-HEXANEDIOL, NIACINAMIDE, CAPRYLIC/CAPRIC TRIGLYCERIDE, BUTYLENE GLYCOL, SODIUM DILAURAMIDOGLUTAMIDE, SODIUM HYDROXIDE, ACACIA SENEGAL GUM, XANTHAN GUM, BAKUCHIOL, TOCOPHERYL GLUCOSIDE, C9-12 ALKANE, COCO-CAPRYLATE/CAPRATE, PARFUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.ANTI_AGE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, notes: 'Vitamine Cg : forme stable de vitamine C',},
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: 'Réduit les taches et lisse les rides',},
      { slug: INGREDIENT_SLUGS.BAKUCHIOL, notes: 'Alternative végétale au rétinol',},
    ],
  },
  {
    slug: "avene-solaire-cleanance-solaire-spf50-plus",
    name: 'Cleanance Solaire SPF50+',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1299,
    description: 'Protection solaire SPF50+ matifiante pour peaux grasses/acnéiques. Contrôle sébum.',
    notes: 'Filtres chimiques + minéraux. Eau thermale apaisante, texture fluide non grasse.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL [NANO], CETEARYL ISONONANOATE, WATER, DIISOPROPYL ADIPATE, ISODECYL NEOPENTANOATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DIETHYLHEXYL BUTAMIDO TRIAZONE, POLYMETHYL METHACRYLATE, BUTYL METHOXYDIBENZOYLMETHANE, POTASSIUM CETYL PHOSPHATE, DECYL GLUCOSIDE, GLYCERYL LAURATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, DISODIUM EDTA, FRAGRANCE (PARFUM), GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, HYDROGENATED PALM GLYCERIDES, HYDROGENATED PALM KERNEL GLYCERIDES, PROPYLENE GLYCOL, SILICA, SODIUM HYDROXIDE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM, ZINC GLUCONATE',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.BRILLANCE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ZINC_GLUCONATE, notes: 'Action sébo-régulatrice',},
      { slug: INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE, notes: 'Pré-tocophéryl : antioxydant',},
    ],
  },
  {
    slug: "avene-fluide-anti-imperfection-spf50",
    name: 'Fluide Anti-Imperfection SPF50',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "tube",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 2400,
    description: 'Fluide solaire SPF50+ léger pour peaux sensibles et à imperfections. Protège contre UVB/UVA et lumière bleue.',
    notes: 'Texture fluide non grasse, matifiante. Sans parfum.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER, DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, GLYCERYL LAURATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENZOATE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM, ZINC GLUCONATE',
    url: 'https://www.avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.LUMIERE_BLEUE,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRIASORB, notes: 'Filtre solaire breveté contre les UV et la lumière bleue haute énergie',},
      { slug: INGREDIENT_SLUGS.ZINC_GLUCONATE, notes: 'Régule le sébum et limite les imperfections',},
    ],
  },
  {
    slug: "avene-solaire-sunsimed-ka-spf50-plus",
    name: 'SunsiMed KA SPF50+',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 80,
    amountUnit: "ml",
    priceCents: 1799,
    description: 'Protection SPF50+ très haute pour peaux à kératoses actiniques. Prévention photo-vieillissement et cancers cutanés.',
    notes: 'Texture crème non grasse, tolérance optimale peaux fragiles/sensibles.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL [NANO], WATER, CETEARYL ISONONANOATE, DIISOPROPYL ADIPATE, ISODECYL NEOPENTANOATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DIETHYLHEXYL BUTAMIDO TRIAZONE, ALUMINUM STARCH OCTENYLSUCCINATE, BUTYL METHOXYDIBENZOYLMETHANE, POTASSIUM CETYL PHOSPHATE, DECYL GLUCOSIDE, C10-18 TRIGLYCERIDES, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, DISODIUM EDTA, GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, GLYCERYL LAURATE, PROPYLENE GLYCOL, SILICA (NANO), SODIUM HYDROXIDE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.CREME_SOLAIRE, TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
      secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.MATIN, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.ZONE_VISAGE],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [{ slug: INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE, notes: 'Pré-tocophéryl : puissant antioxydant',}],
  },
  {
    slug: "avene-solaires-creme-teinte-anti-lumiere-bleue-spf50-plus",
    name: 'Crème Teintée Anti-Lumière Bleue SPF50+',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1299,
    description: 'Crème teintée SPF50+ anti-lumière bleue/UV. Protection large spectre + anti-pollution, unifie teint.',
    notes: 'Peaux sensibles.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, ETHYLHEXYL TRIAZONE, GLYCERIN, PHENYLENE BIS-DIPHENYLTRIAZINE, WATER, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, TITANIUM DIOXIDE, POTASSIUM CETYL PHOSPHATE, MYRISTYL ALCOHOL, ORYZA SATIVA (RICE) STARCH, STEARYL ALCOHOL, ISONONYL ISONONANOATE, VP/EICOSENE COPOLYMER, ALUMINA, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, FRAGRANCE (PARFUM), GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, IRON OXIDES, ISOPROPYL MYRISTATE, ISOPROPYL TITANIUM TRIISOSTEARATE, MYRISTYL GLUCOSIDE, POLYHYDROXYSTEARIC ACID, PPG-1-PEG-9 LAURYL GLYCOL ETHER, PROPYLENE CARBONATE, STEARALKONIUM HECTORITE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_NORMALE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE_TEINTEE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.LUMIERE_BLEUE,
        TAG_SLUGS.POLLUTION,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.FILTRES_MINERAUX,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRIASORB, notes: 'Protection ultra-large spectre contre la lumière bleue',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Hydratation 24h',},
    ],
  },
  {
    slug: "avene-ultra-fluid-oil-control-spf50",
    name: 'Ultra Fluid Oil Control SPF50',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1369,
    description: 'Fluide matifiant SPF50 contrôle brillance/peaux grasses. Absorption rapide, fini sec.',
    notes: 'Filtres chimiques + amidon riz/tapioca + lentille exfoliante douce.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER, DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, TAPIOCA STARCH, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, ETHYLHEXYLGLYCERIN, GLYCERYL LAURATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENOAZE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.BRILLANCE,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRIASORB, notes: 'Protection lumière bleue et UV',},
      { slug: INGREDIENT_SLUGS.LENS_ESCULENTA_SEED_EXTRACT, notes: 'Extrait de lentille pour réduire les pores et matifier',},
    ],
  },
  {
    slug: "avene-ultra-fluid-eclat-radiance-spf50-plus",
    name: 'Ultra Fluid Éclat Radiance SPF50+',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1399,
    description: 'Fluide SPF50+ éclat radiance pour peaux normales/mixtes. Illumine, matifie, protection large spectre.',
    notes: 'Filtres chimiques + amidon riz + lentille + huiles végétales.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER, DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, GLYCERYL LAURATE, GLYCINE SOJA (SOYBEAN) OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENZOATE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [TAG_SLUGS.CREME_SOLAIRE, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.MATIN, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.ZONE_VISAGE],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRIASORB, notes: 'Protection solaire invisible et large spectre',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: `Antioxydant pour l'éclat du teint`,},
    ],
  },
  {
    slug: "avene-ultra-fluid-perfecteur-spf50-plus",
    name: 'Ultra Fluid Perfecteur SPF50+',
    brand: 'Avène',
    kind: 'sunscreen',
    unit: "pump",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1549,
    description: 'Fluide perfecteur SPF50+ teint parfait. Uniformise, matifie, protège des UV/lumière bleue.',
    notes: 'Texture fluide teintée légère, fini velours.',
    inci: 'WATER, C12-15 ALKYL BENZOATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, ALUMINA, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, ETHYLHEXYLGLYCERIN, GLYCERYL LAURATE, IRON OXIDES, ISONONYL ISONONANOATE, ISOPROPYL MYRISTATE, ISOPROPYL TITANIUM TRIISOSTEARATE, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, POLYHYDROXYSTEARIC ACID, PPG-1-PEG-9 LAURYL GLYCOL ETHER, PROPYLENE CARBONATE, SODIUM BENZOATE, SODIUM PHYTATE, STEARALKONIUM HECTORITE, TITANIUM DIOXIDE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE_TEINTEE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.LUMIERE_BLEUE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.FILTRES_MINERAUX,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRIASORB, notes: 'Protection contre le photovieillissement',},
      { slug: INGREDIENT_SLUGS.IRON_OXIDE, notes: 'Pigments pour unifier le teint',},
    ],
  },
  {
    slug: "avene-tolerance-control-creme",
    name: 'Tolérance Control Crème',
    brand: 'Avène',
    kind: 'moisturizer',
    unit: "pump",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1400,
    description: 'Crème apaisante restauratrice haute tolérance pour peaux hypersensibles, intolérantes ou allergiques.',
    notes: 'Texture crème légère. D-Sensinose™ postbiotique ultra-calmante.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, ETHYLHEXYL PALMITATE, GLYCERIN, CETEARYL ALCOHOL, SQUALANE, CETEARYL GLUCOSIDE, CETYL ESTERS, AQUAPHILUS DOLOMIAE EXTRACT FILTRATE, ARGININE, BEESWAX (CERA ALBA), CITRIC ACID, TROMETHAMINE, WATER, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'D-Sensinose™ : actif postbiotique ultra-calmant breveté',},
      { slug: INGREDIENT_SLUGS.SQUALANE, notes: 'Restaure la barrière cutanée',},
    ],
  },
  {
    slug: "avene-xeracalm-ad-baume-relipidant",
    name: 'Xeracalm A.D Baume Relipidant',
    brand: 'Avène',
    kind: 'balm',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 1800,
    description: 'Baume relipidant très riche pour peaux très sèches à tendance atopique, dès la naissance.',
    notes: 'Texture baume très riche. I-modulia® + Cer-Omega apaisent démangeaisons et relipident durablement.',
    inci: 'WATER, MINERAL OIL (PARAFFINUM LIQUIDUM), GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, PEG-12, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, GLYCERYL STEARATE, MYRETH-3 MYRISTATE, PEG-100 STEARATE, POLYACRYLATE-13, AQUAPHILUS DOLOMIAE EXTRACT, ARGININE, CITRIC ACID, EVENING PRIMROSE OIL/PALM OIL AMINOPROPANEDIOL ESTERS, GLYCINE, POLYISOBUTENE, POLYSORBATE 20, SORBITAN ISOSTEARATE, TOCOPHEROL, WATER',
    url: 'https://www.eau-thermale-avene.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ECZEMA],
      secondary: [
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT, notes: 'I-modulia® : réduit les sensations de démangeaisons',},
      { slug: INGREDIENT_SLUGS.HUILE_ONAGRE, notes: 'Cer-Omega : nourrit et renforce le film protecteur',},
    ],
  },
  {
    slug: "avene-antirougeurs-rosamed",
    name: 'Antirougeurs Rosamed',
    brand: 'Avène',
    kind: 'serum',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 1850,
    description: `Concentré spécifique pour les rougeurs installées. Co-développé avec des dermatologues pour réduire l\"hypervascularisation à la source.`,
    notes: `Contient de l\"Angiopausine™ 6% (extrait de chardon-marie). Action anti-récidive. 98% d\'origine naturelle. Sans parfum.`,
    inci: 'WATER, OCTYLDODECANOL, GLYCERIN, MYRISTYL ALCOHOL, PENTYLENE GLYCOL, SILYBUM MARIANUM FRUIT EXTRACT, POTASSIUM CETYL PHOSPHATE, MYRISTYL GLUCOSIDE, CITRIC ACID, DIUTAN GUM, GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, SODIUM BENZOATE, TOCOPHEROL, TRIBEHENIN, XANTHAN GUM',
    tags: {
      primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE, TAG_SLUGS.FLUSHS, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.SERUM, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.ZONE_VISAGE],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ANGIOPAUSINE, concentrationValue: 6, concentrationUnit: "%", notes: `Réduit l'hypervascularisation à la source`,},
      { slug: INGREDIENT_SLUGS.AVENE_THERMAL_SPRING_WATER, notes: 'Apaisante et anti-irritante',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: 'Vitamine E antioxydante',},
    ],
  },
];
