import { TAG_SLUGS } from '../../tags/seed-tags'
import { MEME_PRODUCT_SLUGS } from './memeCancer'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const MEME_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [MEME_PRODUCT_SLUGS.MEME_CREME_VISAGE]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BRILLANCE],
  },

  
  [MEME_PRODUCT_SLUGS.MEME_GELEE_DEMAQUILLANTE]: {
    primary: [
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.BAUME_DEMAQUILLANT,
    ],
    avoid: [],
  },

  
  [MEME_PRODUCT_SLUGS.MEME_HUILE_LAVANTE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.HUILE_NETTOYANTE,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [MEME_PRODUCT_SLUGS.MEME_BAUME_MULTI_USAGES]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BAUME,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },
}
