import { TAG_SLUGS } from "../../tags/seed-tags";
import { INGREDIENT_SLUGS } from "../../ingredients/ingredient-slugs";
import type { UnifiedProductSeed } from "../unified-types";

export const LA_ROCHE_POSAY_SEED: UnifiedProductSeed[] = [
  {
    slug: "la-roche-posay-lipikar-huile-lavante-ap-plus",
    name: 'Lipikar Huile Lavante AP+',
    brand: 'La Roche-Posay',
    kind: 'cleanser',
    unit: "pump",
    totalAmount: 750,
    amountUnit: "ml",
    priceCents: 2350,
    description: 'Huile lavante relipidante anti-irritation et anti-grattage enrichie en Beurre de Karité.',
    notes: 'Note: 4.6/5. Convient dès la naissance. Équilibre le microbiome cutané.',
    inci: 'AQUA / WATER / EAU, GLYCERIN, SUCROSE, SODIUM LAURETH SULFATE, COCO-BETAINE, SODIUM CHLORIDE, CITRIC ACID, SODIUM HYDROXIDE, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, VITREOSCILLA FERMENT, NIACINAMIDE, PEG-75 SHEA BUTTER GLYCERIDES, PENTYLENE GLYCOL, POLYSORBATE 20, SODIUM BENZOATE, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.HUILE_NETTOYANTE,
        TAG_SLUGS.DOUBLE_NETTOYAGE_1,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.SANS_SAVON,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ECZEMA,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Apaise les démangeaisons',},
      {
        slug: INGREDIENT_SLUGS.SHEA_BUTTER,
        notes: 'Beurre de karité relipidant',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Aqua Posae Filiformis — équilibre microbiome cutané',},
    ],
  },
  {
    slug: "la-roche-posay-anthelios-xl-brume-spf50",
    name: 'Anthelios XL Brume Solaire Invisible Corps SPF50+',
    brand: 'La Roche-Posay',
    kind: 'sunscreen',
    unit: "spray",
    totalAmount: 200,
    amountUnit: "ml",
    priceCents: 1899,
    description: 'Brume solaire corps SPF50+ très haute protection UVA/UVB.',
    notes: `Mexoryl XL. Très résistante à l'eau. Fini invisible.`,
    inci: 'BUTANE, WATER, HOMOSALATE, DICAPRYLYL ETHER, OCTOCRYLENE, ETHYLHEXYL SALICYLATE, DIMETHICONE, STYRENE/ACRYLATES COPOLYMER, BUTYL METHOXYDIBENZOYLMETHANE, DROMETRIZOLE TRISILOXANE, PEG-30 DIPOLYHYDROXYSTEARATE, NYLON-12, DICAPRYLYL CARBONATE, METHYL METHACRYLATE CROSSPOLYMER, CYCLOHEXASILOXANE, POLYMETHYLSILSESQUIOXANE, P-ANISIC ACID, CAPRYLYL GLYCOL, DISODIUM EDTA, DISTEARDIMONIUM HECTORITE, DODECENE, ETHYLHEXYL TRIAZONE, ISODODECANE, LAURYL PEG/PPG-18/18 METHICONE, PEG-8 LAURATE, PHENOXYETHANOL, POLOXAMER 407, POLY C10-30 ALKYL ACRYLATE, PROPYLENE CARBONATE, SODIUM CHLORIDE, TOCOPHEROL, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [
        TAG_SLUGS.PROTECTION_SOLAIRE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PEAU_SENSIBLE,
      ],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.BRUME,
        TAG_SLUGS.FILTRES_CHIMIQUES,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.PEAU_REACTIVE,
      ],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.BUTYL_METHOXYDIBENZOYLMETHANE,
        notes: 'Avobenzone – UVA',},
      {
        slug: INGREDIENT_SLUGS.DROMETRIZOLE_TRISILOXANE,
        notes: 'Mexoryl XL – UVA/UVB stable signature La Roche-Posay',},
      {
        slug: INGREDIENT_SLUGS.ETHYLHEXYL_TRIAZONE,
        notes: 'Uvinul T 150 – UVB',},
      { slug: INGREDIENT_SLUGS.OCTOCRYLENE },
      { slug: INGREDIENT_SLUGS.HOMOSALATE },
      {
        slug: INGREDIENT_SLUGS.ETHYLHEXYL_SALICYLATE,
        notes: 'Octisalate – UVB',},
      {
        slug: INGREDIENT_SLUGS.TOCOPHEROL,
        notes: 'Vitamine E – antioxydant',},
    ],
  },
  {
    slug: "la-roche-posay-hyalu-b5-serum",
    name: 'Hyalu B5 Sérum',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3149,
    description: `Sérum hydratant repulpant anti-rides à l'acide hyaluronique.`,
    notes: `4 formes d'AH. Vitamine B5. Madecassoside.`,
    inci: 'WATER, GLYCERIN, ALCOHOL DENAT., PROPYLENE GLYCOL, PANTHENOL, PENTYLENE GLYCOL, DIMETHICONE, PEG-6 CAPRYLIC/CAPRIC GLYCERIDES, ALPINIA GALANGA LEAF EXTRACT, CALCIUM CHLORIDE, GLYCERYL ISOSTEARATE, PPG-6-DECYLTETRADECETH-30, SODIUM ACETYLATED HYALURONATE, SODIUM HYALURONATE, ALGIN, ADENOSINE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, PROPANEDIOL, HYDROLYZED HYALURONIC ACID, HYDROXYACETOPHENONE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, ACETYL GLUCOSAMINE, XANTHAN GUM, BUTYLENE GLYCOL, 1,2-HEXANEDIOL, TOCOPHEROL, PHENOXYETHANOL, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT, TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.HYDRATATION,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.CICATRISATION,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
      ],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE,
        notes: 'Sodium Hyaluronate – hydratation',},
      {
        slug: INGREDIENT_SLUGS.HYALURONIC_ACID,
        notes: 'HA hydrolysé – pénétration profonde',},
      {
        slug: INGREDIENT_SLUGS.PANTHENOL,
        notes: 'Vitamine B5 – réparateur, apaisant',},
      {
        slug: INGREDIENT_SLUGS.MADECASSOSIDE,
        notes: 'Madecassoside – anti-âge, réparateur',},
    ],
  },
  {
    slug: "la-roche-posay-effaclar-duo-m",
    name: 'Effaclar Duo+M Soin Triple Correction Anti-Imperfections',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1375,
    description: 'Soin anti-imperfections pour peaux grasses à tendance acnéique.',
    notes: 'Niacinamide. Zinc PCA. Acide salicylique + LHA. Texture gel-crème.',
    inci: 'WATER, GLYCERIN, DIMETHICONE, ISOCETYL STEARATE, NIACINAMIDE, ISOPROPYL LAUROYL SARCOSINATE, SILICA, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, ORYZA SATIVA STARCH, PUNICA GRANATUM PERICARP EXTRACT, POTASSIUM CETYL PHOSPHATE, SORBITAN OLEATE, ZINC PCA, GLYCERYL STEARATE SE, ISOHEXADECANE, SODIUM HYDROXIDE, MYRISTYL MYRISTATE, 2-OLEAMIDO-1,3-OCTADECANEDIOL, MANNOSE, POLOXAMER 338, PROPANEDIOL, HYDROXYETHOXYPHENYL BUTANONE, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, MALTODEXTRIN, XANTHAN GUM, PENTYLENE GLYCOL, POLYSORBATE 80, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, SALICYLIC ACID, PIROCTONE OLAMINE, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE, TAG_SLUGS.PEAU_GRASSE],
      secondary: [
        TAG_SLUGS.GEL_CREME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.HYPERPIGMENTATION,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.BRILLANCE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.PEAU_SENSIBLE,
      ],
      avoid: [
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.ROSACEE,
        TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
      ],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Niacinamide – anti-imperfections, barrière',},
      {
        slug: INGREDIENT_SLUGS.ZINC_PCA,
        notes: 'Zinc PCA – séborégulateur',},
      {
        slug: INGREDIENT_SLUGS.CAPRYLOYL_SALICYLIC_ACID,
        notes: 'LHA – exfoliant doux',},
      {
        slug: INGREDIENT_SLUGS.SALICYLIC_ACID,
        notes: 'Acide salicylique – anti-boutons',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Phylobioma – microbiome',},
    ],
  },
  {
    slug: "la-roche-posay-cicaplast-baume-b5-spf50",
    name: 'Cicaplast Baume B5+ Réparateur Apaisant SPF50',
    brand: 'La Roche-Posay',
    kind: 'balm',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1350,
    description: 'Baume réparateur apaisant SPF50 pour peaux fragilisées.',
    notes: 'Panthénol. Madecassoside. Zinc. Protection minérale.',
    inci: 'WATER, HYDROGENATED POLYISOBUTENE, DIMETHICONE, GLYCERIN, BUTYROSPERMUM PARKII BUTTER, PANTHENOL, PROPANEDIOL, BUTYLENE GLYCOL, ALUMINUM STARCH OCTENYLSUCCINATE, CETYL PEG/PPG-10/1 DIMETHICONE, TRIHYDROXYSTEARIN, ZINC GLUCONATE, MADECASSOSIDE, MANGANESE GLUCONATE, SILICA, ALUMINUM HYDROXIDE, MAGNESIUM SULFATE, DISODIUM EDTA, COPPER GLUCONATE, CAPRYLOYL GLYCINE, CITRIC ACID, ACETYLATED GLYCOL STEARATE, POLYGLYCERYL-4 ISOSTEARATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CI 77891',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION, TAG_SLUGS.PROTECTION_SOLAIRE],
      secondary: [
        TAG_SLUGS.CREME_SOLAIRE,
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.FILTRES_MINERAUX,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ANTI_ROUGEURS,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.ANTI_TACHES,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_REACTIVE,
        TAG_SLUGS.PEAU_ATOPIQUE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.PANTHENOL,
        notes: 'Panthénol (B5) – réparateur, apaisant',},
      {
        slug: INGREDIENT_SLUGS.MADECASSOSIDE,
        notes: 'Madecassoside – cicatrisation',},
      {
        slug: INGREDIENT_SLUGS.ZINC_GLUCONATE,
        notes: 'Zinc gluconate – purifiant',},
      { slug: INGREDIENT_SLUGS.MANGANESE_GLUCONATE },
      { slug: INGREDIENT_SLUGS.COPPER_GLUCONATE },
    ],
  },
  {
    slug: "la-roche-posay-toleriane-rosaliac-ar",
    name: 'Toleriane Rosaliac AR',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "pump",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 2330,
    description: 'Soin correcteur qui rééquilibre le microbiome pour agir sur la cause profonde des rougeurs. Apaise immédiatement les échauffements.',
    notes: 'Contient du Sphingobioma et de la Neurosensine. Pigments verts correcteurs pour un effet camouflage instantané. Texture gel-crème veloutée. Sans parfum.',
    inci: 'WATER, GLYCERIN, ISOSTEARYL NEOPENTANOATE, BUTYLENE GLYCOL, BORON NITRIDE, BUTYROSPERMUM PARKII BUTTER / SHEA BUTTER, CI 77891 / TITANIUM DIOXIDE, PENTYLENE GLYCOL, HYDROGENATED COCO-GLYCERIDES, POLYSORBATE 20, ZEA MAYS STARCH / CORN STARCH, SCHISANDRA SPHENANTHERA FRUIT EXTRACT, TIN OXIDE, SORBITAN OLEATE, GLYCERYL ACRYLATE/ACRYLIC ACID COPOLYMER, GLYCERYL STEARATE CITRATE, ISOHEXADECANE, SPHINGOMONAS FERMENT EXTRACT, SILICA, ALUMINUM HYDROXIDE, MANNITOL, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, HYDROGENATED LECITHIN, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, ACETYL DIPEPTIDE-1 CETYL ESTER, MALTODEXTRIN, POLYSORBATE 80, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, MICA, CI 77288 / CHROMIUM OXIDE GREENS, CI 77491 / IRON OXIDES, CI 77492 / IRON OXIDES, CI 77499 / IRON OXIDES',
    tags: {
      primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.GEL_CREME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.PIGMENTS_VERTS,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.COUPEROSE,
        TAG_SLUGS.FLUSHS,
        TAG_SLUGS.PEAU_REACTIVE,
      ],
      avoid: [TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, notes: 'Sphingobioma : rééquilibre le microbiome',},
      { slug: INGREDIENT_SLUGS.ACETYL_DIPEPTIDE_1_CETYL_ESTER, notes: 'Neurosensine : peptide apaisant puissant',},
      { slug: INGREDIENT_SLUGS.SCHISANDRA, notes: `Réduit l'inflammation et les rougeurs`,},
      { slug: INGREDIENT_SLUGS.SHEA_BUTTER, notes: 'Hydrate et apaise',},
    ],
  },
  {
    slug: "la-roche-posay-effaclar-h-iso-biome",
    name: 'Effaclar H Iso-Biome',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "pump",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 0,
    description: 'Crème hydratante compensatrice pour peaux grasses fragilisées par les traitements asséchants anti-acné.',
    notes: 'Occlusion 6/10. Texture crème légère. Répare et réduit imperfections/marqués.',
    inci: 'WATER, GLYCERIN, SQUALANE, DIMETHICONE, PANTHENOL, ZEA MAYS STARCH/CORN STARCH, NIACINAMIDE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, MYRISTYL MYRISTATE, BIXA ORELLANA SEED EXTRACT, STEARIC ACID, POTASSIUM CETYL PHOSPHATE, GLYCERYL STEARATE SE, SODIUM HYDROXIDE, MYRISTIC ACID, 2-OLEAMIDO-1,3-OCTADECANEDIOL, PALMITIC ACID, HYDROXYACETOPHENONE, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, MALTODEXTRIN, XANTHAN GUM, PARFUM/FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.PEAU_SENSIBLE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Niacinamide – répare barrière',},
      {
        slug: INGREDIENT_SLUGS.PANTHENOL,
        notes: 'Panthénol – apaisant',},
      {
        slug: INGREDIENT_SLUGS.SQUALANE,
        notes: 'Squalane – hydratant',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Phylobioma – microbiome',},
    ],
  },
  {
    slug: "la-roche-posay-cicaplast-baume-b5-plus",
    name: 'Cicaplast Baume B5+',
    brand: 'La Roche-Posay',
    kind: 'balm',
    unit: "pump",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 0,
    description: 'Baume réparateur multi-usage apaisant pour peaux irritées, lésions, post-actes.',
    notes: 'Occlusion 8/10. Texture baume riche. Effet pansement, anti-marques.',
    inci: 'WATER, HYDROGENATED POLYISOBUTENE, DIMETHICONE, GLYCERIN, BUTYROSPERMUM PARKII BUTTER/SHEA BUTTER, PANTHENOL, ZEA MAYS STARCH/CORN STARCH, PROPANEDIOL, BUTYLENE GLYCOL, CETYL PEG/PPG-10/1 DIMETHICONE, TRIHYDROXYSTEARIN, CENTELLA ASIATICA LEAF EXTRACT, POLYMNIA SONCHIFOLIA ROOT JUICE, ZINC GLUCONATE, MADECASSOSIDE, MANGANESE GLUCONATE, ALPHA-GLUCAN OLIGOSACCHARIDE, SILICA, ALUMINUM HYDROXIDE, MAGNESIUM SULFATE, MANNOSE, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, LACTOBACILLUS, ACETYLATED GLYCOL STEARATE, MALTODEXTRIN, POLYGLYCERYL-4 ISOSTEARATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CI 77891/TITANIUM DIOXIDE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION, TAG_SLUGS.PEAU_SENSIBLE],
      secondary: [
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.ANTI_ROUGEURS,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.PEAU_REACTIVE,
        TAG_SLUGS.PEAU_ATOPIQUE,
        TAG_SLUGS.ECZEMA,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.PANTHENOL,
        notes: 'Panthénol (B5) – réparateur',},
      {
        slug: INGREDIENT_SLUGS.MADECASSOSIDE,
        notes: 'Madecassoside – cicatrisation',},
      { slug: INGREDIENT_SLUGS.ZINC_GLUCONATE },
      {
        slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA,
        notes: 'Centella – apaisant',},
      {
        slug: INGREDIENT_SLUGS.ALPHA_GLUCAN_OLIGOSACCHARIDE,
        notes: 'Prébiotique – microbiome',},
    ],
  },
  {
    slug: "la-roche-posay-hyalu-b5-cream",
    name: 'Hyalu B5 Soin Crème',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 2699,
    description: `Crème anti-rides hydratante et repulpante à l'acide hyaluronique.`,
    notes: 'Acide hyaluronique haut & bas PM. Vitamine B5. Texture riche.',
    inci: 'WATER, GLYCERIN, DIMETHICONE, HYDROGENATED POLYISOBUTENE, PROPYLENE GLYCOL, HYDROXYPROPYL TETRAHYDROPYRANTRIOL, ALCOHOL DENAT., PROPANEDIOL, PANTHENOL, SYNTHETIC WAX, NYLON-12, PEG-10 DIMETHICONE, DIMETHICONE/PEG-10/15 CROSSPOLYMER, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, TOCOPHEROL, SODIUM POLYACRYLATE, SODIUM HYALURONATE, HYDROLYD HYALURONIC ACID, SODIUM CITRATE, PHENOXYETHANOL, ADENOSINE, CHLORPHENESIN, PROPYLENE CARBONATE, DIPROPYLENE GLYCOL, DISTEARDIMONIUM HECTORITE, DISODIUM EDTA, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT, TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.PEAU_NORMALE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE,
        notes: 'HA haut PM – hydratation surface',},
      {
        slug: INGREDIENT_SLUGS.HYALURONIC_ACID,
        notes: 'HA bas PM – pénétration profonde',},
      {
        slug: INGREDIENT_SLUGS.PANTHENOL,
        notes: 'Vitamine B5 – repulpant',},
    ],
  },
  {
    slug: "la-roche-posay-effaclar-mat",
    name: 'Effaclar Mat Crème Hydratante Sébo-Régulatrice',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1149,
    description: 'Crème hydratante sébo-régulatrice pour peaux grasses.',
    notes: 'Sebulyse. Zinc. Perlite absorbante. LHA.',
    inci: 'WATER, GLYCERIN, DIMETHICONE, ISOCETYL STEARATE, ALCOHOL DENAT., SILICA, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, METHYL METHACRYLATE CROSSPOLYMER, BUTYLENE GLYCOL, PEG-100 STEARATE, COCAMIDE MEA, SARCOSINE, GLYCERYL STEARATE, TRIETHANOLAMINE, ISOHEXADECANE, PERLITE, CAPRYLOYL SALICYLIC ACID, TETRASODIUM EDTA, PENTYLENE GLYCOL, POLYSORBATE 80, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, SALICYLIC ACID, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.BRILLANCE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.PEAU_GRASSE],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.MATIFIANT,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ANTI_ACNE,
        TAG_SLUGS.PEAU_MIXTE,
      ],
      avoid: [
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ROSACEE,
        TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
      ],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SILICA,
        notes: 'Silica/Perlite – matifiant, absorbe sébum',},
      {
        slug: INGREDIENT_SLUGS.CAPRYLOYL_SALICYLIC_ACID,
        notes: 'LHA – exfoliant doux',},
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID },
    ],
  },
  {
    slug: "la-roche-posay-toleriane-sensitive",
    name: 'Tolériane Sensitive Crème',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: "tube",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1499,
    description: 'Crème hydratante apaisante pour peaux sensibles. Renforce la barrière cutanée.',
    notes: 'Niacinamide. Céramide NP. Sans parfum.',
    inci: 'WATER, GLYCERIN, SQUALANE, DIMETHICONE, ZEA MAYS STARCH, NIACINAMIDE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, MYRISTYL MYRISTATE, STEARIC ACID, CERAMIDE NP, POTASSIUM CETYL PHOSPHATE, GLYCERYL STEARATE SE, SODIUM HYDROXIDE, MYRISTIC ACID, PALMITIC ACID, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, XANTHAN GUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.DESHYDRATATION,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Niacinamide – apaisant, barrière',},
      {
        slug: INGREDIENT_SLUGS.CERAMIDE_NP,
        notes: 'Céramide NP – renforce barrière',},
      { slug: INGREDIENT_SLUGS.SQUALANE },
    ],
  },
  {
    slug: "la-roche-posay-vitamin-c12-serum",
    name: 'Pure Vitamin C12 Sérum',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3433,
    description: 'Sérum éclat anti-rides à 12% de vitamine C pure.',
    notes: '12% acide ascorbique. Acide salicylique. Neurosensine.',
    inci: 'WATER, ASCORBIC ACID, DIMETHICONE, GLYCERIN, ALCOHOL DENAT., POTASSIUM HYDROXIDE, POLYSILICONE-11, SILICA, PENTAERYTHRITYL TETRAETHYLHEXANOATE, PEG-20 METHYL GLUCOSE SESQUISTEARATE, SODIUM HYALURONATE, ADENOSINE, POLOXAMER 338, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, HYDROLYZED HYALURONIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, LAURETH-7, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, BIS-PEG/PPG-16/16 PEG/PPG-16/16 DIMETHICONE, ACETYL DIPEPTIDE-1 CETYL ESTER, XANTHAN GUM, PENTYLENE GLYCOL, POLYACRYLAMIDE, C13-14 ISOALKANE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SALICYLIC ACID, PARFUM',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.ANTI_AGE],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ANTI_TACHES,
        TAG_SLUGS.HYPERPIGMENTATION,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
      ],
      avoid: [
        TAG_SLUGS.PEAU_REACTIVE,
        TAG_SLUGS.ROSACEE,
        TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
      ],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.VITAMIN_C,
        notes: '12% Acide ascorbique pur – éclat, anti-taches',},
      {
        slug: INGREDIENT_SLUGS.SALICYLIC_ACID,
        notes: 'Acide salicylique – texture',},
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
    ],
  },
  {
    slug: "la-roche-posay-lipikar-baume-ap-m",
    name: 'Lipikar Baume AP+M Triple-Réparation Anti-Grattage Hydratant',
    brand: 'La Roche-Posay',
    kind: 'balm',
    unit: "jar",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 1899,
    description: 'Baume relipidant anti-démangeaisons et anti-récidive pour peaux très sèches à tendance atopique. Action immédiate sur les démangeaisons et équilibre du microbiome.',
    notes: '4.8 ★. Procerad™ (niacinamide + céramides) + Aqua Posae Filiformis. Apaise en 60s. Réduit 90% le grattage nocturne. Sans parfum. Toute la famille dès la naissance.',
    inci: 'WATER, BUTYROSPERMUM PARKII BUTTER / SHEA BUTTER, GLYCERIN, DIMETHICONE, NIACINAMIDE, CETEARYL ALCOHOL, BRASSICA CAMPESTRIS SEED OIL / RAPESEED SEED OIL, GLYCERYL STEARATE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, PEG-100 STEARATE, PROPANEDIOL, OPHIOPOGON JAPONICUS ROOT EXTRACT, PEG-20 METHYL GLUCOSE SESQUISTEARATE, SORBITAN TRISTEARATE, DIMETHICONOL, SODIUM CHLORIDE, MANNOSE, COCO-BETAINE, DISODIUM EDTA, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, MALTODEXTRIN, XANTHAN GUM, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.BAUME,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.ECZEMA,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SHEA_BUTTER,
        notes: '20% beurre de karité – nutrition intense',},
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Niacinamide – apaisant',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Aqua Posae Filiformis – prébiotique microbiome',},
      { slug: INGREDIENT_SLUGS.GLYCERIN },
      { slug: INGREDIENT_SLUGS.HUILE_COLZA },
      { slug: INGREDIENT_SLUGS.DIMETHICONE },
      { slug: INGREDIENT_SLUGS.TOCOPHEROL },
    ],
  },
  {
    slug: "la-roche-posay-lipikar-lait",
    name: 'Lipikar Lait',
    brand: 'La Roche-Posay',
    kind: 'body-lotion',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 1750,
    description: 'Lait corporel relipidant pour peaux sèches et sensibles. Hydratation 48h, texture fluide et légère à pénétration instantanée sans fini gras.',
    notes: '4.6 ★. Beurre de karité (20%) + Niacinamide + Eau thermale. Confort immédiat, habillage rapide. Sans parfum. Idéal climats chauds. Toute la famille.',
    inci: 'WATER, BUTYROSPERMUM PARKII BUTTER/SHEA BUTTER, GLYCERIN, ISOPROPYL PALMITATE, DIMETHICONE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CETEARYL ALCOHOL, NIACINAMIDE, PEG-100 STEARATE, GLYCERYL STEARATE, SODIUM HYDROXIDE, CARBOMER, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, CAPRYLYL GLYCOL, CITRIC ACID, VITREOSCILLA FERMENT, XANTHAN GUM, PENTYLENE GLYCOL',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.LAIT_CORPS,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.ZONE_CORPS,
      ],
      avoid: [],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SHEA_BUTTER,
        value: 20,
        unit: "%",
        notes: 'Beurre de karité relipidant',},
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Renforce la barrière et apaise',},
      {
        slug: INGREDIENT_SLUGS.DIMETHICONE,
        notes: 'Film occlusif protecteur',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Équilibre du microbiome cutané',},
      {
        slug: INGREDIENT_SLUGS.GLYCERIN,
        notes: 'Humectant',},
      { slug: INGREDIENT_SLUGS.CIRE_ABEILLE },
    ],
  },
  {
    slug: "la-roche-posay-effaclar-gel",
    name: 'Effaclar Gel Moussant Purifiant Nettoyant Anti-Imperfection',
    brand: 'La Roche-Posay',
    kind: 'cleanser',
    unit: "tube",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 1262,
    description: 'Gel nettoyant purifiant moussant pour peaux grasses à tendance acnéique.',
    notes: 'Innovation microbiome avec Phylobioma. Action anti-imperfections en profondeur.',
    inci: 'AQUA / WATER, SODIUM LAURETH SULFATE, PEG-8, COCO-BETAINE, HEXYLENE GLYCOL, SODIUM CHLORIDE, PUNICA GRANATUM PERICARP EXTRACT, ZINC PCA, PEG-120 METHYL GLUCOSE DIOLEATE, SODIUM CITRATE, SODIUM HYDROXIDE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, MALTODEXTRIN, PENTYLENE GLYCOL, TOCOPHEROL, SODIUM BENZOATE, PHENOXYETHANOL, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.PEAU_GRASSE],
      secondary: [
        TAG_SLUGS.GEL_NETTOYANT,
        TAG_SLUGS.DOUBLE_NETTOYAGE_2,
        TAG_SLUGS.MICROBIOME,
        TAG_SLUGS.SANS_SAVON,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.ZONE_CORPS,
        TAG_SLUGS.BRILLANCE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.PEAU_SENSIBLE,
      ],
      avoid: [
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.PEAU_ATOPIQUE,
        TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
      ],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.ZINC_PCA,
        notes: 'Zinc PCA – purifiant',},
      {
        slug: INGREDIENT_SLUGS.PUNICA_GRANATUM,
        notes: 'Extrait grenade – apaisant',},
      {
        slug: INGREDIENT_SLUGS.VITREOSCILLA_FERMENT,
        notes: 'Phylobioma – microbiome',},
    ],
  },
  {
    slug: "serum-mela-b3",
    name: 'Mela B3 Sérum anti-taches concentré intensif',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 4499,
    description: 'Sérum anti-taches intensif contre les taches brunes persistantes.',
    notes: 'Innovation Melasyl™ pour hyperpigmentation. 10% Niacinamide.',
    inci: 'WATER, DIMETHICONE, NIACINAMIDE, GLYCERIN, PROPYLENE GLYCOL, POLYSILICONE-11, SILICA, BIS-PEG/PPG-16/16 PEG/PPG-16/16 DIMETHICONE, CYSTOSEIRA TAMARISCIFOLIA EXTRACT, 2-MERCAPTONICOTINOYL GLYCINE, PEG-20 METHYL GLUCOSE SESQUISTEARATE, SODIUM HYALURONATE, SODIUM HYDROXIDE, SODIUM THIOSULFATE, CARNOSINE, POLOXAMER 338, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, DIPOTASSIUM GLYCYRRHIZATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM, PENTYLENE GLYCOL, OCTYLDODECANOL, RETINYL PALMITATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, PHENOXYETHANOL, CI 17200 / RED 33, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.POST_ACNE,
        TAG_SLUGS.TEINT_TERNE,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.PEAU_GRASSE,
      ],
      avoid: [TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: '10% Niacinamide – anti-taches, barrière',},
      {
        slug: INGREDIENT_SLUGS.MELASYL,
        notes: 'Melasyl™ multibreveté – corrige taches persistantes',},
      { slug: INGREDIENT_SLUGS.CAPRYLOYL_SALICYLIC_ACID },
    ],
  },
  {
    slug: "la-roche-posay-serum-b3-retinol",
    name: 'Rétinol B3 Sérum anti-rides au rétinol régénérant resurfaçant',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 4499,
    description: 'Sérum anti-âge au rétinol pur + libération graduelle, associé à la Vitamine B3.',
    notes: 'Rétinol pur + graduel pour tolérance optimale. Niacinamide apaisante.',
    inci: 'WATER, GLYCERIN, DIMETHICONE, ALCOHOL DENAT., PENTYLENE GLYCOL, NIACINAMIDE, GLYCINE SOJA OIL / SOYBEAN OIL, PPG-6-DECYLTETRADECETH-30, SODIUM HYALURONATE, RETINOL, ADENOSINE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM, POLYSILICONE-11, RETINYL PALMITATE, TOCOPHEROL, PHENOXYETHANOL, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES],
      secondary: [
        TAG_SLUGS.SERUM,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.TRAITEMENT,
        TAG_SLUGS.ZONE_VISAGE,
        TAG_SLUGS.HYPERPIGMENTATION,
        TAG_SLUGS.PHOTO_VIEILLISSEMENT,
        TAG_SLUGS.PORES_DILATES,
        TAG_SLUGS.BARRIERE_CUTANEE,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_NORMALE,
      ],
      avoid: [
        TAG_SLUGS.PEAU_REACTIVE,
        TAG_SLUGS.ROSACEE,
        TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
        TAG_SLUGS.GROSSESSE_COMPATIBLE,
      ],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.RETINOL,
        notes: 'Rétinol pur + libération graduelle – anti-rides',},
      {
        slug: INGREDIENT_SLUGS.NIACINAMIDE,
        notes: 'Niacinamide – apaisant, tolérance',},
      { slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE },
    ],
  },
];
