import { TAG_SLUGS } from '../../tags/seed-tags'
import { TO_PRODUCT_SLUGS } from './theOrdinary'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const TO_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [TO_PRODUCT_SLUGS.TO_NIACINAMIDE_10_ZINC_1]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.TO_HYALURONIC_ACID_2_B5]: {
    primary: [TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.CRUELTY_FREE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.TO_CAFFEINE_5_EGCG]: {
    primary: [TAG_SLUGS.CERNES_POCHES],
    secondary: [
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SOIN_YEUX,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.TO_AZELAIC_ACID_10]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
    ],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_MULTI_PEPTIDE_COPPER_1]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_MATRIXYL_10_HA]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_MULTI_PEPTIDES_HA_EX_BUFFET]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_MULTI_PEPTIDES_YEUX]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SOIN_YEUX,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_ECLAT_MULTI_ANTIOXYDANT]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  
  [TO_PRODUCT_SLUGS.THE_ORDINARY_SOLUTION_GF_15]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },
}
