import { TAG_SLUGS } from '../tags/seed-tags'

/**
 * Mapping des ingrédients (INCI) vers les tags
 * La clé est le nom de l'ingrédient (en minuscule)
 */
export const INGREDIENT_TAG_MAP: Record<string, string[]> = {
  // Anti-âge / Rétinoïdes
  retinol: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  'retinyl palmitate': [TAG_SLUGS.ANTI_AGE],
  retinal: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  bakuchiol: [TAG_SLUGS.ANTI_AGE],
  adenosine: [TAG_SLUGS.ANTI_AGE],

  // Acides / Exfoliation / Anti-Acné
  'azelaic acid': [
    TAG_SLUGS.ANTI_ACNE,
    TAG_SLUGS.ANTI_ROUGEURS,
    TAG_SLUGS.TRAITEMENT,
    TAG_SLUGS.SEBO_REGULATEUR,
  ],
  'salicylic acid': [
    TAG_SLUGS.ANTI_ACNE,
    TAG_SLUGS.EXFOLIATION,
    TAG_SLUGS.SEBO_REGULATEUR,
    TAG_SLUGS.KERATOLYTIQUE,
  ],
  'glycolic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ECLAT, TAG_SLUGS.KERATOLYTIQUE],
  'lactic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.HYDRATATION, TAG_SLUGS.KERATOLYTIQUE],
  'mandelic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ANTI_ACNE],
  gluconolactone: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.PEAU_SENSIBLE],
  'lactobionic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.PEAU_SENSIBLE],
  'benzoyl peroxide': [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SOIN_LOCALISE],

  // Vitamines / Antioxydants
  'ascorbic acid': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  'sodium ascorbyl phosphate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_ACNE],
  'magnesium ascorbyl phosphate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_OXYDANT],
  'tetrahexyldecyl ascorbate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
  tocopherol: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.REPARATEUR],
  'tocopheryl acetate': [TAG_SLUGS.ANTI_OXYDANT],
  'ferulic acid': [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  resveratrol: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  ubiquinone: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],

  // Peptides
  peptide: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
  palmitoyl: [TAG_SLUGS.ANTI_AGE],
  'copper tripeptide': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR],
  'acetyl hexapeptide-8': [TAG_SLUGS.ANTI_AGE],
  matrixyl: [TAG_SLUGS.ANTI_AGE],

  // Hydratation / Barrière / Microbiome
  'hyaluronic acid': [TAG_SLUGS.HYDRATATION, TAG_SLUGS.REPULPANT],
  'sodium hyaluronate': [TAG_SLUGS.HYDRATATION],
  'hydrolyzed hyaluronic acid': [TAG_SLUGS.HYDRATATION],
  glycerin: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.HUMECTANT],
  panthenol: [TAG_SLUGS.APAISANT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
  niacinamide: [
    TAG_SLUGS.BARRIERE_CUTANEE,
    TAG_SLUGS.ECLAT,
    TAG_SLUGS.SEBO_REGULATEUR,
    TAG_SLUGS.PORES_DILATES,
  ],
  ceramide: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENCE],
  'ceramide np': [TAG_SLUGS.BARRIERE_CUTANEE],
  'ceramide ap': [TAG_SLUGS.BARRIERE_CUTANEE],
  'ceramide eop': [TAG_SLUGS.BARRIERE_CUTANEE],
  phytosphingosine: [TAG_SLUGS.BARRIERE_CUTANEE],
  cholesterol: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENCE],
  squalane: [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.TEXTURE_LEGERE],
  urea: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.KERATOLYTIQUE],
  'bifida ferment': [TAG_SLUGS.MICROBIOME, TAG_SLUGS.REPARATEUR],
  lactobacillus: [TAG_SLUGS.MICROBIOME],

  // Apaisement / Anti-rougeurs
  'centella asiatica': [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
  madecassoside: [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
  asiaticoside: [TAG_SLUGS.APAISANT],
  allantoin: [TAG_SLUGS.APAISANT],
  'aloe barbadensis': [TAG_SLUGS.APAISANT, TAG_SLUGS.HYDRATATION],
  bisabolol: [TAG_SLUGS.APAISANT],
  'colloidal oatmeal': [TAG_SLUGS.APAISANT, TAG_SLUGS.ECZEMA],
  'avena sativa': [TAG_SLUGS.APAISANT, TAG_SLUGS.PEAU_SENSIBLE],
  licorice: [TAG_SLUGS.APAISANT, TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES],
  'dipotassium glycyrrhizate': [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ROUGEURS],
  'tranexamic acid': [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.TRAITEMENT],

  // Solaire / Filtres
  'zinc oxide': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.APAISANT],
  'titanium dioxide': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX],
  avobenzone: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  octocrylene: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'ethylhexyl methoxycinnamate': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  homosalate: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'ethylhexyl salicylate': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  tinosorb: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  mexoryl: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
}

/**
 * Mapping des catégories/types CSV (colonne usage_type / category) vers les tags
 */
export const CSV_CATEGORY_TAG_MAP: Record<string, string[]> = {
  // ── usage_type values ───────────────────────────────────────────────────────
  Face: [TAG_SLUGS.ZONE_VISAGE],
  'Skin Treatments': [TAG_SLUGS.TRAITEMENT, TAG_SLUGS.ZONE_VISAGE],
  'Skin Care': [TAG_SLUGS.ZONE_VISAGE],
  Body: [TAG_SLUGS.ZONE_CORPS],
  'Facial Cleansers': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.DOUBLE_NETTOYAGE_2],
  Cleansers: [TAG_SLUGS.NETTOYANT],
  'Toners & Astringents': [TAG_SLUGS.TONIQUE, TAG_SLUGS.PREPARATION, TAG_SLUGS.ZONE_VISAGE],
  Eyes: [TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.CONTOUR_YEUX],
  'Lip Care': [TAG_SLUGS.ZONE_LEVRES, TAG_SLUGS.SOIN_LEVRES],
  'Eye Cream, Gel, Oils, & Serum': [TAG_SLUGS.CONTOUR_YEUX, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX],
  Moisturizers: [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.HYDRATATION],
  Sunscreen: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.CREME_SOLAIRE],
  'Anti-Aging/Anti-Wrinkle': [TAG_SLUGS.ANTI_AGE],
  'Exfoliators, Polishes, & Scrubs': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ZONE_VISAGE],
  Hand: [TAG_SLUGS.ZONE_MAINS, TAG_SLUGS.CREME_MAINS],
  'Cloths, Towelettes, & Wipes': [TAG_SLUGS.NETTOYANT],
  'Acids & Peels': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.TRAITEMENT],
  'Pore Treatments': [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SOIN_LOCALISE],
  'Sets & Kits': [],

  // ── category values ─────────────────────────────────────────────────────────
  // Nettoyage
  'Facial Washes': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.MOUSSE_NETTOYANTE, TAG_SLUGS.DOUBLE_NETTOYAGE_2, TAG_SLUGS.ZONE_VISAGE],
  'Facial Foaming Cleansers': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.MOUSSE_NETTOYANTE, TAG_SLUGS.DOUBLE_NETTOYAGE_2, TAG_SLUGS.ZONE_VISAGE],
  'Foaming Cleansers': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.MOUSSE_NETTOYANTE],
  'Bar Soaps': [TAG_SLUGS.NETTOYANT],
  'Liquid Cleansers & Soaps': [TAG_SLUGS.NETTOYANT],
  'Liquid or Cream Hand Soaps': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.ZONE_MAINS],
  'Facial Cleansers': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.DOUBLE_NETTOYAGE_2],
  'Facial Cleansing Oil': [TAG_SLUGS.HUILE_NETTOYANTE, TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.ZONE_VISAGE],
  'Facial Cleansing Milks': [TAG_SLUGS.LAIT_NETTOYANT, TAG_SLUGS.NETTOYANT, TAG_SLUGS.ZONE_VISAGE],
  'Facial Wipes': [TAG_SLUGS.NETTOYANT, TAG_SLUGS.ZONE_VISAGE],
  'Micellar Water': [TAG_SLUGS.EAU_MICELLAIRE, TAG_SLUGS.DOUBLE_NETTOYAGE_1],
  // Préparation
  Toners: [TAG_SLUGS.TONIQUE, TAG_SLUGS.PREPARATION],
  'Toners & Astringents': [TAG_SLUGS.TONIQUE, TAG_SLUGS.PREPARATION, TAG_SLUGS.ZONE_VISAGE],
  Essence: [TAG_SLUGS.ESSENCE, TAG_SLUGS.PREPARATION],
  Mists: [TAG_SLUGS.BRUME, TAG_SLUGS.PREPARATION],
  'Spray Moisturizers': [TAG_SLUGS.BRUME, TAG_SLUGS.HYDRATATION],
  'Spray Moisturizer': [TAG_SLUGS.BRUME, TAG_SLUGS.HYDRATATION],
  // Traitements / Sérums
  Serums: [TAG_SLUGS.SERUM, TAG_SLUGS.TRAITEMENT],
  'Moisturizing Serums': [TAG_SLUGS.SERUM, TAG_SLUGS.HYDRATATION],
  'Skin Treatments': [TAG_SLUGS.TRAITEMENT, TAG_SLUGS.ZONE_VISAGE],
  'Anti-Aging': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  'Anti-Wrinkle': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  'Anti-Aging/Anti-Wrinkle': [TAG_SLUGS.ANTI_AGE],
  'Anti-Wrinkle Treatments': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  'Firming Treatments': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT, TAG_SLUGS.TRAITEMENT],
  'Dark Spot Corrector & Pigment Corrector': [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.TRAITEMENT],
  'Skin Lightening': [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
  'Spot Treatments': [TAG_SLUGS.SPOT_TREATMENT, TAG_SLUGS.SOIN_LOCALISE],
  'Acne Care (OTC)': [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SPOT_TREATMENT, TAG_SLUGS.SOIN_LOCALISE],
  'Pore Cleansing': [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.NETTOYANT],
  'Pore Refining': [TAG_SLUGS.PORES_DILATES],
  'Pore Treatments': [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SOIN_LOCALISE],
  // Hydratation / Soin
  Creams: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.EMOLLIENCE],
  Moisturizers: [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.HYDRATATION],
  'Moisturizers with SPF': [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.CREME_SOLAIRE, TAG_SLUGS.MATIN],
  'Nighttime Moisturizers': [TAG_SLUGS.CREME_DE_NUIT, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.SOIR],
  'Daytime Moisturizers': [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.MATIN],
  'Tinted Moisturizers': [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.PIGMENTS_VERTS],
  Lotions: [TAG_SLUGS.LOTION, TAG_SLUGS.EMOLLIENCE],
  Gels: [TAG_SLUGS.GEL_CREME],
  'Facial Gels': [TAG_SLUGS.GEL_CREME, TAG_SLUGS.ZONE_VISAGE],
  Oils: [TAG_SLUGS.HUILE_VISAGE, TAG_SLUGS.EMOLLIENCE],
  Balms: [TAG_SLUGS.BAUME],
  'Balms, Ointments & Salves': [TAG_SLUGS.BAUME, TAG_SLUGS.OCCLUSIF, TAG_SLUGS.REPARATEUR],
  Butters: [TAG_SLUGS.OCCLUSIF, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_RICHE],
  Emulsions: [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.CREME_HYDRATANTE],
  // Yeux / Lèvres
  'Eye Cream, Gel, Oils, & Serum': [TAG_SLUGS.CONTOUR_YEUX, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX],
  'Eye Masks & Pads': [TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.MASQUE_HEBDO, TAG_SLUGS.PATCH],
  'Puffiness Treatments': [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX],
  'Dark Circle Treatments': [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX],
  'Lip Balms, Gels, Moisturizers & Oils': [TAG_SLUGS.SOIN_LEVRES, TAG_SLUGS.ZONE_LEVRES, TAG_SLUGS.BAUME],
  'Lip Mask': [TAG_SLUGS.SOIN_LEVRES, TAG_SLUGS.SLEEPING_MASK, TAG_SLUGS.ZONE_LEVRES],
  // Exfoliants
  Exfoliators: [TAG_SLUGS.EXFOLIATION],
  'Exfoliators & Scrubs': [TAG_SLUGS.EXFOLIATION],
  'Exfoliators, Polishes, & Scrubs': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ZONE_VISAGE],
  Scrubs: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_PHYSIQUE],
  'Facial Scrubs': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_PHYSIQUE, TAG_SLUGS.ZONE_VISAGE],
  Polishes: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_PHYSIQUE],
  Peels: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_CHIMIQUE],
  'Acids & Peels': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.TRAITEMENT],
  // Masques
  'Facial Masks': [TAG_SLUGS.MASQUE_TISSU, TAG_SLUGS.MASQUE_HEBDO],
  // Solaires
  Sunscreen: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.CREME_SOLAIRE],
  // Corps / Mains
  Hand: [TAG_SLUGS.ZONE_MAINS, TAG_SLUGS.CREME_MAINS],
  'Sets & Kits': [],
}

/**
 * Mapping des mots-clés présents dans le nom du produit vers les tags
 */
export const NAME_KEYWORD_TAG_MAP: Record<string, string[]> = {
  sunscreen: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.CREME_SOLAIRE],
  spf: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.CREME_SOLAIRE],
  'cleansing oil': [TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.NETTOYANT, TAG_SLUGS.HUILE_NETTOYANTE],
  'cleansing balm': [
    TAG_SLUGS.DOUBLE_NETTOYAGE_1,
    TAG_SLUGS.NETTOYANT,
    TAG_SLUGS.BAUME_DEMAQUILLANT,
  ],
  micellar: [TAG_SLUGS.EAU_MICELLAIRE, TAG_SLUGS.DOUBLE_NETTOYAGE_1],
  cleanser: [TAG_SLUGS.NETTOYANT],
  wash: [TAG_SLUGS.NETTOYANT],
  soap: [TAG_SLUGS.NETTOYANT],
  toner: [TAG_SLUGS.TONIQUE, TAG_SLUGS.PREPARATION],
  essence: [TAG_SLUGS.ESSENCE, TAG_SLUGS.PREPARATION],
  serum: [TAG_SLUGS.SERUM, TAG_SLUGS.TRAITEMENT],
  ampoule: [TAG_SLUGS.AMPOULE, TAG_SLUGS.TRAITEMENT],
  moisturizer: [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.HYDRATATION, TAG_SLUGS.CREME_HYDRATANTE],
  cream: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.EMOLLIENCE],
  gel: [TAG_SLUGS.GEL_CREME],
  lotion: [TAG_SLUGS.LOTION],
  balm: [TAG_SLUGS.BAUME],
  eye: [TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.CONTOUR_YEUX],
  lip: [TAG_SLUGS.ZONE_LEVRES, TAG_SLUGS.SOIN_LEVRES],
  hand: [TAG_SLUGS.ZONE_MAINS, TAG_SLUGS.CREME_MAINS],
  body: [TAG_SLUGS.ZONE_CORPS],
  acne: [TAG_SLUGS.ANTI_ACNE],
  blemish: [TAG_SLUGS.ANTI_ACNE],
  spot: [TAG_SLUGS.SOIN_LOCALISE, TAG_SLUGS.SPOT_TREATMENT],
  patch: [TAG_SLUGS.PATCH],
  mask: [TAG_SLUGS.MASQUE_HEBDO],
  scrub: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_PHYSIQUE],
  peel: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_CHIMIQUE],
  exfoliat: [TAG_SLUGS.EXFOLIATION],
  night: [TAG_SLUGS.SOIR, TAG_SLUGS.CREME_DE_NUIT],
  day: [TAG_SLUGS.MATIN],
  tinted: [TAG_SLUGS.PIGMENTS_VERTS], // Ou autre selon contexte, mais souvent maquillage/correction
}
