import { TAG_SLUGS } from '../tags/seed-tags'

/**
 * Mapping des ingrédients (INCI) vers les tags
 * La clé est le nom de l'ingrédient (en minuscule)
 */
export const INGREDIENT_TAG_MAP: Record<string, string[]> = {
  // Anti-âge / Rétinoïdes
  retinol: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  'retinyl palmitate': [TAG_SLUGS.ANTI_AGE],
  retinal: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
  bakuchiol: [TAG_SLUGS.ANTI_AGE],
  'adenosine': [TAG_SLUGS.ANTI_AGE],

  // Acides / Exfoliation / Anti-Acné
  'azelaic acid': [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.SEBO_REGULATEUR],
  'salicylic acid': [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.KERATOLYTIQUE],
  'glycolic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ECLAT, TAG_SLUGS.KERATOLYTIQUE],
  'lactic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.HYDRATATION, TAG_SLUGS.KERATOLYTIQUE],
  'mandelic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ANTI_ACNE],
  'gluconolactone': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.PEAU_SENSIBLE],
  'lactobionic acid': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.PEAU_SENSIBLE],
  'benzoyl peroxide': [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SOIN_LOCALISE],

  // Vitamines / Antioxydants
  'ascorbic acid': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  'sodium ascorbyl phosphate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_ACNE],
  'magnesium ascorbyl phosphate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_OXYDANT],
  'tetrahexyldecyl ascorbate': [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
  'tocopherol': [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.REPARATEUR],
  'tocopheryl acetate': [TAG_SLUGS.ANTI_OXYDANT],
  'ferulic acid': [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  'resveratrol': [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
  'ubiquinone': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],

  // Peptides
  'peptide': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
  'palmitoyl': [TAG_SLUGS.ANTI_AGE],
  'copper tripeptide': [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR],
  'acetyl hexapeptide-8': [TAG_SLUGS.ANTI_AGE],
  'matrixyl': [TAG_SLUGS.ANTI_AGE],

  // Hydratation / Barrière / Microbiome
  'hyaluronic acid': [TAG_SLUGS.HYDRATATION, TAG_SLUGS.REPULPANT],
  'sodium hyaluronate': [TAG_SLUGS.HYDRATATION],
  'hydrolyzed hyaluronic acid': [TAG_SLUGS.HYDRATATION],
  'glycerin': [TAG_SLUGS.HYDRATATION, TAG_SLUGS.HUMECTANT],
  'panthenol': [TAG_SLUGS.APAISANT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
  'niacinamide': [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ECLAT, TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.PORES_DILATES],
  'ceramide': [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENCE],
  'ceramide np': [TAG_SLUGS.BARRIERE_CUTANEE],
  'ceramide ap': [TAG_SLUGS.BARRIERE_CUTANEE],
  'ceramide eop': [TAG_SLUGS.BARRIERE_CUTANEE],
  'phytosphingosine': [TAG_SLUGS.BARRIERE_CUTANEE],
  'cholesterol': [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENCE],
  'squalane': [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.TEXTURE_LEGERE],
  'urea': [TAG_SLUGS.HYDRATATION, TAG_SLUGS.KERATOLYTIQUE],
  'bifida ferment': [TAG_SLUGS.MICROBIOME, TAG_SLUGS.REPARATEUR],
  'lactobacillus': [TAG_SLUGS.MICROBIOME],

  // Apaisement / Anti-rougeurs
  'centella asiatica': [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
  'madecassoside': [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
  'asiaticoside': [TAG_SLUGS.APAISANT],
  'allantoin': [TAG_SLUGS.APAISANT],
  'aloe barbadensis': [TAG_SLUGS.APAISANT, TAG_SLUGS.HYDRATATION],
  'bisabolol': [TAG_SLUGS.APAISANT],
  'colloidal oatmeal': [TAG_SLUGS.APAISANT, TAG_SLUGS.ECZEMA],
  'avena sativa': [TAG_SLUGS.APAISANT, TAG_SLUGS.PEAU_SENSIBLE],
  'licorice': [TAG_SLUGS.APAISANT, TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES],
  'dipotassium glycyrrhizate': [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ROUGEURS],
  'tranexamic acid': [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.TRAITEMENT],

  // Solaire / Filtres
  'zinc oxide': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.APAISANT],
  'titanium dioxide': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX],
  'avobenzone': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'octocrylene': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'ethylhexyl methoxycinnamate': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'homosalate': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'ethylhexyl salicylate': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'tinosorb': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
  'mexoryl': [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
}

/**
 * Mapping des mots-clés présents dans le nom du produit vers les tags
 */
export const NAME_KEYWORD_TAG_MAP: Record<string, string[]> = {
  sunscreen: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.CREME_SOLAIRE],
  spf: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.CREME_SOLAIRE],
  'cleansing oil': [TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.NETTOYANT, TAG_SLUGS.HUILE_NETTOYANTE],
  'cleansing balm': [TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.NETTOYANT, TAG_SLUGS.BAUME_DEMAQUILLANT],
  'micellar': [TAG_SLUGS.EAU_MICELLAIRE, TAG_SLUGS.DOUBLE_NETTOYAGE_1],
  'cleanser': [TAG_SLUGS.NETTOYANT],
  'wash': [TAG_SLUGS.NETTOYANT],
  'soap': [TAG_SLUGS.NETTOYANT],
  'toner': [TAG_SLUGS.TONIQUE, TAG_SLUGS.PREPARATION],
  'essence': [TAG_SLUGS.ESSENCE, TAG_SLUGS.PREPARATION],
  'serum': [TAG_SLUGS.SERUM, TAG_SLUGS.TRAITEMENT],
  'ampoule': [TAG_SLUGS.AMPOULE, TAG_SLUGS.TRAITEMENT],
  'moisturizer': [TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.HYDRATATION, TAG_SLUGS.CREME_HYDRATANTE],
  'cream': [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.EMOLLIENCE],
  'gel': [TAG_SLUGS.GEL_CREME],
  'lotion': [TAG_SLUGS.LOTION],
  'balm': [TAG_SLUGS.BAUME],
  'eye': [TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.CONTOUR_YEUX],
  'lip': [TAG_SLUGS.ZONE_LEVRES, TAG_SLUGS.SOIN_LEVRES],
  'hand': [TAG_SLUGS.ZONE_MAINS, TAG_SLUGS.CREME_MAINS],
  'body': [TAG_SLUGS.ZONE_CORPS],
  'acne': [TAG_SLUGS.ANTI_ACNE],
  'blemish': [TAG_SLUGS.ANTI_ACNE],
  'spot': [TAG_SLUGS.SOIN_LOCALISE, TAG_SLUGS.SPOT_TREATMENT],
  'patch': [TAG_SLUGS.PATCH],
  'mask': [TAG_SLUGS.MASQUE_HEBDO],
  'scrub': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_PHYSIQUE],
  'peel': [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.EXFOLIANT_CHIMIQUE],
  'exfoliat': [TAG_SLUGS.EXFOLIATION],
  'night': [TAG_SLUGS.SOIR, TAG_SLUGS.CREME_DE_NUIT],
  'day': [TAG_SLUGS.MATIN],
  'tinted': [TAG_SLUGS.PIGMENTS_VERTS], // Ou autre selon contexte, mais souvent maquillage/correction
}
