import type { UnifiedProductSeed } from '../unified-types'
import { TAG_SLUGS } from '../../tags/seed-tags'
import { INGREDIENT_SLUGS } from '../../ingredients/ingredient-slugs'

export const HARUHARU_SEED: UnifiedProductSeed[] = [
  {
    name: 'Black Rice Moisture Deep Cleansing Oil',
    brand: 'Haruharu',
    kind: 'cleanser',
    unit: 'bottle',
    slug: 'haruharu-black-rice-moisture-deep-cleansing-oil',
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Une huile démaquillante profonde qui dissout les impuretés et le maquillage tout en hydratant intensément la peau.',
    notes: `Contient de l'huile de riz noir et de jojoba, idéale pour tous les types de peaux recherchant un nettoyage doux.`,
    inci: 'CAPRYLIC/CAPRIC TRIGLYCERIDE, ETHYLHEXYLGLYCERIN, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, MACADAMIA INTEGRIFOLIA SEED OIL, OLEA EUROPAEA (OLIVE) FRUIT OIL, ORYZA SATIVA (RICE) BRAN OIL, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, SORBETH-30 TETRAOLEATE, TOCOPHEROL',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-moisture-deep-cleansing-oil-5-1-fl-oz-150-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/DFF293475274AF/large_1675456409.jpeg?1675456409',
    tags: {
      primary: [TAG_SLUGS.HUILE_DEMAQUILLANTE, TAG_SLUGS.NETTOYANT, TAG_SLUGS.DOUBLE_NETTOYAGE_1],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [],
    },
    keyIngredients: [],
  },
  {
    name: 'Black Rice Moisture 5.5 Soft Cleansing Gel',
    brand: 'Haruharu',
    kind: 'cleanser',
    unit: 'tube',
    slug: 'haruharu-black-rice-moisture-5-5-soft-cleansing-gel',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Un nettoyant gel au pH équilibré qui purifie la peau en douceur sans altérer sa barrière protectrice naturelle.',
    notes: `Enrichi en extrait de riz noir et de ginseng, parfait pour maintenir l'hydratation des peaux sensibles.`,
    inci: '1,2-HEXANEDIOL, ASPERGILLUS FERMENT, BETA-GLUCAN, BUTYLENE GLYCOL, CITRIC ACID, COCO-BETAINE, CYCLODEXTRIN, ETHYLHEXYLGLYCERIN, GLYCERIN, HYDROXYETHYLCELLULOSE, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PENTYLENE GLYCOL, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POTASSIUM COCOATE, POTASSIUM COCOYL GLYCINATE, PROPANEDIOL, PULSATILLA KOREANA EXTRACT, SODIUM CHLORIDE, TREHALOSE, USNEA BARBATA (LICHEN) EXTRACT, WATER, XANTHAN GUM, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-moisture-5-5-soft-cleansing-gel-100-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/C7733CE69234A9/large_1712126607.jpeg?1712126607',
    tags: {
      primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.GEL_NETTOYANT, TAG_SLUGS.DOUBLE_NETTOYAGE_2],
      secondary: [TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.PEAU_SENSIBLE],
      avoid: [],
    },
    keyIngredients: [],
  },
  {
    name: 'Black Rice Hyaluronic Cream',
    brand: 'Haruharu',
    kind: 'moisturizer',
    unit: 'jar',
    slug: 'haruharu-black-rice-hyaluronic-cream',
    totalAmount: 90,
    amountUnit: 'ml',
    priceCents: 0,
    description: `Une crème hydratante riche qui nourrit intensément et améliore l'élasticité de la peau grâce au riz noir fermenté.`,
    notes: `Contient de l'acide hyaluronique et de l'huile d'onagre, idéale pour les peaux sèches et déshydratées.`,
    inci: '1,2-HEXANEDIOL, ALCOHOL, ASPERGILLUS FERMENT, BUTYLENE GLYCOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL, CETEARYL ALCOHOL, CETEARYL OLIVATE, CETYL PALMITATE, CYCLODEXTRIN, GLYCERIN, HEPTYL UNDECYLENATE, HYALURONIC ACID, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, LIMONENE, LINALOOL, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POLYGLYCERYL-3 STEARATE, PROPANEDIOL, PULSATILLA KOREANA EXTRACT, SODIUM PHYTATE, SORBITAN OLIVATE, SORBITAN PALMITATE, USNEA BARBATA (LICHEN) EXTRACT, WATER, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-cream-black-rice-hyaluronic-3-2-fl-oz-90ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/CAF74EBF47F7E8/large_1700989572.jpeg?1700989572',
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.CREME_HYDRATANTE],
      secondary: [],
      avoid: [],
    },
    keyIngredients: [{ slug: INGREDIENT_SLUGS.HYALURONIC_ACID }],
  },
  {
    name: 'Black Rice Hyaluronic Toner for Sensitive Skin',
    brand: 'Haruharu',
    kind: 'toner',
    unit: 'bottle',
    slug: 'haruharu-black-rice-hyaluronic-toner-sensitive',
    totalAmount: 300,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Une lotion tonique sans alcool ni parfum qui apaise et hydrate profondément les peaux les plus fragiles.',
    notes: 'Formulée avec du riz noir et du bêta-glucane, spécialement conçue pour les peaux ultra-sensibles.',
    inci: '1,2-HEXANEDIOL, ASPERGILLUS FERMENT, BETA-GLUCAN, BETAINE, BUTYLENE GLYCOL, CELLULOSE GUM, CYCLODEXTRIN, GLUCOSE, GLYCERIN, HYALURONIC ACID, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POLYGLYCERYL-10 LAURATE, POLYGLYCERYL-10 MYRISTATE, PROPANEDIOL, PULSATILLA KOREANA EXTRACT, SCUTELLARIA BAICALENSIS ROOT EXTRACT, SODIUM PHYTATE, TAMARINDUS INDICA SEED GUM, USNEA BARBATA (LICHEN) EXTRACT, WATER, XANTHAN GUM, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-hyaluronic-toner-for-sensitive-skin-10-1-fl-oz-300ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/530475C2710CF9/large_1690895646.jpeg?1690895646',
    tags: {
      primary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.HYDRATATION, TAG_SLUGS.PREPARATION],
      secondary: [TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.PEAU_SENSIBLE],
      avoid: [],
    },
    keyIngredients: [{ slug: INGREDIENT_SLUGS.HYALURONIC_ACID }],
  },
  {
    name: 'Black Rice Night Knight Retinol Serum',
    brand: 'Haruharu',
    kind: 'serum',
    unit: 'pump',
    slug: 'haruharu-black-rice-night-knight-retinol-serum',
    totalAmount: 20,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Un sérum de nuit revitalisant au rétinol qui lisse les ridules et améliore la texture de la peau pendant votre sommeil.',
    notes: `Synergie de Rétinol et Bakuchiol, idéal pour lutter contre les signes de l'âge même sur peaux sensibles.`,
    inci: '1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, ADENOSINE, ARGININE, ASPERGILLUS FERMENT, BAKUCHIOL, BUTYLENE GLYCOL, C12-20 ALKYL GLUCOSIDE, C14-22 ALCOHOLS, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CERAMIDE NP, CYCLODEXTRIN, DIPROPYLENE GLYCOL, DISODIUM EDTA, ETHYLHEXYLGLYCERIN, GLUCOSE, GLYCERIN, GLYCERYL STEARATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYDROGENATED LECITHIN, HYDROGENATED POLYISOBUTENE, HYDROXYACETOPHENONE, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POLYGLYCERYL-10 STEARATE, POLYGLYCERYL-2 STEARATE, POTASSIUM CETYL PHOSPHATE, RETINOL, STEARYL ALCOHOL, WATER, XANTHAN GUM',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-night-knight-retinol-serum-0-67-fl-oz-20-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/D93B3FE7C53C99/large_1753515506.jpeg?1753515506',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TRAITEMENT],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINOL },
      { slug: INGREDIENT_SLUGS.BAKUCHIOL },
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP },
    ],
  },
  {
    name: 'Triple AHA Gentle Cleansing Gel',
    brand: 'Haruharu',
    kind: 'cleanser',
    unit: 'tube',
    slug: 'haruharu-triple-aha-gentle-cleansing-gel',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Un gel nettoyant exfoliant doux qui élimine les cellules mortes pour un teint instantanément plus clair.',
    notes: `Contient de l'Acide Mandélique et Tartrique (AHA), idéal pour affiner le grain de peau en douceur.`,
    inci: '1,2-HEXANEDIOL, ASPERGILLUS FERMENT, BETA-GLUCAN, BETAINE, BUTYLENE GLYCOL, CITRIC ACID, COCO-BETAINE, CYCLODEXTRIN, ETHYLHEXYLGLYCERIN, GLYCERIN, HYDROXYETHYLCELLULOSE, MANDELIC ACID, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PENTYLENE GLYCOL, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POTASSIUM COCOYL GLYCINATE, PROPANEDIOL, PULSATILLA KOREANA EXTRACT, SODIUM CHLORIDE, TARTARIC ACID, USNEA BARBATA (LICHEN) EXTRACT, WATER, XANTHAN GUM, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-triple-aha-gentle-cleansing-gel-black-rice-3-38-fl-oz-100-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/D9DE00F6AA7525/large_1752402030.png?1752402030',
    tags: {
      primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.DOUBLE_NETTOYAGE_2],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [],
    },
    keyIngredients: [],
  },
  {
    name: 'Black Rice Bakuchiol Eye Cream',
    brand: 'Haruharu',
    kind: 'eye-cream',
    unit: 'tube',
    slug: 'haruharu-black-rice-bakuchiol-eye-cream',
    totalAmount: 20,
    amountUnit: 'ml',
    priceCents: 0,
    description: `Un soin contour des yeux raffermissant qui réduit l'apparence des cernes et des ridules.`,
    notes: `Bakuchiol + Niacinamide, idéal pour revitaliser le regard sans irriter la peau fine du contour de l'œil.`,
    inci: '1,2-HEXANEDIOL, ADENOSINE, AMINO ACIDS, ASPERGILLUS FERMENT, BAKUCHIOL, BUTYLENE GLYCOL, C12-20 ALKYL GLUCOSIDE, C14-22 ALCOHOLS, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLY/CAPRYL GLUCOSIDE, CARBOMER, CETEARYL ALCOHOL, CETEARYL GLUCOSIDE, CETYL ALCOHOL, CETYL PALMITATE, CYCLODEXTRIN, DISODIUM EDTA, ETHYLHEXYLGLYCERIN, GLUCOSE, GLYCERIN, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, LAURYL ALCOHOL, MADECASSOSIDE, MYRISTYL ALCOHOL, NATTO GUM, NIACINAMIDE, ORYZA SATIVA (RICE) EXTRACT, PANAX GINSENG ROOT EXTRACT, PENTYLENE GLYCOL, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, POLYISOBUTENE, PULSATILLA KOREANA EXTRACT, SODIUM ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SODIUM HYALURONATE, SORBITAN OLEATE, SORBITAN OLIVATE, SORBITAN PALMITATE, STEARYL ALCOHOL, TROMETHAMINE, USNEA BARBATA (LICHEN) EXTRACT, WATER, WHEAT, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-bakuchiol-eye-cream-0-67-fl-oz-20-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/A26BE545B8779F/large_1749448818.png?1749448818',
    tags: {
      primary: [TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.CONTOUR_YEUX, TAG_SLUGS.ANTI_AGE],
      secondary: [TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.ZONE_YEUX],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.BAKUCHIOL },
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
    ],
  },
  {
    name: 'Centella Phyto & 5 Peptide Concentrate Cream',
    brand: 'Haruharu',
    kind: 'moisturizer',
    unit: 'tube',
    slug: 'haruharu-centella-phyto-5-peptide-concentrate-cream',
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Une crème concentrée réparatrice qui renforce la barrière cutanée et raffermit les tissus grâce aux peptides.',
    notes: 'Complexe de 5 Peptides et Centella Asiatica, idéal pour les peaux matures ou abîmées.',
    inci: '1,2-HEXANEDIOL, ACETYL HEXAPEPTIDE-8, ADENOSINE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, ANHYDROXYLITOL, ASIATIC ACID, ASIATICOSIDE, BUTYLENE GLYCOL, BUTYROSPERMUM PARKII (SHEA) BUTTER, CAFFEINE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CENTELLA ASIATICA EXTRACT, CERAMIDE NP, CETYL ALCOHOL, CETYL PALMITATE, COPPER TRIPEPTIDE-1, ETHYLHEXYLGLYCERIN, GLUCOSE, GLYCERIN, GLYCERYL STEARATE, GLYCERYL STEARATE CITRATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HIPPOPHAE RHAMNOIDES FRUIT EXTRACT, HYDROGENATED LECITHIN, HYDROLYZED PEA PROTEIN, HYDROLYZED SOY PROTEIN, LAURYL ALCOHOL, MADECASSIC ACID, MADECASSOSIDE, MYRISTYL ALCOHOL, OLIGOPEPTIDE-29, OLIGOPEPTIDE-32, PALMITOYL PENTAPEPTIDE-4, PENTYLENE GLYCOL, PHYTOSTEROLS, POLYGLYCERYL-3 DISTEARATE, SORBITAN OLIVATE, SORBITAN PALMITATE, SQUALANE, STEARYL ALCOHOL, WATER, XANTHAN GUM, XYLITOL, XYLITYLGLUCOSIDE',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-centella-phyto-5-peptide-concentrate-cream-1-01-fl-oz-30-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/5D7A38D0E46078/large_1744940029.jpeg?1744940029',
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_AGE],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA },
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP },
      { slug: INGREDIENT_SLUGS.COPPER_PEPTIDES },
    ],
  },
  {
    name: 'Black Rice Facial Oil',
    brand: 'Haruharu',
    kind: 'oil',
    unit: 'bottle',
    slug: 'haruharu-black-rice-facial-oil',
    totalAmount: 10,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Une huile visage légère et antioxydante qui apporte un éclat immédiat et une protection contre les radicaux libres.',
    notes: `Mélange d'huiles de son de riz et d'amande douce, idéal pour sceller l'hydratation de tous types de peaux.`,
    inci: 'CAMELLIA SEED OIL, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERYL DIOLEATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HEPTYL UNDECYLENATE, JOJOBA OIL/MACADAMIA SEED OIL ESTERS, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, ORYZA SATIVA (RICE) BRAN OIL, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, TOCOPHEROL, TRIOLEIN',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-facial-oil-0-3-fl-oz-10-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/111544528C5D39/large_1740021103.jpeg?1740021103',
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.OCCLUSION, TAG_SLUGS.ANTI_OXYDANT],
      secondary: [],
      avoid: [],
    },
    keyIngredients: [],
  },
  {
    name: 'Black Rice Probiotics Barrier Essence',
    brand: 'Haruharu',
    kind: 'toner',
    unit: 'pump',
    slug: 'haruharu-black-rice-probiotics-barrier-essence',
    totalAmount: 120,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Une essence fortifiante aux probiotiques qui rééquilibre le microbiome cutané et renforce la barrière de la peau.',
    notes: 'Contient des ferments de riz et des céramides, idéal pour les peaux stressées ou fragilisées.',
    inci: '1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, ARACHIDIC ACID, ASPERGILLUS FERMENT, BIFIDA FERMENT FILTRATE, BUTYLENE GLYCOL, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CERAMIDE AP, CERAMIDE AS, CERAMIDE EOP, CERAMIDE NP, CERAMIDE NS, CETEARYL ALCOHOL, CHOLESTEROL, CYCLODEXTRIN, DISODIUM EDTA, ETHYLHEXYLGLYCERIN, GALACTOMYCES FERMENT FILTRATE, GLYCERIN, GLYCERYL STEARATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYDROGENATED LECITHIN, HYDROGENATED POLYISOBUTENE, HYDROLYZED WHEAT PROTEIN, HYDROXYACETOPHENONE, LIMNANTHES ALBA (MEADOWFOAM) SEED OIL, MYRISTIC ACID, OLEIC ACID, ORYZA SATIVA (RICE) EXTRACT, ORYZA SATIVA (RICE) LEES EXTRACT, PALMITIC ACID, PANAX GINSENG ROOT EXTRACT, PANTHENOL, PENTYLENE GLYCOL, PHYLLOSTACHYS PUBESCENS SHOOT BARK EXTRACT, PHYTOSPHINGOSINE, PHYTOSTEROLS, POLYGLYCERYL-10 LAURATE, POLYGLYCERYL-3 METHYLGLUCOSE DISTEARATE, POTASSIUM CETYL PHOSPHATE, SQUALANE, STEARIC ACID, TROMETHAMINE, WATER, XANTHAN GUM',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-black-rice-probiotics-barrier-essence-4-05-fl-oz-120-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/5FA5E220139D4B/large_1740020794.jpeg?1740020794',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.HYDRATATION, TAG_SLUGS.ESSENCE],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP },
      { slug: INGREDIENT_SLUGS.CERAMIDE_AP },
      { slug: INGREDIENT_SLUGS.PROBIOTICS },
      { slug: INGREDIENT_SLUGS.PANTHENOL },
    ],
  },
  {
    name: 'Black Rice Hyaluronic Toner Fragrance Free',
    brand: 'Haruharu',
    kind: 'toner',
    unit: 'pump',
    slug: 'haruharu-wonder-black-rice-hyaluronic-toner-fragrance-free',
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 892,
    description: 'Tonique hydratant au riz noir coréen + HA + bêta-glucane. Hydratation intense, régénération cellulaire, sans alcool/parfum.',
    notes: '95% naturel, 2000 ppm riz noir. Apaise, repulpe, illumine. Texture légère, tous types (idéal sensible).',
    inci: 'WATER, BETAINE, GLYCERIN, PROPANEDIOL, SCUTELLARIA BAICALENSIS ROOT EXTRACT, ORYZA SATIVA (RICE) EXTRACT, PHYLLOSACHYS PUBESCENS SHOOT BARK EXTRACT, XANTHAN GUM, CELLULOSE GUM, 1,2-HEXANEDIOL, BUTYLENE GLYCOL, PULSATILLA KOREANA EXTRACT, ZANTHOXYLUM PIPERITUM FRUIT EXTRACT, USNEA BARBATA (LICHEN) EXTRACT, ASPERGILLUS FERMENT, SODIUM GLUCONATE, HYALURONIC ACID, BETA-GLUCAN, TAMARINDUS INDICA SEED GUM, PANAX GINSENG ROOT EXTRACT, GLUCOSE, CYCLODEXTRIN',
    url: 'https://haruharuusa.com',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
      secondary: [
        TAG_SLUGS.TONIQUE,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.PREPARATION,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ORYZA_SATIVA, notes: 'Extrait de riz noir fermenté (2000 ppm) — antioxydant, régénérant, illumine',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: 'Hydratation intense, repulpe la peau',},
      { slug: INGREDIENT_SLUGS.BETA_GLUCAN, notes: 'Apaisant, hydratant, renforce barrière',},
      { slug: INGREDIENT_SLUGS.PANAX_GINSENG, notes: 'Extrait de ginseng — revitalisant',},
    ],
  },
  {
    name: 'Dark Spot Go Away Serum',
    brand: 'Haruharu',
    kind: 'serum',
    unit: 'pump',
    slug: 'haruharu-dark-spot-go-away-serum',
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Un sérum ciblé haute performance pour corriger les taches pigmentaires et illuminer le teint durablement.',
    notes: `Contient 4% d'Acide Tranexamique et de la Niacinamide, idéal pour traiter l'hyperpigmentation.`,
    inci: '1,2-HEXANEDIOL, ASCORBIC ACID, ASIATIC ACID, ASIATICOSIDE, BUTYLENE GLYCOL, CENTELLA ASIATICA EXTRACT, ETHYLHEXYLGLYCERIN, MADECASSIC ACID, MADECASSOSIDE, NIACINAMIDE, POLYGLYCERYL-10 LAURATE, PROPANEDIOL, PYRUS COMMUNIS (PEAR) FRUIT EXTRACT, SODIUM ASCORBYL PHOSPHATE, SODIUM POLYACRYLOYLDIMETHYL TAURATE, TRANEXAMIC ACID, WATER',
    url: 'https://www.skinsafeproducts.com/haruharu-wonder-dark-spot-go-away-serum-centella-4-txa-1-01-fl-oz-30-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/7E9AC0E562CA0E/large_1740021031.jpeg?1740021031',
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
      secondary: [TAG_SLUGS.SANS_PARFUM],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRANEXAMIC_ACID },
      { slug: INGREDIENT_SLUGS.NIACINAMIDE },
      { slug: INGREDIENT_SLUGS.VITAMIN_C },
    ],
  },
]
