import { TAG_SLUGS } from '../../tags/seed-tags'
import { AZELAIQUE_PRODUCT_SLUGS } from './azelaique'

interface ProductTagGroups {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const AZELAIQUE_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  // ── Nine Less
  [AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.POST_ACNE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  // ── Purito
  [AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE]: {
    primary: [TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  // ── Nooance
  [AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15]: {
    primary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  // ── Allies of Skin
  [AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ANTI_TACHES],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  // ── Dr Sam
  [AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.POST_ACNE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },
}
