import { TAG_SLUGS } from '../../tags/seed-tags'
import { BIODERMA_PRODUCT_SLUGS } from './bioderma'

interface ProductTagGroups {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const BIODERMA_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_CREME_ULTRA]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.EMOLLIENCE],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_PP_BAUME]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.ECZEMA, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.HUILE_NETTOYANTE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_LEGERE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYDRATATION,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.ECZEMA, TAG_SLUGS.EMOLLIENCE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE]: {
    primary: [TAG_SLUGS.SOIN_YEUX, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.ZONE_YEUX],
    secondary: [TAG_SLUGS.SANS_PARFUM],
    avoid: [],
  },

  
  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_H2O]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.EAU_MICELLAIRE],
    secondary: [TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.HYPOALLERGENIQUE, TAG_SLUGS.ZONE_VISAGE],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE]: {
    primary: [TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.HUILE_DEMAQUILLANTE],
    secondary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_GEL_MOUSSANT]: {
    primary: [TAG_SLUGS.DOUBLE_NETTOYAGE_2, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.GEL_NETTOYANT],
    secondary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.EMOLLIENCE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.EMOLLIENCE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_FORT]: {
    primary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.FLUSHS],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.SOIN_LOCALISE],
    avoid: [],
  },

  
  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.EMOLLIENCE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_TACHES],
    secondary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.CREME_SOLAIRE],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME]: {
    primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.SANS_PARFUM],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_BAUME_LAVANT]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },

  
  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.PEAU_GRASSE],
    secondary: [
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.GEL_NETTOYANT,
      TAG_SLUGS.MATIFIANT,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.EXFOLIATION,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_SENSIBLE],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA]: {
    primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.POST_ACNE],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_H2O]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.EAU_MICELLAIRE],
    secondary: [TAG_SLUGS.PEAU_MIXTE],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  
  [BIODERMA_PRODUCT_SLUGS.BIODERMA_PHOTODERM_XDEFENSE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.POLLUTION],
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_PIGMENTBIO_SENSITIVE_AREAS]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ZONE_CORPS],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.EMOLLIENCE],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA_CLEANSER]: {
    primary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.DOUBLE_NETTOYAGE_2,
      TAG_SLUGS.HYDRATATION,
    ],
    secondary: [
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.SOIN_LOCALISE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_SENSITIVE]: {
    primary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.TRAITEMENT,
    ],
    secondary: [
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SOIN_LOCALISE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_RESTOR]: {
    primary: [
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    secondary: [
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_ARNICA]: {
    primary: [
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SOIN_LOCALISE,
    ],
    secondary: [
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DS_PLUS]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.EMOLLIENCE,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.PROTECTION_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIN_LOCALISE,
    ],
    avoid: [],
  },

  [BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_SOIN_ISOLANT]: {
    primary: [
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    secondary: [
      TAG_SLUGS.SOIN_LOCALISE,
    ],
    avoid: [],
  },
}
