import { INGREDIENT_CATEGORIES, INGREDIENT_TYPES } from '@habit-tracker/shared'
import { INGREDIENT_SLUGS } from '../ingredient-slugs'
import type { IngredientInput } from '../seed-ingredients'

export const HAIR_EPAISSISSANTS: IngredientInput[] = [
  {
    name: 'Carbomer',
    slug: INGREDIENT_SLUGS.CARBOMER_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Acrylates Copolymer',
    slug: INGREDIENT_SLUGS.ACRYLATES_COPOLYMER_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Gomme de Xanthane (Xanthan Gum)',
    slug: INGREDIENT_SLUGS.XANTHAN_GUM_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Gomme de Cellulose (Cellulose Gum)',
    slug: INGREDIENT_SLUGS.CELLULOSE_GUM_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Hydroxyéthylcellulose (Hydroxyethylcellulose)',
    slug: INGREDIENT_SLUGS.HYDROXYETHYLCELLULOSE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Hydroxypropyl Méthylcellulose (Hydroxypropyl Methylcellulose)',
    slug: INGREDIENT_SLUGS.HYDROXYPROPYL_METHYLCELLULOSE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'PEG-120 Methyl Glucose Dioleate',
    slug: INGREDIENT_SLUGS.PEG_120_METHYL_GLUCOSE_DIOLEATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Alginate de Sodium (Sodium Alginate)',
    slug: INGREDIENT_SLUGS.SODIUM_ALGINATE_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Gomme de Sclérote (Sclerotium Gum)',
    slug: INGREDIENT_SLUGS.SCLEROTIUM_GUM,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Gomme de Tara (Caesalpinia Spinosa Gum)',
    slug: INGREDIENT_SLUGS.TARA_GUM,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Cétéaryl Glucoside (Cetearyl Glucoside)',
    slug: INGREDIENT_SLUGS.CETEARYL_GLUCOSIDE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'PEG-40 Huile de Ricin Hydrogénée (PEG-40 Hydrogenated Castor Oil)',
    slug: INGREDIENT_SLUGS.PEG_40_HYDROGENATED_CASTOR_OIL,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
]
