import { INGREDIENT_CATEGORIES, INGREDIENT_TYPES } from '@habit-tracker/shared'
import { INGREDIENT_SLUGS } from '../ingredient-slugs'
import type { IngredientInput } from '../seed-ingredients'

export const HAIR_HUMECTANTS: IngredientInput[] = [
  {
    name: 'Aqua (Water)',
    slug: INGREDIENT_SLUGS.AQUA_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.EXCIPIENT,
    description: '',
    content: '',
  },
  {
    name: 'Glycérine (Glycerin)',
    slug: INGREDIENT_SLUGS.GLYCERIN_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Propylène Glycol (Propylene Glycol)',
    slug: INGREDIENT_SLUGS.PROPYLENE_GLYCOL_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Butylène Glycol (Butylene Glycol)',
    slug: INGREDIENT_SLUGS.BUTYLENE_GLYCOL_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Pentylène Glycol (Pentylene Glycol)',
    slug: INGREDIENT_SLUGS.PENTYLENE_GLYCOL_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Sorbitol',
    slug: INGREDIENT_SLUGS.SORBITOL_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Sodium PCA',
    slug: INGREDIENT_SLUGS.SODIUM_PCA_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Panthénol (Pro-Vitamine B5)',
    slug: INGREDIENT_SLUGS.PANTHENOL_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Aloe Vera (Aloe Barbadensis Leaf Juice)',
    slug: INGREDIENT_SLUGS.ALOE_VERA_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Acide Hyaluronique (Hyaluronic Acid)',
    slug: INGREDIENT_SLUGS.HYALURONIC_ACID_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Hyaluronate',
    slug: INGREDIENT_SLUGS.SODIUM_HYALURONATE_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Bétaïne (Betaine)',
    slug: INGREDIENT_SLUGS.BETAINE_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Fructose',
    slug: INGREDIENT_SLUGS.FRUCTOSE_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Tréhalose (Trehalose)',
    slug: INGREDIENT_SLUGS.TREHALOSE_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
  {
    name: 'Allantoïne (Allantoin)',
    slug: INGREDIENT_SLUGS.ALLANTOIN_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.HUMECTANT,
    description: '',
    content: '',
  },
]
