import { INGREDIENT_CATEGORIES, INGREDIENT_TYPES } from '@habit-tracker/shared'
import { INGREDIENT_SLUGS } from '../ingredient-slugs'
import type { IngredientInput } from '../seed-ingredients'

export const HAIR_TENSIOACTIFS_ANIONIQUES: IngredientInput[] = [
  {
    name: 'Sodium Lauryl Sulfate (SLS)',
    slug: INGREDIENT_SLUGS.SLS_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Laureth Sulfate (SLES)',
    slug: INGREDIENT_SLUGS.SLES_HAIR,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Ammonium Lauryl Sulfate',
    slug: INGREDIENT_SLUGS.AMMONIUM_LAURYL_SULFATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Ammonium Laureth Sulfate',
    slug: INGREDIENT_SLUGS.AMMONIUM_LAURETH_SULFATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Cocoyl Sulfate',
    slug: INGREDIENT_SLUGS.SODIUM_COCOYL_SULFATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Disodium Laureth Sulfosuccinate',
    slug: INGREDIENT_SLUGS.DISODIUM_LAURETH_SULFOSUCCINATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Lauroyl Sarcosinate',
    slug: INGREDIENT_SLUGS.SODIUM_LAUROYL_SARCOSINATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Cocoyl Glutamate',
    slug: INGREDIENT_SLUGS.SODIUM_COCOYL_GLUTAMATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Lauroyl Glutamate',
    slug: INGREDIENT_SLUGS.SODIUM_LAUROYL_GLUTAMATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Cocoyl Isethionate (SCI)',
    slug: INGREDIENT_SLUGS.SODIUM_COCOYL_ISETHIONATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Lauryl Methyl Isethionate (SLMI)',
    slug: INGREDIENT_SLUGS.SODIUM_LAURYL_METHYL_ISETHIONATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'Sodium Coco-Sulfate (SCS)',
    slug: INGREDIENT_SLUGS.SODIUM_COCO_SULFATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
  {
    name: 'TEA Lauryl Sulfate',
    slug: INGREDIENT_SLUGS.TEA_LAURYL_SULFATE,
    type: INGREDIENT_TYPES.HAIRCARE,
    category: INGREDIENT_CATEGORIES.TENSIOACTIF,
    description: '',
    content: '',
  },
]
