import { TAG_SLUGS } from '../../tags/seed-tags'
import { INGREDIENT_SLUGS } from '../../ingredients/ingredient-slugs'
import type { UnifiedProductSeed } from '../unified-types'

export const CYLA_SEED: UnifiedProductSeed[] = [
  {
    slug: 'cyla-essence-initiale',
    name: 'Essence Initiale',
    brand: 'Cyla',
    kind: 'essence',
    unit: 'pump',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 5000,
    description: `Concentré d'hydratation bio-mimétique. Restaure le pH physiologique (5-5,5) et hydrate intensément la couche cornée.`,
    notes: 'Complexe NMF biomimétique à 15%. Flacon airless, pompe 0.2/0.3/0.5g. Avant crème, sur peau humide.',
    inci: 'WATER, SERINE, GLYCERIN, LACTIC ACID, GLYCINE, PCA, UREA, ACETYL GLUCOSAMINE, GLUCOSE, HISTIDINE, LYSINE HCL, GLUTAMINE, LEUCINE, TYROSINE, ARGININE, ASPARTIC ACID, PHENYLALANINE, SODIUM CHLORIDE, POTASSIUM PCA, CALCIUM PCA, MAGNESIUM PCA, BIOSACCHARIDE GUM-1, MALTODEXTRIN, HYDROXYETHYLCELLULOSE, SODIUM NITRATE, SODIUM HYDROXIDE, SODIUM GLUCONATE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, POTASSIUM SORBATE',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.ESSENCE,
        TAG_SLUGS.PREPARATION,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.ECLAT,
        TAG_SLUGS.HYPOALLERGENIQUE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.SERINE,
        notes: 'NMF biomimétique 15% – hydratation, restauration pH physiologique',},
      { slug: INGREDIENT_SLUGS.GLYCINE },
      { slug: INGREDIENT_SLUGS.PCA },
      { slug: INGREDIENT_SLUGS.UREA },
      { slug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE },
      { slug: INGREDIENT_SLUGS.LACTIC_ACID, notes: 'Acide lactique – ajustement pH, hydratant',},
      { slug: INGREDIENT_SLUGS.BIOSACCHARIDE_GUM_1, notes: 'Hydratant filmogène',},
    ],
  },
  {
    slug: 'cyla-gel-plume',
    name: 'Gel Plume',
    brand: 'Cyla',
    kind: 'cleanser',
    unit: 'pump',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 3500,
    description: 'Gel démaquillant et nettoyant biomimétique. Nettoie, apaise et démaquille sans délipider.',
    notes: '50%+ glycérine. Centella Asiatica + avoine. 1ère étape double nettoyage sur peau sèche. Déconseillé pour cils.',
    inci: 'GLYCERIN, WATER, PROPANEDIOL, PHENYL TRIMETHICONE, HYDROGENATED POLYISOBUTENE, PEG-7 GLYCERYL COCOATE, ISONONYL ISONONANOATE, ASIATICOSIDE, MADECASSIC ACID, ASIATIC ACID, AVENA SATIVA (OAT) KERNEL EXTRACT, SODIUM POLYACRYLATE, CAPRYLYL METHICONE, BUTYLENE GLYCOL, TRIDECETH-6, TOCOPHEROL, POTASSIUM SORBATE, PHENOXYETHANOL, CHLORPHENESIN',
    tags: {
      primary: [TAG_SLUGS.HUILE_DEMAQUILLANTE, TAG_SLUGS.DOUBLE_NETTOYAGE_1, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      {
        slug: INGREDIENT_SLUGS.GLYCERIN,
        notes: '50%+ glycérine – hydratation intense, nettoyant sans délipider',},
      { slug: INGREDIENT_SLUGS.ASIATICOSIDE },
      { slug: INGREDIENT_SLUGS.CENTELLA_COMPLEX, notes: 'TECA Centella – apaisant, réparateur',},
      {
        slug: INGREDIENT_SLUGS.AVENA_SATIVA,
        notes: 'Extrait avoine kernel – calmant, anti-irritations',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL },
    ],
  },
  {
    slug: 'cyla-creme-filante',
    name: 'Crème Filante',
    brand: 'Cyla',
    kind: 'cleanser',
    unit: 'pump',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 3400,
    description: 'Crème nettoyante texture guimauve. Nettoie en profondeur sans irriter ni dessécher.',
    notes: 'Tensioactifs doux pH acide. Centella Asiatica + avoine. 2e étape double nettoyage sur peau humide.',
    inci: 'WATER, SODIUM COCOYL ISETHIONATE, GLYCERIN, PALMITIC ACID, SODIUM TAURINE COCOYL METHYLTAURATE, PROPANEDIOL, COCAMIDOPROPYL BETAINE, SODIUM POLYACRYLATE, ACRYLATES COPOLYMER, 1,2-HEXANEDIOL, GLYCERYL STEARATE, SODIUM CHLORIDE, SODIUM HYDROXIDE, CAPRYLHYDROXAMIC ACID, BUTYLENE GLYCOL, CITRIC ACID, ASIATICOSIDE, MADECASSIC ACID, ASIATIC ACID, AVENA SATIVA (OAT) KERNEL EXTRACT, POTASSIUM SORBATE',
    tags: {
      primary: [TAG_SLUGS.GEL_NETTOYANT, TAG_SLUGS.DOUBLE_NETTOYAGE_2, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.SANS_SAVON,
        TAG_SLUGS.PEAU_SENSIBLE,
        TAG_SLUGS.PEAU_TOUS_TYPES,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.ASIATICOSIDE },
      { slug: INGREDIENT_SLUGS.CENTELLA_COMPLEX, notes: 'TECA Centella – apaisant dans nettoyant',},
      { slug: INGREDIENT_SLUGS.AVENA_SATIVA, notes: 'Extrait avoine – calmant',},
      {
        slug: INGREDIENT_SLUGS.SODIUM_COCOYL_ISETHIONATE,
        notes: 'Tensioactif doux – nettoyage pH acide',},
    ],
  },
  {
    slug: 'cyla-creme-legere-initiale',
    name: 'Crème Légère Initiale',
    brand: 'Cyla',
    kind: 'moisturizer',
    unit: 'pump',
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 6500,
    description: 'Crème hydratante légère biomimétique au fini non gras. Restaure hydratation et nutrition.',
    notes: 'Peaux normales/mixtes/grasses. 35 ingrédients biomimétiques : NMF 5% + lipides 2% (1%+ céramides). Après Essence Initiale.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, DIGLYCERIN, GLYCERYL STEARATE CITRATE, MICROCRYSTALLINE CELLULOSE, GLYCERIN, SERINE, LACTIC ACID, C10-18 TRIGLYCERIDES, CETEARYL ALCOHOL, CHOLESTEROL, CERAMIDE AP, CERAMIDE NG, CERAMIDE NP, GLYCOLIPIDS, PHYTOSPHINGOSINE, SPHINGOLIPIDS, LINOLEIC ACID, LINOLENIC ACID, OLEIC ACID, JOJOBA ESTERS, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, PALMITIC ACID, STEARIC ACID, POLYGLYCERIN-3, GLYCERYL STEARATE, SODIUM STEAROYL GLUTAMATE, SODIUM CHLORIDE, GLYCINE, PCA, UREA, HISTIDINE, POTASSIUM PCA, LYSINE HCL, ACETYL GLUCOSAMINE, ARGININE, ASPARTIC ACID, CALCIUM PCA, MAGNESIUM PCA, GLUTAMINE, LEUCINE, PHENYLALANINE, TYROSINE, GLUCOSE, TOCOPHEROL, CELLULOSE GUM, XANTHAN GUM, SODIUM HYDROXIDE, DEHYDROACETIC ACID, SODIUM GLUCONATE, SODIUM ANISATE, SODIUM LEVULINATE',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
      secondary: [
        TAG_SLUGS.GEL_CREME,
        TAG_SLUGS.PEAU_MIXTE,
        TAG_SLUGS.PEAU_GRASSE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.TEXTURE_LEGERE,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.NON_COMEDOGENE,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_SECHE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SERINE, notes: 'NMF biomimétique 5% – hydratation',},
      { slug: INGREDIENT_SLUGS.PCA },
      { slug: INGREDIENT_SLUGS.UREA },
      { slug: INGREDIENT_SLUGS.CERAMIDE_AP },
      { slug: INGREDIENT_SLUGS.CERAMIDE_NG },
      {
        slug: INGREDIENT_SLUGS.CERAMIDE_NP,
        notes: 'Complexe lipides 2% (céramides + cholestérol + acides gras) – barrière',},
      { slug: INGREDIENT_SLUGS.CHOLESTEROL },
      { slug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE },
      { slug: INGREDIENT_SLUGS.LINOLEIC_ACID },
    ],
  },
  {
    slug: 'cyla-creme-intense-initiale',
    name: 'Crème Intense Initiale',
    brand: 'Cyla',
    kind: 'moisturizer',
    unit: 'pump',
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 6500,
    description: 'Crème hydratante veloutée haute nutrition biomimétique. Nourrit et repulpe.',
    notes: 'Peaux normales à sèches. 35 ingrédients biomimétiques : NMF 5% + lipides 2% (1%+ céramides). Après Essence Initiale.',
    inci: 'WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, DIGLYCERIN, C10-18 TRIGLYCERIDES, DIMETHICONE, SERINE, GLYCERYL STEARATE, CETYL ALCOHOL, GLYCERIN, POLYACRYLAMIDE, LACTIC ACID, PCA, PEG-75 STEARATE, PEG-100 STEARATE, CETETH-20, STEARETH-20, LAURETH-7, CAPRYLYL GLYCOL, PALMITIC ACID, STEARIC ACID, C13-14 ISOPARAFFIN, GLYCINE, HISTIDINE, LYSINE HCL, ARGININE, ASPARTIC ACID, GLUTAMINE, LEUCINE, PHENYLALANINE, TYROSINE, CHOLESTEROL, CERAMIDE AP, CERAMIDE NG, CERAMIDE NP, LINOLEIC ACID, GLYCOLIPIDS, PHYTOSPHINGOSINE, SPHINGOLIPIDS, OLEIC ACID, LINOLENIC ACID, SODIUM CHLORIDE, POTASSIUM PCA, SODIUM GLUCONATE, CALCIUM PCA, MAGNESIUM PCA, GLUCOSE, ACETYL GLUCOSAMINE, UREA, TOCOPHEROL, DEHYDROACETIC ACID, 1,2-HEXANEDIOL, POTASSIUM SORBATE, SODIUM HYDROXIDE',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPULPANT],
      secondary: [
        TAG_SLUGS.CREME_HYDRATANTE,
        TAG_SLUGS.PEAU_SECHE,
        TAG_SLUGS.PEAU_NORMALE,
        TAG_SLUGS.TEXTURE_RICHE,
        TAG_SLUGS.OCCLUSIF,
        TAG_SLUGS.SANS_PARFUM,
        TAG_SLUGS.MATIN,
        TAG_SLUGS.SOIR,
        TAG_SLUGS.EMOLLIENCE,
        TAG_SLUGS.OCCLUSION,
        TAG_SLUGS.DESHYDRATATION,
        TAG_SLUGS.ZONE_VISAGE,
      ],
      avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SERINE, notes: 'NMF biomimétique 5% – hydratation',},
      { slug: INGREDIENT_SLUGS.PCA },
      { slug: INGREDIENT_SLUGS.CERAMIDE_AP },
      { slug: INGREDIENT_SLUGS.CERAMIDE_NG },
      {
        slug: INGREDIENT_SLUGS.CERAMIDE_NP,
        notes: 'Complexe lipides 2% – nutrition intense, barrière',},
      { slug: INGREDIENT_SLUGS.CHOLESTEROL },
      { slug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE },
      { slug: INGREDIENT_SLUGS.LINOLEIC_ACID },
      { slug: INGREDIENT_SLUGS.OLEIC_ACID },
    ],
  },
]
