import { TAG_SLUGS } from '../../tags/seed-tags'
import { INGREDIENT_SLUGS } from '../../ingredients/ingredient-slugs'
import type { UnifiedProductSeed } from '../unified-types'

export const INNISFREE_SEED: UnifiedProductSeed[] = [
  {
    slug: 'innisfree-green-tea-seed-serum',
    name: 'Green Tea Seed Serum',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'bottle',
    totalAmount: 80,
    amountUnit: 'ml',
    priceCents: 0,
    description: `Sérum hydratant à base d\"extrait de thé vert Jeju pour nourrir et revitaliser la peau en profondeur.`,
    notes: `Contient du parfum (FRAGRANCE/PARFUM). Riche en Camellia Sinensis, Niacinamide, Acide Hyaluronique et Squalane. Idéal pour peaux normales à mixtes en quête d\"hydratation durable.`,
    inci: 'WATER/AQUA/EAU, 1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, ALCOHOL DENAT, ALLANTOIN, BETAINE, BUTYLENE GLYCOL, CAMELLIA SINENSIS LEAF EXTRACT, CAMELLIA SINENSIS SEED OIL, CAPRYLYL GLYCOL, CERATONIA SILIQUA (CAROB) GUM, CETEARYL OLIVATE, CITRIC ACID, DEXTRIN, DIPOTASSIUM GLYCYRRHIZATE, DISODIUM EDTA, EPIGALLOCATECHIN GALLATE, ETHOXYDIGLYCOL, ETHYLHEXYLGLYCERIN, FRAGRANCE/PARFUM, GLYCERIN, HYALURONIC ACID, HYDROGENATED LECITHIN, HYDROLYZED HYALURONIC ACID, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, LACTIC ACID, LACTOBACILLUS FERMENT LYSATE, LIMONENE, LINALOOL, NIACINAMIDE, PANTHENOL, POLOXAMER 235, POLOXAMER 338, PROPANEDIOL, SACCHARIDE ISOMERATE, SODIUM ACETYLATED HYALURONATE, SODIUM CITRATE, SODIUM HYALURONATE, SODIUM HYALURONATE CROSSPOLYMER, SORBITAN ISOSTEARATE, SORBITAN OLIVATE, SQUALANE, SUCROSE, THEOBROMA CACAO (COCOA) EXTRACT, TOCOPHERSOLAN, TREHALOSE, TROMETHAMINE',
    url: 'https://www.skinsafeproducts.com/innisfree-green-tea-seed-serum-2-70-fl-oz-80-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/9D3A6A7996F60E/large_1684903637.pngpng?1684903637',
    tags: {
      primary: [TAG_SLUGS.SERUM, TAG_SLUGS.HYDRATATION, TAG_SLUGS.TRAITEMENT],
      secondary: [TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.MICROBIOME, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: 'Triple HA (Hyaluronic Acid + Hydrolysé + Sodium Acetylated + Crosspolymer)',},
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: 'Unification teint, sébo-régulation',},
      { slug: INGREDIENT_SLUGS.SQUALANE, notes: 'Émollient léger, biomimétique',},
      { slug: INGREDIENT_SLUGS.PANTHENOL, notes: 'Apaisant / hydratant complémentaire',},
    ],
  },
  {
    slug: 'innisfree-green-tea-seed-hyaluronic-cream',
    name: 'Green Tea Seed Hyaluronic Acid Cream',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'jar',
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 0,
    description: `Crème hydratante riche formulée avec de l\"acide hyaluronique multi-poids et de l\'extrait de thé vert pour une peau repulpée et lumineuse.`,
    notes: 'Associe Céramide NP, Acide Hyaluronique, Madecassoside et Squalane pour un effet barrière renforcé. Idéal pour peaux normales à sèches.',
    inci: 'WATER/AQUA/EAU, 1,2-HEXANEDIOL, ALLANTOIN, BUTYLENE GLYCOL, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, CAMELLIA SINENSIS LEAF EXTRACT, CAMELLIA SINENSIS SEED EXTRACT, CAMELLIA SINENSIS SEED OIL, CARBOMER, CERAMIDE NP, CETEARYL ALCOHOL, CHOLESTEROL, DEXTRIN, ETHYLHEXYLGLYCERIN, GLYCERIN, GLYCERYL CAPRYLATE, GLYCERYL POLYMETHACRYLATE, GLYCERYL STEARATE, HYALURONIC ACID, HYDROGENATED LECITHIN, HYDROLYZED HYALURONIC ACID, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, LACTIC ACID, LACTOBACILLUS FERMENT LYSATE, MADECASSOSIDE, METHYL TRIMETHICONE, PANTHENOL, PENTAERYTHRITYL TETRAETHYLHEXANOATE, PHYTOSPHINGOSINE, POLYGLYCERYL-3 METHYLGLUCOSE DISTEARATE, POLYMETHYLSILSESQUIOXANE, PROPANEDIOL, SODIUM ACETYLATED HYALURONATE, SODIUM HYALURONATE, SODIUM HYALURONATE CROSSPOLYMER, SODIUM METAPHOSPHATE, SODIUM STEAROYL GLUTAMATE, SORBITAN ISOSTEARATE, SQUALANE, STEARYL DIMETHICONE, THEOBROMA CACAO (COCOA) EXTRACT, TOCOPHEROL, TROMETHAMINE, XANTHAN GUM',
    url: 'https://www.skinsafeproducts.com/innisfree-jumbo-hyaluronic-acid-cream-green-tea-seed-2-7-fl-oz-80-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/C9501C7F73DAF6/large_1754260766.jpeg?1754260766',
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP, notes: 'Barrière lipidique',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: 'Triple HA + Sodium Acetylated Hyaluronate',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: 'Madecassoside — apaisant, cicatrisant',},
      { slug: INGREDIENT_SLUGS.SQUALANE, notes: 'Émollient biomimétique',},
    ],
  },
  {
    slug: 'innisfree-super-volcanic-pore-clay-mask',
    name: 'Super Volcanic Pore Clay Mask',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'tube',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Masque argileux purificateur aux cendres volcaniques de Jeju pour affiner les pores et débarrasser la peau des impuretés et excès de sébum.',
    notes: 'Cendres Volcaniques, Kaolin, Bentonite et AHA (Acide Lactique + Acide Glycolique). Idéal pour peaux mixtes à grasses et pores dilatés.',
    inci: 'WATER/AQUA/EAU, 1,2-HEXANEDIOL, BENTONITE, BUTYLENE GLYCOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CETEARYL ALCOHOL, ETHYLHEXYLGLYCERIN, GLYCERIN, GLYCERYL STEARATE, HYDROGENATED VEGETABLE OIL, IRON OXIDES (CI 77499), JUGLANS REGIA (WALNUT) SHELL POWDER, KAOLIN, LACTIC ACID, LACTIC ACID/GLYCOLIC ACID COPOLYMER, LECITHIN, MANNITOL, MENTHOXYPROPANEDIOL, MICROCRYSTALLINE CELLULOSE, PALMITIC ACID, PEG-100 STEARATE, POLYACRYLATE-13, POLYISOBUTENE, POLYQUATERNIUM-10, POLYSORBATE 20, POLYSORBATE 60, POLYVINYL ALCOHOL, PVP, SILICA, SODIUM METAPHOSPHATE, SORBITAN ISOSTEARATE, SORBITAN STEARATE, STEARIC ACID, TETRASODIUM PYROPHOSPHATE, TITANIUM DIOXIDE (CI 77891), TOCOPHEROL, TREHALOSE, VOLCANIC ASH, XANTHAN GUM, ZEA MAYS (CORN) STARCH',
    url: 'https://www.skinsafeproducts.com/innisfree-super-volcanic-pore-clay-mask-volcanic-clusters-aha-3-38-fl-oz-100-ml-0',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/E9D4668BA6B4D9/large_1718482494.jpeg?1718482494',
    tags: {
      primary: [TAG_SLUGS.MASQUE_ARGILE, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.EXFOLIATION],
      secondary: [TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.MASQUE_HEBDO, TAG_SLUGS.ZONE_VISAGE],
      avoid: [],
    },
  },
  {
    slug: 'innisfree-volcanic-bha-pore-cleansing-foam',
    name: 'Volcanic BHA Pore Cleansing Foam',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'tube',
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Mousse nettoyante aux cendres volcaniques et BHA pour purifier les pores en profondeur et réduire les imperfections au quotidien.',
    notes: 'Contient du parfum. Acide Salicylique (BHA), Acide Glycolique, Cendres Volcaniques et Zinc PCA. Idéal pour peaux mixtes à grasses sujettes aux points noirs.',
    inci: 'WATER/AQUA/EAU, BUTYLENE GLYCOL, CITRIC ACID, COCAMIDOPROPYL BETAINE, FRAGRANCE/PARFUM, GLYCERIN, GLYCERYL STEARATE, GLYCOLIC ACID, HYDRATED SILICA, LACTIC ACID, LACTIC ACID/GLYCOLIC ACID COPOLYMER, LAURIC ACID, LAURYL GLUCOSIDE, MADECASSOSIDE, MYRISTIC ACID, PALMITIC ACID, PEG-100 STEARATE, PEG-32, POLYQUATERNIUM-10, POLYQUATERNIUM-7, POTASSIUM HYDROXIDE, SALICYLIC ACID, SILICA, SODIUM BENZOATE, SODIUM CHLORIDE, SODIUM METAPHOSPHATE, STEARIC ACID, VOLCANIC ASH, ZINC PCA',
    url: 'https://www.skinsafeproducts.com/innisfree-volcanic-bha-pore-cleansing-foam-5-07-fl-oz-150-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/9D25FD7A8630C1/large_1739743509.jpeg?1739743509',
    tags: {
      primary: [TAG_SLUGS.MOUSSE_NETTOYANTE, TAG_SLUGS.NETTOYANT, TAG_SLUGS.ANTI_ACNE],
      secondary: [TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.DOUBLE_NETTOYAGE_2, TAG_SLUGS.ZONE_VISAGE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID, notes: 'BHA — kératolytique, désobstructeur de pores',},
    ],
  },
  {
    slug: 'innisfree-retinol-cica-repair-ampoule',
    name: 'Retinol Cica Repair Ampoule',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'bottle',
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Ampoule réparatrice associant rétinol et Centella Asiatica pour lisser les rides, régénérer la barrière cutanée et apaiser les irritations.',
    notes: 'Rétinol + Asiaticoside + Madecassic Acid + Céramide NP + Niacinamide. Idéal pour peaux matures ou fragilisées cherchant un anti-âge bien toléré.',
    inci: 'WATER/AQUA/EAU, 1,2-HEXANEDIOL, ACETYL TETRAPEPTIDE-11, ADENOSINE, ALLANTOIN, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, ASIATIC ACID, ASIATICOSIDE, BETA-CAROTENE, BETA-GLUCAN, BHT, BUTYLENE GLYCOL, CAMELLIA SINENSIS SEED EXTRACT, CAPRYLIC/CAPRIC TRIGLYCERIDE, CERAMIDE NP, CHOLESTEROL, DAUCUS CAROTA SATIVA (CARROT) ROOT EXTRACT, DIBUTYL ADIPATE, ETHYLHEXYLGLYCERIN, GLYCERIN, GLYCINE SOJA (SOYBEAN) OIL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYALURONIC ACID, HYDROGENATED LECITHIN, MADECASSIC ACID, MANNITOL, NIACINAMIDE, PHYTOSPHINGOSINE, PROPANEDIOL, RETINOL, SALICYLIC ACID, SODIUM METHYL STEAROYL TAURATE, STEARYL GLYCYRRHETINATE, TOCOPHEROL, TOCOPHERYL ACETATE',
    url: 'https://www.skinsafeproducts.com/innisfree-retinol-cica-repair-ampoule-1-01-fl-oz-30-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/9DE3388EDB0FEF/large_1709369195.pngpng?1709369195',
    tags: {
      primary: [TAG_SLUGS.AMPOULE, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.ANTI_AGE],
      secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.SOIR],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINOL, notes: 'Anti-âge, renouvellement cellulaire',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: 'Asiaticoside + Madecassic Acid — apaisant, barrière',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP, notes: 'Barrière lipidique',},
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: 'Anti-taches, sébo-régulation',},
      { slug: INGREDIENT_SLUGS.BETA_GLUCAN, notes: 'Apaisant immunomodulateur',},
    ],
  },
  {
    slug: 'innisfree-cherry-blossom-glow-jelly-cream',
    name: 'Cherry Blossom Glow Jelly Cream',
    brand: 'Innisfree',
    kind: 'skincare',
    unit: 'jar',
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Crème-gelée légère à la fleur de cerisier et à la niacinamide pour illuminer le teint et procurer une hydratation fraîche et non grasse.',
    notes: `Contient du parfum. Prunus Yedoensis + Niacinamide + Tocophérol. Idéal pour peaux normales à mixtes en quête d\"éclat sans lourdeur.`,
    inci: 'WATER/AQUA/EAU, 1,2-HEXANEDIOL, AMMONIUM ACRYLOYLDIMETHYLTAURATE/BEHENETH-25 METHACRYLATE CROSSPOLYMER, BETAINE, CARBOMER, DIPROPYLENE GLYCOL, ETHYLHEXYLGLYCERIN, FRAGRANCE/PARFUM, GLYCERIN, NIACINAMIDE, PROPANEDIOL, PRUNUS YEDOENSIS LEAF EXTRACT, SODIUM METAPHOSPHATE, TOCOPHEROL, TROMETHAMINE',
    url: 'https://www.skinsafeproducts.com/innisfree-cherry-blossom-glow-jelly-cream-cherry-blossom-b3-1-69-fl-oz-50-ml',
    imageUrl: 'https://cdn1.skinsafeproducts.com/photo/2B305BB46DCD9B/large_1710320602.pngpng?1710320602',
    tags: {
      primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.GEL_CREME, TAG_SLUGS.ECLAT],
      secondary: [TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: 'Éclat, unification teint',},
    ],
  },
]
