// Phase 1 → Phase 2 backfill helpers.
// Maps each legacy `product_type` slug (42 entries, mixing function + zone +
// texture) to its V2 functional bucket, optional zone, and optional texture.
// Phase 2 script will iterate tag_products and add the derived V2 tags.

import { SKINCARE_PRODUCT_TAG_SLUGS, type SkincareProductTagSlug } from './tag-slugs'

const S = SKINCARE_PRODUCT_TAG_SLUGS

export const SKINCARE_LEGACY_TYPE_TO_V2: Partial<
  Record<SkincareProductTagSlug, SkincareProductTagSlug>
> = {
  // Nettoyants
  [S.BAUME_DEMAQUILLANT]: S.TYPE_NETTOYANT,
  [S.HUILE_DEMAQUILLANTE]: S.TYPE_NETTOYANT,
  [S.HUILE_NETTOYANTE]: S.TYPE_NETTOYANT,
  [S.GEL_NETTOYANT]: S.TYPE_NETTOYANT,
  [S.MOUSSE_NETTOYANTE]: S.TYPE_NETTOYANT,
  [S.LAIT_NETTOYANT]: S.TYPE_NETTOYANT,
  [S.CREME_NETTOYANTE]: S.TYPE_NETTOYANT,
  [S.EAU_MICELLAIRE]: S.TYPE_NETTOYANT,
  [S.NETTOYANT_CORPS]: S.TYPE_NETTOYANT,
  // Toners
  [S.TONIQUE]: S.TYPE_TONER,
  [S.LOTION]: S.TYPE_TONER,
  [S.ESSENCE]: S.TYPE_TONER,
  // Mist
  [S.BRUME]: S.TYPE_MIST,
  // Sérum / Concentré
  [S.SERUM]: S.TYPE_SERUM,
  [S.AMPOULE]: S.TYPE_SERUM,
  [S.HUILE_VISAGE]: S.TYPE_SERUM,
  // Hydratants
  [S.CREME_HYDRATANTE]: S.TYPE_HYDRATANT,
  [S.GEL_CREME]: S.TYPE_HYDRATANT,
  [S.CREME_DE_NUIT]: S.TYPE_HYDRATANT,
  [S.BAUME]: S.TYPE_HYDRATANT,
  [S.LAIT_CORPS]: S.TYPE_HYDRATANT,
  [S.CREME_CORPS]: S.TYPE_HYDRATANT,
  [S.HUILE_CORPS]: S.TYPE_HYDRATANT,
  [S.CREME_MAINS]: S.TYPE_HYDRATANT,
  [S.CREME_PIEDS]: S.TYPE_HYDRATANT,
  // Masques
  [S.MASQUE_ARGILE]: S.TYPE_MASQUE,
  [S.MASQUE_TISSU]: S.TYPE_MASQUE,
  [S.MASQUE_HYDRATANT]: S.TYPE_MASQUE,
  [S.SLEEPING_MASK]: S.TYPE_MASQUE,
  [S.PATCH]: S.TYPE_MASQUE,
  // Exfoliation
  [S.EXFOLIANT_CHIMIQUE]: S.TYPE_EXFOLIATION,
  [S.EXFOLIANT_PHYSIQUE]: S.TYPE_EXFOLIATION,
  [S.GOMMAGE_CORPS]: S.TYPE_EXFOLIATION,
  // Solaire
  [S.CREME_SOLAIRE]: S.TYPE_SOLAIRE,
  [S.CREME_SOLAIRE_TEINTEE]: S.TYPE_SOLAIRE,
  [S.APRES_SOLEIL]: S.TYPE_SOLAIRE,
  [S.AUTO_BRONZANT]: S.TYPE_SOLAIRE,
  // Traitement ciblé
  [S.SPOT_TREATMENT]: S.TYPE_TRAITEMENT,
  [S.CONTOUR_YEUX]: S.TYPE_TRAITEMENT,
  [S.SOIN_LEVRES]: S.TYPE_TRAITEMENT,
  // Primer
  [S.PRIMER]: S.TYPE_PRIMER,
  // Déodorant
  [S.DEODORANT]: S.TYPE_DEODORANT,
  // Outil
  [S.OUTIL_MASSAGE]: S.TYPE_OUTIL,
}

export const SKINCARE_LEGACY_TYPE_TO_ZONE: Partial<
  Record<SkincareProductTagSlug, SkincareProductTagSlug>
> = {
  [S.HUILE_VISAGE]: S.ZONE_VISAGE,
  [S.LAIT_CORPS]: S.ZONE_CORPS,
  [S.CREME_CORPS]: S.ZONE_CORPS,
  [S.HUILE_CORPS]: S.ZONE_CORPS,
  [S.GOMMAGE_CORPS]: S.ZONE_CORPS,
  [S.NETTOYANT_CORPS]: S.ZONE_CORPS,
  [S.CONTOUR_YEUX]: S.ZONE_YEUX,
  [S.SOIN_LEVRES]: S.ZONE_LEVRES,
  [S.CREME_MAINS]: S.ZONE_MAINS,
  [S.CREME_PIEDS]: S.ZONE_PIEDS,
}

// Inferred from legacy slug name only. Conservative — leaves null when ambiguous
// (e.g. SERUM, AMPOULE, ESSENCE: liquid but not strictly 'eau'; product-specific).
export const SKINCARE_LEGACY_TYPE_TO_TEXTURE: Partial<
  Record<SkincareProductTagSlug, SkincareProductTagSlug>
> = {
  [S.GEL_NETTOYANT]: S.TEXTURE_GEL,
  [S.GEL_CREME]: S.TEXTURE_GEL,
  [S.CREME_NETTOYANTE]: S.TEXTURE_CREME,
  [S.CREME_HYDRATANTE]: S.TEXTURE_CREME,
  [S.CREME_DE_NUIT]: S.TEXTURE_CREME,
  [S.CREME_CORPS]: S.TEXTURE_CREME,
  [S.CREME_MAINS]: S.TEXTURE_CREME,
  [S.CREME_PIEDS]: S.TEXTURE_CREME,
  [S.CREME_SOLAIRE]: S.TEXTURE_CREME,
  [S.CREME_SOLAIRE_TEINTEE]: S.TEXTURE_CREME,
  [S.BAUME]: S.TEXTURE_BAUME,
  [S.BAUME_DEMAQUILLANT]: S.TEXTURE_BAUME,
  [S.HUILE_DEMAQUILLANTE]: S.TEXTURE_HUILE,
  [S.HUILE_NETTOYANTE]: S.TEXTURE_HUILE,
  [S.HUILE_VISAGE]: S.TEXTURE_HUILE,
  [S.HUILE_CORPS]: S.TEXTURE_HUILE,
  [S.LAIT_NETTOYANT]: S.TEXTURE_LAIT,
  [S.LAIT_CORPS]: S.TEXTURE_LAIT,
  [S.MOUSSE_NETTOYANTE]: S.TEXTURE_MOUSSE,
  [S.EAU_MICELLAIRE]: S.TEXTURE_EAU,
  [S.BRUME]: S.TEXTURE_EAU,
  [S.TONIQUE]: S.TEXTURE_EAU,
  [S.LOTION]: S.TEXTURE_EAU,
  [S.PATCH]: S.TEXTURE_PATCH,
}
