// ─── Skincare Product Tag Slugs ───────────────────────────────────────────────
// Tags applicable to skincare products.
// Categories: concern, skin_type, skin_zone, product_type, routine_step,
//             skin_effect, product_label, shared_label.

export const SKINCARE_PRODUCT_TAG_SLUGS = {
  // ── Concerns ───────────────────────────────────────────────────────
  // Functional (treat) — first 8
  ACNE_IMPERFECTIONS: 'acne-imperfections',
  ROUGEURS_VASCULAIRES: 'rougeurs-vasculaires',
  ECZEMA_ATOPIE: 'eczema-atopie',
  BARRIERE_CUTANEE: 'barriere-cutanee',
  HYPERPIGMENTATION: 'hyperpigmentation',
  // Slug suffixed to avoid collision with haircare 'reparation' (hair_effect).
  REPARATION: 'reparation-cutanee',
  KERATOSE_PILAIRE: 'keratose-pilaire',
  DESHYDRATATION: 'deshydratation',
  // Aesthetic (improve) — last 5
  ECLAT_TEINT: 'eclat-teint-uniforme',
  ANTI_AGE: 'anti-age',
  PORES_SEBUM: 'pores-sebum',
  CERNES_POCHES: 'cernes-poches',
  PROTECTION: 'protection',

  // ── Skin types ─────────────────────────────────────────────────────
  PEAU_SECHE: 'peau-seche',
  PEAU_MIXTE: 'peau-mixte',
  PEAU_GRASSE: 'peau-grasse',
  PEAU_SENSIBLE: 'peau-sensible',
  PEAU_NORMALE: 'peau-normale',

  // ── Skin zones ─────────────────────────────────────────────────────
  ZONE_VISAGE: 'zone-visage',
  ZONE_CORPS: 'zone-corps',
  ZONE_YEUX: 'zone-yeux',
  ZONE_LEVRES: 'zone-levres',
  ZONE_MAINS: 'zone-mains',
  ZONE_PIEDS: 'zone-pieds',

  // ── Product types V2 (functional, UI-facing) ───────────────────────
  TYPE_NETTOYANT: 'type-nettoyant',
  TYPE_TONER: 'type-toner',
  TYPE_MIST: 'type-mist',
  TYPE_SERUM: 'type-serum',
  TYPE_HYDRATANT: 'type-hydratant',
  TYPE_MASQUE: 'type-masque',
  TYPE_EXFOLIATION: 'type-exfoliation',
  TYPE_SOLAIRE: 'type-solaire',
  TYPE_TRAITEMENT: 'type-traitement',
  TYPE_PRIMER: 'type-primer',
  TYPE_DEODORANT: 'type-deodorant',
  TYPE_OUTIL: 'type-outil',

  // ── Textures (physical format) ─────────────────────────────────────
  TEXTURE_GEL: 'texture-gel',
  TEXTURE_CREME: 'texture-creme',
  TEXTURE_BAUME: 'texture-baume',
  TEXTURE_HUILE: 'texture-huile',
  TEXTURE_LAIT: 'texture-lait',
  TEXTURE_MOUSSE: 'texture-mousse',
  TEXTURE_EAU: 'texture-eau',
  TEXTURE_PATCH: 'texture-patch',
  TEXTURE_STICK: 'texture-stick',

  // ── Product types ──────────────────────────────────────────────────
  BAUME_DEMAQUILLANT: 'baume-demaquillant',
  HUILE_DEMAQUILLANTE: 'huile-demaquillante',
  HUILE_NETTOYANTE: 'huile-nettoyante',
  GEL_NETTOYANT: 'gel-nettoyant',
  MOUSSE_NETTOYANTE: 'mousse-nettoyante',
  LAIT_NETTOYANT: 'lait-nettoyant',
  CREME_NETTOYANTE: 'creme-nettoyante',
  EAU_MICELLAIRE: 'eau-micellaire',
  TONIQUE: 'tonique',
  ESSENCE: 'essence',
  LOTION: 'lotion',
  BRUME: 'brume',
  PRIMER: 'primer',
  SERUM: 'serum',
  AMPOULE: 'ampoule',
  HUILE_VISAGE: 'huile-visage',
  SPOT_TREATMENT: 'spot-treatment',
  CREME_HYDRATANTE: 'creme-hydratante',
  GEL_CREME: 'gel-creme',
  CREME_DE_NUIT: 'creme-de-nuit',
  BAUME: 'baume',
  SLEEPING_MASK: 'sleeping-mask',
  CONTOUR_YEUX: 'contour-yeux',
  SOIN_LEVRES: 'soin-levres',
  EXFOLIANT_CHIMIQUE: 'exfoliant-chimique',
  EXFOLIANT_PHYSIQUE: 'exfoliant-physique',
  MASQUE_ARGILE: 'masque-argile',
  MASQUE_TISSU: 'masque-tissu',
  MASQUE_HYDRATANT: 'masque-hydratant',
  CREME_SOLAIRE: 'creme-solaire',
  CREME_SOLAIRE_TEINTEE: 'creme-solaire-teintee',
  APRES_SOLEIL: 'apres-soleil',
  AUTO_BRONZANT: 'auto-bronzant',
  LAIT_CORPS: 'lait-corps',
  CREME_CORPS: 'creme-corps',
  CREME_MAINS: 'creme-mains',
  HUILE_CORPS: 'huile-corps',
  GOMMAGE_CORPS: 'gommage-corps',
  NETTOYANT_CORPS: 'nettoyant-corps',
  DEODORANT: 'deodorant',
  CREME_PIEDS: 'creme-pieds',
  PATCH: 'patch',
  OUTIL_MASSAGE: 'outil-massage',

  // ── Routine steps ──────────────────────────────────────────────────
  MATIN: 'matin',
  SOIR: 'soir',
  NETTOYANT: 'nettoyant',
  DOUBLE_NETTOYAGE_1: 'double-nettoyage-1',
  DOUBLE_NETTOYAGE_2: 'double-nettoyage-2',
  PREPARATION: 'preparation',
  TRAITEMENT: 'traitement',
  HYDRATATION: 'hydratation',
  EMOLLIENCE: 'emollience',
  PROTECTION_SOLAIRE: 'protection-solaire',
  OCCLUSION: 'occlusion',
  SOIN_YEUX: 'soin-yeux',
  SOIN_LOCALISE: 'soin-localise',
  EXFOLIATION: 'exfoliation',
  MASQUE_HEBDO: 'masque-hebdo',

  // ── Skin effects ───────────────────────────────────────────────────
  OCCLUSIF: 'occlusif',
  REPULPANT: 'repulpant',
  MATIFIANT: 'matifiant',
  PROTECTION_CUTANEE: 'protection-cutanee',
  TEXTURE_RICHE: 'texture-riche',
  TEXTURE_LEGERE: 'texture-legere',
  ANTI_OXYDANT: 'anti-oxydant',
  APAISANT: 'apaisant',
  SEBO_REGULATEUR: 'sebo-regulateur',
  REPARATEUR: 'reparateur',
  PURIFIANT: 'purifiant',
  PREBIOTIQUE: 'prebiotique',
  KERATOLYTIQUE: 'keratolytique',

  // ── Product labels ─────────────────────────────────────────────────
  SANS_PARFUM: 'sans-parfum',
  BIO_NATUREL: 'bio-naturel',
  VEGAN: 'vegan',
  CRUELTY_FREE: 'cruelty-free',
  HYPOALLERGENIQUE: 'hypoallergenique',
  PIGMENTS_VERTS: 'pigments-verts',
  SANS_SAVON: 'sans-savon',
  FILTRES_CHIMIQUES: 'filtres-chimiques',
  FILTRES_MINERAUX: 'filtres-mineraux',
  GROSSESSE_COMPATIBLE: 'grossesse-compatible',

  // ── Shared labels ──────────────────────────────────────────────────
  COMEDOGENE: 'comedogene',
  NON_COMEDOGENE: 'non-comedogene',
} as const

export type SkincareProductTagSlug =
  (typeof SKINCARE_PRODUCT_TAG_SLUGS)[keyof typeof SKINCARE_PRODUCT_TAG_SLUGS]
