import { TAG_SLUGS } from '../../tags/seed-tags'
import { COLIBRI_PRODUCT_SLUGS } from './colibri'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const COLIBRI_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [],
  },

  
  [COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BRILLANCE],
    secondary: [
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  
  [COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER]: {
    primary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },

  
  [COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER]: {
    primary: [TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  
  [COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  
  [COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },
}
