import { TAG_SLUGS } from "../../tags/seed-tags";
import { INGREDIENT_SLUGS } from "../../ingredients/ingredient-slugs";
import type { UnifiedProductSeed } from "../unified-types";

export const THERAMID_SEED: UnifiedProductSeed[] = [
  {
    slug: "theramid-even-in",
    name: 'Even In',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 2995,
    description: 'Traitement anti-taches avancé conçu pour réduire visiblement l’apparence des taches brunes et l’hyperpigmentation.',
    notes: 'Acide Tranexamique, Acide Kojique, Alpha-Arbutine 2%. Étude clinique : -22% de taches en 8 semaines.',
    inci: 'AQUA, GLYCERIN, BETAINE, GLYCERETH-26, TRANEXAMIC ACID, BUTYLENE GLYCOL, ACETYL GLUCOSAMINE, ARBUTIN, KOJIC ACID, NONAPEPTIDE-1, POTASSIUM AZELOYL DIGLYCINATE, GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT, CARNOSINE, LACTOBIONIC ACID, MANDELIC ACID, NIACINAMIDE, LACTOBACILLUS FERMENT, AMINOETHYLPHOSPHINIC ACID, HEXYLRESORCINOL, PHENYLETHYL RESORCINOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, DICAPRYLYL CARBONATE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, CARBOMER, SILICA, DEXTRIN PALMITATE, CAPRYLYL GLYCOL, DIISOSTEARYL MALATE, CITRIC ACID, TOCOPHEROL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
      secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.SERUM, TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.TRAITEMENT],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, notes: '2% - Partie du complexe TXA-Kojic 4%',},
      { slug: INGREDIENT_SLUGS.KOJIC_ACID, notes: '2% - Partie du complexe TXA-Kojic 4%',},
      { slug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, notes: '2%',},
      { slug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, notes: '2% - NAG Amino Monosaccharide',},
    ],
  },
  {
    slug: "theramid-tetramid-cef",
    name: 'Tetramid C.E.F',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "dropper",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3295,
    description: 'Traitement intensif à la vitamine C avec un puissant effet antioxydant pour restaurer la luminosité et combattre le photovieillissement.',
    notes: '20% Vitamin C Complex (Tetra, Ascorbosilane, Glucoside), 1% Vitamine E, 0.5% Acide Férulique.',
    inci: 'AQUA, ASCORBYL TETRAISOPALMITATE, PROPANEDIOL, ASCORBYL GLUCOSIDE, GLYCERIN, TRICAPRYLIN, METHYLPROPANEDIOL, GLYCINE SOJA (SOYBEAN) SEED EXTRACT, TOCOPHEROL, ASCORBYL METHYLSILANOL PECTINATE, FERULIC ACID, LECITHIN, SCLEROTIUM GUM, PULLULAN, XANTHAN GUM, SILICA, SODIUM HYDROXIDE, SODIUM CITRATE, CITRIC ACID, SODIUM BENZOATE, POTASSIUM SORBATE',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
      secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.MATIN, TAG_SLUGS.POLLUTION, TAG_SLUGS.SERUM],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.VITAMIN_C, notes: '20% - Vitamine C Tetra (liposoluble), Ascorbosilane et Ascorbyl Glucoside',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: '1%',},
      { slug: INGREDIENT_SLUGS.FERULIC_ACID, notes: '0.5%',},
    ],
  },
  {
    slug: "theramid-a-retinyl-retinoate",
    name: 'A Retinyl Retinoate',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3995,
    description: 'Traitement anti-âge puissant combinant le rétinoate de rétinyle et le rétinal pur encapsulé pour stimuler le collagène sans irritation.',
    notes: '0,06% Retinyl Retinoate, 0,1% Retinal encapsulé, Sodium Retinoyl Hyaluronate. Utilisation nuit uniquement.',
    inci: 'AQUA, CAPRYLIC/CAPRIC TRIGLYCERIDE, COCO-CAPRYLATE, GLYCERIN, DIMETHICONE, TRIBEHENIN PEG-20 ESTERS, SILICA, COCO-CAPRYLATE/CAPRATE, BETAINE, PANTHENOL, CETEARYL ALCOHOL, RETINAL, RETINYL RETINOATE, SODIUM RETINOYL HYALURONATE, JOJOBA ESTERS, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, PPG-13-DECYLTETRADECETH-24, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, CARBOMER, BUTYLENE GLYCOL, MANNITOL, PHOSPHATIDYLCHOLINE, ISOPROPYL LAUROYL SARCOSINATE, POTASSIUM CETYL PHOSPHATE, CETYL ALCOHOL, ACACIA DECURRENS FLOWER WAX, POLYGLYCERIN-3, DIETHYLHEXYL SYRINGYLIDENEMALONATE, BENZOTRIAZOLYL DODECYL P-CRESOL, XANTHAN GUM, TOCOPHEROL, PHOSPHORIC ACID, CITRIC ACID, ETHYLHEXYLGLYCERIN, SODIUM BENZOATE, POTASSIUM SORBATE, SODIUM CHLORIDE, PHENOXYETHANOL, SODIUM HYDROXIDE',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.SOIR],
      secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.SERUM, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.TRAITEMENT],
      avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINAL, notes: '0.1% - Pur encapsulé liposomal',},
      { slug: INGREDIENT_SLUGS.RETINYL_RETINOATE, notes: '0.06% - Encapsulé liposomal',},
      { slug: INGREDIENT_SLUGS.SODIUM_RETINOYL_HYALURONATE, notes: '0.06% - HyRetin TM',},
    ],
  },
  {
    slug: "theramid-copper-peptide",
    name: 'Copper Peptide',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 4495,
    description: 'Formulation de pointe avec la plus haute concentration de peptides de cuivre pour une peau ferme, lisse et réparée.',
    notes: '3% Copper Peptides, 13% Peptide Complex (Munapsys, Bio-peptides). Ne pas associer aux acides ou rétinoïdes.',
    inci: 'AQUA, PROPANEDIOL, DIMETHICONE, HYDROGENATED ETHYLHEXYL OLIVATE, BETAINE, ISODODECANE, PEG-10 DIMETHICONE, COPPER TRIPEPTIDE-1, BIFIDA FERMENT LYSATE, GLYCERIN, PEG/PPG-18/18 DIMETHICONE, MAGNESIUM SULFATE, HYDROGENATED CASTOR OIL/SEBACIC ACID COPOLYMER, SODIUM HYALURONATE, ACETYL HEXAPEPTIDE-1, ACETYL TETRAPEPTIDE-2, TRIFLUOROACETYL TRIPEPTIDE-2, SH-OLIGOPEPTIDE-1, SH OLIGOPEPTIDE-2, SH-POLYPEPTIDE-1, SH-POLYPEPTIDE-9, SH POLYPEPTIDE-11, BACILLUS/FOLIC ACID FERMENT FILTRATE EXTRACT, ACETYL GLUTAMINE, DISTEARDIMONIUM HECTORITE, HYDROGENATED OLIVE OIL UNSAPONIFIABLES, PROPYLENE CARBONATE, LECITHIN, CAPRYLYL GLYCOL, BUTYLENE GLYCOL, DEXTRAN, TOCOPHEROL, ACETIC ACID, LACTIC ACID, DISODIUM EDTA, SODIUM BENZOATE, 1,2 HEXANEDIOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CICATRISATION, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.SERUM],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.COPPER_PEPTIDES, notes: '3%',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '13% - Munapsys, Peptides Bio, NeoclairPro et Progeline',},
    ],
  },
  {
    slug: "theramid-ceramide-treatment",
    name: 'Ceramide Treatment',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3495,
    description: 'Soin intensif conçu pour restaurer la barrière protectrice de la peau et maintenir une hydratation optimale.',
    notes: '3% Céramides purs, 1% Ectoïne, 1% CICA (Centella Asiatica). Répare les peaux sèches et réactives.',
    inci: 'AQUA, PROPANEDIOL, DICAPRYLYL CARBONATE, GLYCERIN, UNDECANE, CERAMIDE NG, TRIDECANE, GLYCINE SOJA SEED EXTRACT, CERAMIDE NP, CERAMIDE AP, CERAMIDE AS, CERAMIDE NS, CERAMIDE EOP, GOSSYPIUM HERBACEUM CALLUS CULTURE, DIMETHICONE, ECTOIN, ASIATICOSIDE, MADECCASSIC ACID, ASIATIC ACID, SILICA, HYDROGENATED LECITHIN, XANTHAN GUM, SCLEROTIUM GUM, DIPROPYLENE GLYCOL, LECITHIN, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, PULLULAN, SUCROSE DISTEARATE, GLYCERYL STEARATE, CHOLESTEROL, TOCOPHEROL, CITRIC ACID, ALCOHOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
      secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.BAUME],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '3% - Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_NS, notes: 'Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_AP, notes: 'Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_EOP, notes: 'Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_NG, notes: 'Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.CERAMIDE_NP, notes: 'Céramides purs (NG, NP, AP, AS, NS, EOP)',},
      { slug: INGREDIENT_SLUGS.ECTOIN, notes: '1%',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: '1% - CICA',},
    ],
  },
  {
    slug: "theramid-clinical-vitamin-a",
    name: 'Clinical Vitamin A',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3495,
    description: 'Traitement anti-âge haute performance combinant trois formes de vitamine A pour une régénération cellulaire maximale.',
    notes: '5% Granactive Retinoid, 0,3% Rétinol, 0,1% Rétinal encapsulé. Idéal pour les utilisateurs expérimentés de rétinoïdes.',
    inci: 'AQUA, GLYCERIN, COCO-CAPRYLATE/CAPRATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, PROPANEDIOL, COCO-CAPRYLATE, DIMETHYL ISOSORBIDE, POLYGLYCERYL-6 DISTERATE, CELLULOSE ACETATE BUTYRATE, CETYL ALCOHOL, HYDROXYPINACOLONE RETINOATE, RETINOL, RETINAL, LACTOCOCCUS FERMENT LYSATE, PLANKTON EXTRACT, CERAMIDE NG, TOCOPHEROL, ETHYLHEXYLGLYCERIN, JOJOBA ESTERS, LECITHIN, PULLULAN, SCLEROTIUM GUM, XANTHAN GUM, TRICAPRILIN, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CAPRYLYL GLYCOL, SILICA, SODIUM CHLORIDE, LACTIC ACID, CITRIC ACID, PHENOXYETHANOL, SODIUM BENZOATE',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.SOIR, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
      secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.SERUM, TAG_SLUGS.POST_ACNE, TAG_SLUGS.TRAITEMENT],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.GRANACTIVE_RETINOID, notes: '5%',},
      { slug: INGREDIENT_SLUGS.RETINOL, notes: '0.3% - Encapsulé',},
      { slug: INGREDIENT_SLUGS.RETINAL, notes: '0.1% - Pur encapsulé liposomal',},
    ],
  },
  {
    slug: "theramid-azid",
    name: 'AZID',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3495,
    description: 'Traitement intensif à 15% d’acide azélaïque pour réduire les taches, apaiser les rougeurs et traiter les peaux à tendance acnéique.',
    notes: '15% Acide Azélaïque, 1% Carnosine, 1% Avoine Colloïdale. Propriétés antibactériennes et séborégulatrices.',
    inci: 'AQUA, AZELAIC ACID, GLYCERIN, PROPANEDIOL, GLYCERETH-26, AVENA SATIVA (OAT) KERNEL FLOUR, CARNOSINE, ACETYL TETRAPEPTIDE-2, CERAMIDE NP, CERAMIDE EOP, CERAMIDE NS, CERAMIDE AS, CERAMIDE AP, GALLYL GLUCOSIDE, PROPYL GALLATE, EPIGALLOCATECHIN GALLATYL GLUCOSIDE, DAUCUS CAROTA SATIVA ROOT CELL CULTURE LYSATE, GOSSYPIUM HERBACEUM (COTTON) CALLUS CULTURE, SPHINGOMONAS FERMENT EXTRACT, ETHYLHEXYLGLYCERIN, HYDROGENATED LECITHIN, SUCROSE DISTEARATE, GLYCERYL STEARATE, DIPROPYLENE GLYCOL, DEHYDROACETIC ACID, CAPRYLYL GLYCOL, PHENOXYETHANOL, TRIETHANOLAMINE, BENZYL ALCOHOL, CITRIC ACID',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.ROSACEE, TAG_SLUGS.COUPEROSE],
      secondary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SPOT_TREATMENT],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.AZELAIC_ACID, notes: '15%',},
      { slug: INGREDIENT_SLUGS.COLLOIDAL_OATMEAL, notes: '1%',},
      { slug: INGREDIENT_SLUGS.CARNOSINE, notes: '1%',},
    ],
  },
  {
    slug: "theramid-lino-8",
    name: 'Lino-8',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3295,
    description: 'Traitement antioxydant puissant qui nourrit et protège la barrière cutanée grâce à un cocktail de vitamines essentielles.',
    notes: '8% Vitamine F, 1% Vitamine K1, 1% Coenzyme Q10. Améliore l’élasticité et traite les cernes.',
    inci: 'AQUA, PANTHENOL, LINOLEIC ACID, COCO-CAPRYLATE, GLYCERIN, C15-19 ALKANE, PERSEA GRATISSIMA (AVOCADO) OIL, POLYGLYCERYL-6 DISTEARATE, SACCHAROMYCES FERMENT, DIMETHICONE, GLYCERYL STEARATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, PHYTONADIONE EPOXIDE, UBIQUINONE, LINOLENIC ACID, LAUROYL LYSINE, HAEMATOCOCCUS PLUVALIS EXTRACT, SQUALENE, BETA-SITOSTEROL, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, XANTHAN GUM, DISODIUM STEAROYL GLUTAMATE, SCLEROTIUM GUM, TOCOPHEROL, PHENOXYETHANOL, ETHYLHEXYLGLYCERIN',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ECLAT],
      secondary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_LEGERE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.LINOLEIC_ACID, notes: '8% - Acides Linoléique et Linolénique',},
      { slug: INGREDIENT_SLUGS.VITAMIN_K1, notes: '1%',},
      { slug: INGREDIENT_SLUGS.COQ10, notes: '1%',},
    ],
  },
  {
    slug: "theramid-smoothing-treatment",
    name: 'Smoothing Treatment',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 2995,
    description: 'Traitement exfoliant de nuit aux acides AHA et PHA pour une peau plus lisse, lumineuse et unifiée.',
    notes: '10% Gluconolactone, 10% Acide Mandélique, 5% Complexe Peptides Apaisants. Exfoliation douce sans irritation.',
    inci: 'AQUA, GLUCONOLACTONE, MANDELIC ACID, GLYCERIN, PROPANEDIOL, SODIUM HYDROXIDE, BUTYLENE GLYCOL, ETHOXYDIGLYCOL, ACETYL HEXAPEPTIDE-1, ACETYL TETRAPEPTIDE-2, SODIUM HYALURONATE, CAPRYLYL GLYCOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
      secondary: [TAG_SLUGS.SOIR, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.EXFOLIATION],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.PHA, notes: '10% - PHA',},
      { slug: INGREDIENT_SLUGS.MANDELIC_ACID, notes: '10% - AHA',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '5%',},
    ],
  },
  {
    slug: "theramid-derma-peptides",
    name: 'Derma - Peptides',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3295,
    description: 'Sérum multi-peptide ultra-concentré stimulant la production de collagène et d’élastine pour réduire les signes de l’âge.',
    notes: '35% Peptides (Matrixyl, Munapsys, Bio-Peptides). 9 peptides biomimétiques. Texture fondante.',
    inci: 'AQUA, GLYCERIN, PROPANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, BUTYLENE GLYCOL, DODECANE, C15-19 ALKANE, ETHYL MACADAMIATE, SILICA, GLYCINE SOJA (SOYBEAN) SEED EXTRACT, SODIUM HYALURONATE, ACETYL HEXAPEPTIDE-1, N-PROLYL PALMITOYL TRIPEPTIDE-56 ACETATE, ACETYL TETRAPEPTIDE-2, PALMITOYL TRIPEPTIDE-38, PALMITOYL TRIPEPTIDE-1, SH OLIGOPEPTIDE-1, SH-OLIGOPEPTIDE-2, SH-POLYPEPTIDE-1, SH POLYPEPTIDE-11, SH-POLYPEPTIDE-9, PALMITOYL DIPEPTIDE-10, PALMITOYL TETRAPEPTIDE-7, NONAPEPTIDE-1, PALMITOYL TETRAPEPTIDE-72 AMIDE, ACETYL GLUTAMINE, BACILLUS/FOLIC ACID FERMENT FILTRATE EXTRACT, TOCOPHEROL, POLYACRYLATE-13, PULLULAN, POLYISOBUTENE, PENTYLENE GLYCOL, POLYSORBATE 20, 1,2-HEXANEDIOL, LECITHIN, SORBITAN ISOSTEARATE, CARBOMER, SCLEROTIUM GUM, XANTHAN GUM, SODIUM LACTATE, CETYL ALCOHOL, HYDROXYPROPYL CYCLODEXTRIN, MALIC ACID, DEXTRAN, CAPRYLYL GLYCOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.SERUM, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '35% - Mélange de 9 peptides biomimétiques (Matrixyl, Munapsys, etc.)',},
    ],
  },
  {
    slug: "theramid-hapca-filler",
    name: 'HAPCA FILLER',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 3495,
    description: 'Sérum hydratant et repulpant à l’acide hyaluronique de nouvelle génération avec un effet similaire aux fillers dermiques.',
    notes: '5% Sodium PCA, 3% Acide Hyaluronique (Primalhyal Ultrafiller & 3K). Protection contre la pollution et les UV.',
    inci: 'AQUA, GLYCERIN, SODIUM PCA, PROPANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, POLYSORBATE 80, HYDROLYZED HYALURONIC ACID, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, SODIUM ACETYLATED HYALURONATE, BETA-GLUCAN, PHOSPHOLIPIDS, SPHINGOLIPIDS, PLANKTON EXTRACT, CERAMIDE NG, TOCOPHEROL, ETHYLHEXYLGLYCERIN, LECITHIN, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, SQUALANE, PULLULAN, SCLEROTIUM GUM, XANTHAN GUM, CARBOMER, CETEARYL ALCOHOL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SILICA, TRIETHANOLAMINE, SORBITAN OLEATE, PHENOXYETHANOL, POLYSORBATE 20, POTASSIUM SORBATE, SODIUM BENZOATE',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.POLLUTION, TAG_SLUGS.SERUM, TAG_SLUGS.PROTECTION_CUTANEE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SODIUM_PCA, notes: '5%',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: '3% - Inclut Primalhyal Ultrafiller (1%) et Primalhyal 3K (2%)',},
    ],
  },
  {
    slug: "theramid-bakuchiol-firming-cream",
    name: 'Bakuchiol Firming Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1695,
    description: `Crème visage raffermissante avec 1% de bakuchiol, l'alternative végétale et anti-âge au rétinol. Réduit visiblement les rides et ridules, améliore le teint et la texture sans irritation ni sensibilité.`,
    notes: 'Convient à tous les types de peau, même les sensibles. Utilisation jour et nuit. pH: 5-5.3. Complexe de peptides anti-âge pour combattre la perte de fermeté.',
    inci: 'AQUA, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, TRIBEHENIN PEG-20 ESTERS, DIMETHICONE, SQUALANE, PROPANEDIOL, COCO-CAPRYLATE, C10-18 TRIGLYCERIDES, TRICAPRYLIN, BAKUCHIOL, CETEARYL ALCOHOL, CERAMIDE NG, HYDROLYZED HYALURONIC ACID, PALMITOYL TRIPEPTIDE-1, PALMITOYL TETRAPEPTIDE-7, CENTELLA ASIATICA CALLUS CONDITIONED MEDIA, LACTOCOCCUS FERMENT LYSATE, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, XANTHAN GUM, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BUTYLENE GLYCOL, CARBOMER, SODIUM LACTATE, LACTIC ACID, POLYSORBATE 20, TOCOPHEROL, CAPRYLYL GLYCOL, CITRIC ACID, SODIUM CHLORIDE, SODIUM BENZOATE, TOCOPHERYL ACETATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.TEXTURE_RICHE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.BAKUCHIOL, notes: '1% - Alternative végétale au rétinol, réduit rides et ridules, stimule fermeté',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '1% - Combat perte de fermeté, stimule synthèse collagène',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: '1% - Cellules souches, hydratation, apaisement cutané',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: 'Restaure barrière cutanée, améliore hydratation',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: 'Hydratation en profondeur, repulpant immédiat',},
    ],
  },
  {
    slug: "theramid-time-reverse-beauty-sleep-mask",
    name: 'Time Reverse Beauty Sleep Mask',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 75,
    amountUnit: "ml",
    priceCents: 1695,
    description: 'Masque de nuit anti-âge slow-aging sans rinçage. Recharge la peau avec des antioxydants et combat les rides pendant le sommeil. Format pratique et efficace pour oublier vos rides en dormant.',
    notes: 'Usage exclusif le soir, sans rinçage. pH: 5.5-6. Contient 5% de niacinamide, complexe ACE (3%) et acide hyaluronique encapsulé (1%). Retinol 0,2% pour action anti-âge renforcée.',
    inci: 'AQUA, GLYCERIN, NIACINAMIDE, PROPANEDIOL, COMPLEXE ACE, HYALURONIC ACID, RETINOL, BUTYLENE GLYCOL, CETYL ALCOHOL, CETEARYL ALCOHOL, SODIUM PCA, XANTHAN GUM, CARBOMER, DIMETHICONE, SODIUM BENZOATE, TOCOPHEROL, CAPRYLYL GLYCOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
      secondary: [TAG_SLUGS.SLEEPING_MASK, TAG_SLUGS.MASQUE_HYDRATANT, TAG_SLUGS.SOIR, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.HYDRATATION, TAG_SLUGS.OCCLUSION, TAG_SLUGS.PEAU_TOUS_TYPES, TAG_SLUGS.TEXTURE_RICHE, TAG_SLUGS.REPULPANT],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: '5% - Vitamine B3, éclat et apaisement cutané',},
      { slug: INGREDIENT_SLUGS.VITAMIN_C, notes: 'Vitamines A, C, E antioxydantes pour nuit anti-âge',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: 'Vitamines A, C, E antioxydantes pour nuit anti-âge',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: '1% - Encapsulé, hydratation profonde, 0,02% pur',},
      { slug: INGREDIENT_SLUGS.RETINOL, notes: '0.2% - Régénération cellulaire, production collagène',},
    ],
  },
  {
    slug: "theramid-retinal-age-reverse-cream",
    name: 'Retinal Age Reverse Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1895,
    description: 'Crème anti-âge innovante avec rétinal pur encapsulé, la forme la plus puissante de vitamine A. Déclenche la régénération cellulaire et la production de collagène pour éliminer rides et signes visibles du vieillissement.',
    notes: 'Contient 4 actifs anti-âge: rétinal pur (0,03%), complexe acide hyaluronique (3%), peptides (2%), bakuchiol (1%). pH: 5.3-5.8. Résultats visibles dès les premières applications.',
    inci: 'AQUA, GLYCERIN, C10-18 TRIGLYCERIDES, COCO CAPRYLATE/CAPRATE, COCO-CAPRYLATE, PROPANEDIOL, CETYL ALCOHOL, ORYZA SATIVA STARCH, BAKUCHIOL, GLYCERYL STEARATE, RETINAL, HYALURONIC ACID, PALMITOYL TRIPEPTIDE-38, PALMITOYL TRIPEPTIDE-1, PALMITOYL TETRAPEPTIDE-7, MANNITOL, XANTHAN GUM, PEG-75 STEARATE, HYDROXYPROPYL STARCH PHOSPHATE, PHOSPHATIDYLCHOLINE, CETETH-20, STEARETH-20, BUTYLENE GLYCOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CHOLESTEROL, HYDROGENATED PHOSPHATIDYLCHOLINE, DECYL GLUCOSIDE, CARBOMER, CITRIC ACID, SODIUM LACTATE, HYDROXYPROPYL CYCLODEXTRIN, POLYSORBATE 20, TOCOPHEROL, CAPRYLYL GLYCOL, SODIUM CHLORIDE, SODIUM BENZOATE, POTASSIUM SORBATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.SOIR, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_RICHE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.RETINAL, notes: '0.03% - Encapsulé, forme la plus puissante de vit. A, effet régénérant maximal',},
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: '3% - Complexe hautement pénétrant, 0,06% pur',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '2% - Anti-âge multi-peptides, stimule collagène et élastine',},
      { slug: INGREDIENT_SLUGS.BAKUCHIOL, notes: '1% - Complément rétinal, sans irritation additionnelle',},
    ],
  },
  {
    slug: "theramid-niacinamide-glow-cream",
    name: 'Niacinamide Glow Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1595,
    description: `Gel-crème légère et puissante formulée avec 5% de niacinamide pour hydrater, illuminer et uniformiser le teint. Restaure l'éclat, réduit visiblement les imperfections et améliore l'aspect général du visage dès la première application.`,
    notes: `Texture gel-crème légère, idéale tous types de peaux. Complétée par complexe d'acides aminés et céramides pour renforcer la barrière cutanée. pH: 5-5.3. Usage quotidien matin et soir.`,
    inci: 'AQUA, GLYCERIN, NIACINAMIDE, PROPANEDIOL, TRIHEPTANOIN, DIMETHICONE, BETAINE, ETHYL MACADAMIATE, ISOSORBIDE DICAPRYLATE, SODIUM PCA, CERAMIDE NG, PCA, LACTOCOCCUS FERMENT LYSATE, LYSINE, SERINE, ALANINE, GLYCINE, LYSINE HCL, THREONINE, ARGININE, PROLINE, GLUTAMIC ACID, GLUCONOLACTONE, PALMITOYL TRIPEPTIDE-1, PALMITOYL TETRAPEPTIDE-7, MAGNESIUM CHLORIDE, POTASSIUM CHLORIDE, MANGANESE CHLORIDE, ALUMINUM CHLORIDE, COPPER SULFATE, TOCOPHEROL, PHENETHYL ALCOHOL, CAPRYLYL GLYCOL, ZINC CHLORIDE, MALIC ACID, CALCIUM GLUCONATE, SODIUM POLYACRYLATE, CARBOMER, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, HYDROGENATED POLYDECENE, BUTYLENE GLYCOL, SODIUM LACTATE, TRIDECETH-6, SODIUM PHYTATE, LACTIC ACID, SODIUM CHLORIDE, POLYSORBATE 20, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.DESHYDRATATION],
      secondary: [TAG_SLUGS.GEL_CREME, TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PEAU_TOUS_TYPES],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: '5% - Vitamine B3 pur, éclat, réduction imperfections, uniformité teint',},
      { slug: INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS, notes: '2% - Stimule production collagène, lisse rides et ridules',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '0.1% - Fortifie barrière lipidique, prévient déshydratation',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Humectant puissant, rétention hydratation naturelle',},
    ],
  },
  {
    slug: "theramid-proteo-repair-cream",
    name: 'Proteo Repair Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 60,
    amountUnit: "ml",
    priceCents: 1695,
    description: 'Crème anti-âge intensive raffermissante enrichie en fragments de collagène hautement pénétrants. Hydrate, raffermit et revitalise la peau en restaurant fermeté et élasticité tout en réduisant rides et relâchement cutané.',
    notes: 'Fragments de collagène plus petits que le collagène conventionnel pour meilleure pénétration. Contient carnosine (peptide anti-glycation), acides aminés et protéoglycanes. pH: 5.5-6. Texture riche à absorption rapide.',
    inci: 'AQUA, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, BUTYROSPERMUM PARKII BUTTER, NEOPENTYL GLYCOL DIHEPTANOATE, PROPANEDIOL, CETYL ALCOHOL, GLYCERYL STEARATE, LIMNANTHES ALBA SEED OIL, HYDROGENATED SOYBEAN OIL, DIMETHICONE, CARNOSINE, CETEARYL ALCOHOL, COLLAGEN AMINO ACIDS, SOLUBLE PROTEOGLYCAN, ARGININE/LYSINE POLYPEPTIDE, BETAINE, NICOTIANA BENTHAMIANA HEXAPEPTIDE-40 SH-POLYPEPTIDE-47, PCA, SERINE, ALANINE, GLYCINE, GLUTAMIC ACID, LYSINE HCL, THREONINE, ARGININE, PROLINE, TOCOPHEROL, SODIUM PCA, CAMELLIA SINENSIS LEAF WATER, ANTHEMIS NOBILIS FLOWER WATER, BUTYLENE GLYCOL, PENTYLENE GLYCOL, CAPRYLYL GLYCOL, MICROCRYSTALLINE WAX, CARBOMER, GLYCINE SOJA OIL, PEG-75 STEARATE, CETETH-20, STEARETH-20, SQUALENE, BETA-SITOSTEROL, CITRIC ACID, DISODIUM EDTA, SODIUM LACTATE, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_RICHE, TAG_SLUGS.REPULPANT, TAG_SLUGS.PEAU_SECHE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS, notes: '4% - Fragments collagène bio petits (haute pénétration), blocs construction derme',},
      { slug: INGREDIENT_SLUGS.PROTEOGLYCAN_COMPLEX, notes: '2% - Renforce derme, stimule synthèse collagène naturelle, densité cutanée',},
      { slug: INGREDIENT_SLUGS.CARNOSINE, notes: '1% - Peptide anti-glycation, protège collagène et élastine',},
    ],
  },
  {
    slug: "theramid-zitback",
    name: 'Zitback',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "spray",
    totalAmount: 80,
    amountUnit: "ml",
    priceCents: 1495,
    description: `Spray corporel à séchage rapide, sans huile et non comédogène pour traiter l'acné corporelle. À base d'AHA pour exfolier doucement et assécher les boutons, enrichi d'eau de citron naturelle qui réduit la formation de points noirs.`,
    notes: 'Usage corporel uniquement, pas sur le visage. Jour et nuit. Si utilisation diurne sur zones exposées au soleil, appliquer protection solaire. 10% eau de citron, 2,8% acide glycolique, 5% niacinamide.',
    inci: 'AQUA, ALCOHOL DENAT., CITRUS LIMON FRUIT WATER, NIACINAMIDE, GLYCERIN, PROPANEDIOL, GLYCOLIC ACID, BETAINE, VITIS VINIFERA FRUIT EXTRACT, MORINDA CITRIFOLIA CALLUS CULTURE LYSATE, BOSWELLIA SERRATA RESIN EXTRACT, ZINGIBER OFFICINALE ROOT EXTRACT, DISODIUM EDTA, CITRIC ACID',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIATION],
      secondary: [TAG_SLUGS.LAIT_CORPS, TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.ZONE_CORPS, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.SOIN_LOCALISE, TAG_SLUGS.NON_COMEDOGENE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CITRUS_LIMON_FRUIT_WATER, notes: '10% - Exfoliant naturel, réduit formation points noirs',},
      { slug: INGREDIENT_SLUGS.GLYCOLIC_ACID, notes: '2.8% - AHA exfoliant, assèche boutons sans irritation',},
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: '5% - Apaisement, sebo-régulation, confort cutané',},
      { slug: INGREDIENT_SLUGS.BOSWELLIA_SERRATA, notes: '0.1% - Propriétés purifiantes et apaisantes',},
      { slug: INGREDIENT_SLUGS.ZINGIBER_OFFICINALE, notes: '0.1% - Gingembre, propriétés anti-inflammatoires et purifiantes',},
    ],
  },
  {
    slug: "theramid-pure-glycerin-face-serum",
    name: 'Pure Glycerin Face Serum',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "bottle",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1495,
    description: `Sérum hydratant pour le visage idéal pour les peaux sèches et déshydratées. Formulé avec 15% de glycérine, hydrate et nourrit la peau en profondeur tout en maintenant les niveaux d'hydratation nécessaires.`,
    notes: `Glycérine empêche la perte d'eau transépidermique. Enrichi de complexe d'acides aminés pour stimuler production de collagène et lisser rides. pH: 5-5.5. Maintient peau hydratée, souple et ferme.`,
    inci: 'AQUA, GLYCERIN, PROPANEDIOL, DIMETHICONE, BETAINE, PROLINE, THREONINE, GLYCINE, ARGININE, SERINE, ALANINE, LYSINE HCL, PCA, SODIUM PCA, GLUTAMIC ACID, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, SODIUM LACTATE, SODIUM PHYTATE, CARBOMER, HYDROGENATED POLYDECENE, TRIDECETH-6, SODIUM POLYACRYLATE, TOCOPHEROL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.HYDRATATION],
      secondary: [TAG_SLUGS.SERUM, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ANTI_AGE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: '15% - Humectant puissant, empêche perte eau transépidermique, hydratation durable',},
      { slug: INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS, notes: '5% - Stimule production collagène, lisse rides et ridules visiblement',},
    ],
  },
  {
    slug: "theramid-barrier-restoring-hydrating-cream",
    name: 'Barrier Restoring Hydrating Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1795,
    description: 'Crème visage ultra-hydratante formulée avec acide hyaluronique à haute pénétration, complexe antioxydant ACE et céramides végétales. Hydrate et nourrit en profondeur, améliorant visiblement texture et apparence pour peaux sèches.',
    notes: 'Contient madécassoside et T.E.C.A de Centella Asiatica pour action réparatrice anti-âge. pH: 5.3-5.8. Idéale pour peaux sèches en prévention et amélioration des signes du vieillissement.',
    inci: 'AQUA, GLYCERIN, C10-18 TRIGLYCERIDES, COCO CAPRYLATE/CAPRATE, COCO-CAPRYLATE, PROPANEDIOL, CETYL ALCOHOL, ORYZA SATIVA STARCH, GLYCERYL STEARATE, SODIUM ASCORBYL PHOSPHATE, RETINYL PALMITATE, HYALURONIC ACID, CERAMIDE NG, MADECASSOSIDE, ASIATICOSIDE, MADECCASSIC ACID, ASIATIC ACID, MANNITOL, XANTHAN GUM, PEG 75 STEARATE, HYDROXYPROPYL STARCH PHOSPHATE, PHOSPHATIDYLCHOLINE, CETETH-20, CHOLESTEROL, STEARETH-20, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, HYDROGENATED PHOSPHATIDYLCHOLINE, PENTYLENE GLYCOL, DECYL GLUCOSIDE, TOCOPHERYL ACETATE, SODIUM CHLORIDE, TOCOPHEROL, CAPRYLYL GLYCOL, POTASSIUM SORBATE, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PEAU_SENSIBLE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: '5% - Encapsulé haute pénétration, 0,1% pur, hydratation multi-couches',},
      { slug: INGREDIENT_SLUGS.VITAMIN_C, notes: '3% - Vitamines A, C, E antioxydantes protection contre vieillissement',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: 'Vitamines A, C, E antioxydantes protection contre vieillissement',},
      { slug: INGREDIENT_SLUGS.MADECASSOSIDE, notes: '0.1% - Centella Asiatica, apaisement et régénération barrière',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '0.1% - Restaure film hydrolipidique, prévient irritation',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: '0.1% - Complexe Centella Asiatica, réparation cutanée avancée',},
    ],
  },
  {
    slug: "theramid-ceramide-repair-moisturizer",
    name: 'Ceramide Repair Moisturizer',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "bottle",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 1795,
    description: `Sérum ultra-hydratant avec céramides d'origine végétale qui aident à rétablir l'hydratation naturelle et réparer le film hydrolipidique. Nanovésicules d'acide hyaluronique hautement concentré pour hydratation interne et stimulation de collagène.`,
    notes: 'Contient 3% acide hyaluronique encapsulé, 1% complexe céramides, 0,5% ectoine, 0,1% madécassoside. pH: 5.3-5.8. Peut être dernière étape ou associée à crème jour/nuit.',
    inci: 'AQUA, GLYCERIN, PROPANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, POLYSORBATE 80, PRUNUS AMYGDALUS DULCIS OIL, HYALURONIC ACID, CERAMIDE NP, CERAMIDE NG, CERAMIDE EOP, CERAMIDE NS, CERAMIDE AS, CERAMIDE AP, ECTOIN, MADECASSOSIDE, ETHYLHEXYLGLYCERIN, HELIANTHUS ANNUUS SEED OIL, SQUALANE, HYDROGENATED LECITHIN, HYDROGENATED PHOSPHATIDYLCHOLINE, PHOSPHATIDYLCHOLINE, MANNITOL, SUCROSE DISTEARATE, CHOLESTEROL, XANTHAN GUM, CARBOMER, CETEARYL ALCOHOL, TOCOPHEROL, GLYCERYL STEARATE, DECYL GLUCOSIDE, PENTYLENE GLYCOL, PROPYLENE GLYCOL, POLYSORBATE 20, SORBITAN OLEATE, SODIUM CHLORIDE, TRIETHANOLAMINE, SODIUM BENZOATE, POTASSIUM SORBATE, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
      secondary: [TAG_SLUGS.SERUM, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_REACTIVE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.HYALURONIC_ACID, notes: '3% - Encapsulé nanovésicules, 0,06% pur, hydratation interne',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '1% - Complexe céramides multi (NP, NG, EOP, NS, As, AP), restaure hydration naturelle',},
      { slug: INGREDIENT_SLUGS.ECTOIN, notes: '0.5% - Osmoprotecteur, renforce barrière lipidique',},
      { slug: INGREDIENT_SLUGS.MADECASSOSIDE, notes: '0.1% - Centella Asiatica, apaisement et régénération',},
    ],
  },
  {
    slug: "theramid-zitcalm-cream",
    name: 'Zitcalm Cream',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 50,
    amountUnit: "ml",
    priceCents: 1495,
    description: 'Crème hydratante et réparatrice spécialement conçue pour atténuer les effets des traitements anti-acnéiques agressifs qui dessèchent. Restaure la barrière protectrice et redonne du confort à la peau apaisée.',
    notes: 'Apaise, réduit et prévient rougeurs et sécheresse. Contient vitamine F, bisabolol et allantoïne. Texture crémeuse non grasse, pénétration rapide. Pour peaux sèches sensibilisées par traitements anti-acnéiques.',
    inci: 'AQUA, COCO-CAPRYLATE/CAPRATE, ETHYL MACADAMIATE, GLYCERIN, C10-18 TRIGLYCERIDES, PROPANEDIOL, POLYGLYCERYL-6 DISTEARATE, BISABOLOL, ALLANTOIN, GLYCERETH-26, CANDELILLA/JOJOBA/RICE BRAN POLYGLYCERYL-3 ESTERS, SCLEROTIUM GUM, ISOSORBIDE DICAPRYLATE, ZINC HYDROLYZED HYALURONATE, LINOLEIC ACID, LINOLENIC ACID, SQUALENE, MORINDA CITRIFOLIA CALLUS CULTURE LYSATE, POTASSIUM CETYL PHOSPHATE, HELIANTHUS ANNUUS SEED OIL, TOCOPHEROL, CITRIC ACID, BETA-SITOSTEROL, PHOSPHORIC ACID, MALIC ACID, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.HYDRATATION, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE],
      avoid: [TAG_SLUGS.BRILLANCE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.MORINDA_CITRIFOLIA, notes: '2% - Quora Noni, propriétés apaisantes et antioxydantes',},
      { slug: INGREDIENT_SLUGS.LINOLEIC_ACID, notes: '1% - Acides gras essentiels (linoléique, linolénique), restaure barrière',},
      { slug: INGREDIENT_SLUGS.BISABOLOL, notes: '2% - Apaisement puissant, réduit rougeurs et irritations',},
      { slug: INGREDIENT_SLUGS.ALLANTOIN, notes: '2% - Cicatrisant et apaisant, hydrate et apaise tiraillement',},
    ],
  },
  {
    slug: "theramid-zitcontrol",
    name: 'Zitcontrol',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 40,
    amountUnit: "ml",
    priceCents: 1795,
    description: `Crème légère exclusive pour lutter contre l'acné avec acide salicylique, Zinc PCA, niacinamide et Quora Noni. Aide à contrôler les boutons, les réduire et empêcher leur réapparition grâce à Nichosome®.`,
    notes: 'Système Nichosome® de libération progressive pour efficacité 12× supérieure sans irritation. Contient 5% niacinamide, 3% Quora Noni, 5% acide salicylique liposomé, 3% Zinc PCA. Pour acné active ou prévention.',
    inci: 'AQUA, NIACINAMIDE, COCO-CAPRYLATE/CAPRATE, GLYCERIN, SALICYLIC ACID, ZINC PCA, MORINDA CITRIFOLIA CALLUS CULTURE LYSATE, DAUCUS CAROTA SATIVA ROOT CELL CULTURE LYSATE, CERAMIDE NP, ETHYLHEXYLGLYCERIN, HYDROGENATED PHOSPHATIDYLCHOLINE, PHOSPHATIDYLCHOLINE, DIMYRISTOYL PHOSPHATIDYLCHOLINE, MANNITOL, LECITHIN, STEARAMINE, CHOLESTEROL, XANTHAN GUM, SODIUM ACRYLATES COPOLYMER, SODIUM ACRYLATES CROSSPOLYMER-2, OLIVE OIL POLYGLYCERYL-6 ESTERS, SORBITAN OLEATE, TOCOPHEROL, LAURYL GLUCOSIDE, DECYL GLUCOSIDE, SODIUM CHLORIDE, CITRIC ACID, SODIUM BENZOATE, POTASSIUM SORBATE, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_ACNE],
      secondary: [TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.SPOT_TREATMENT, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.SOIN_LOCALISE, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.NON_COMEDOGENE],
      avoid: [TAG_SLUGS.PEAU_SECHE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: '3% - Sebo-régulation, pores dilatés',},
      { slug: INGREDIENT_SLUGS.ZINC_PCA, notes: '1% - Matifiant puissant, assainit',},
      { slug: INGREDIENT_SLUGS.SALICYLIC_ACID, notes: '0.5% - BHA, exfolie pores en profondeur',},
      { slug: INGREDIENT_SLUGS.TEA_TREE, notes: '1% - Propriétés antibactériennes naturelles',},
    ],
  },
  {
    slug: "theramid-zi-k-cica-repairing-balm",
    name: 'Zi-K® Cica Repairing Balm',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 100,
    amountUnit: "ml",
    priceCents: 1495,
    description: 'Baume réparateur et apaisant pour les peaux très sèches, abîmées, irritées ou fragiles. Combinaison puissante de Centella Asiatica et dérivés (T.E.C.A, Madecassoside), panthénol et complexe céramides.',
    notes: 'Contient 1% Madecasome (extrait de centella encapsulé). Hydrate, nourrit, apaise, régénère et renforce barrière cutanée. Texture riche et dense qui fond sur la peau. Idéal post-laser ou peeling.',
    inci: 'AQUA, GLYCERIN, PANTHENOL, HYDROGENATED POLYISOBUTENE, ASTROCARYUM MURUMURU SEED BUTTER, OCTYLDODECANOL, DIMETHICONE, ORYZA SATIVA STARCH, MAGNESIUM SULFATE, HYDROGENATED CASTOR OIL, POLYGLYCERYL-4 ISOSTEARATE, CETYL PEG/PPG-10/1 DIMETHICONE, HEXYL LAURATE, SILICA, PEG-30 DIPOLYHYDROXYSTEARATE, DISTEARDIMONIUM HECTORITE, MADECASSOSIDE, ASIATICOSIDE, MADECCASSIC ACID, ASIATIC ACID, CENTELLA ASIATICA EXTRACT, CENTELLA ASIATICA CALLUS CONDITIONED MEDIA, ALPHA-GLUCAN OLIGOSACCHARIDE, POLYMNIA SONCHIFOLIA ROOT JUICE, BIFIDA FERMENT LYSATE, GLYCINE SOJA OIL, COPPER GLUCONATE, MAGNESIUM ASPARTATE, ZINC GLUCONATE, SPHINGOLIPIDS, TOCOPHEROL, CETYL ALCOHOL, PROPYLENE CARBONATE, CAPRYLYL GLYCOL, PENTYLENE GLYCOL, MANNITOL, BETA-SITOSTEROL, PHOSPHATIDYLCHOLINE, SQUALENE, PHOSPHOLIPIDS, POLYGLYCERYL-10 LAURATE, SODIUM CITRATE, ACETIC ACID, P-ANISIC ACID, LACTIC ACID, UBIQUINONE, CITRIC ACID, POTASSIUM SORBATE, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [TAG_SLUGS.BAUME, TAG_SLUGS.OCCLUSION, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.TEXTURE_RICHE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CENTELLA_COMPLEX, notes: '0.2% - Complexe Centella Asiatica triactif, réparation efficace',},
      { slug: INGREDIENT_SLUGS.MADECASSOSIDE, notes: '0.1% - Centella Asiatica, apaisement et cicatrisation',},
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: '1% - Extrait Centella Asiatica complet, synérgie réparatrice',},
    ],
  },
  {
    slug: "theramid-c4-hydrating-milky-toner",
    name: 'C4 Hydrating Milky Toner',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "bottle",
    totalAmount: 130,
    amountUnit: "ml",
    priceCents: 2195,
    description: `Lotion tonique hydratante à texture lactée hybride 2-en-1 combinant légèreté d'un tonique avec efficacité d'un sérum. Restaure et renforce la barrière cutanée avec peptides, céramides, Sodium PCA et panthénol.`,
    notes: 'Formule hybride tonique-sérum. Contient 4% complexe peptides-céramides, 3% Sodium PCA, 3% panthénol. pH: 5-5.5. Hydrate, apaise, répare, illumine. Idéal peaux déshydratées ou sensibles.',
    inci: 'AQUA, GLYCERIN, SODIUM PCA, PANTHENOL, BEHENYL/OLEYL BEHENATE/OLEATE ESTERS, BUTYLENE GLYCOL, BIFIDA FERMENT LYSATE, UREA, CERAMIDE NG, CERAMIDE AP, CERAMIDE NP, CERAMIDE EOP, LINOLEIC ACID, LINOLENIC ACID, GLABRIDIN, ASIATICOSIDE, PHOSPHOLIPIDS, SPHINGOLIPIDS, MADECCASSIC ACID, ASIATIC ACID, BETA-GLUCAN, HEXANOYL DIPEPTIDE-3 NORLEUCINE ACETATE, XYLITYLGLUCOSIDE, ANHYDROXYLITOL, XYLITOL, GLUCOSE, GLYCYRRHIZA GLABRA ROOT EXTRACT, ORYZA SATIVA EXTRACT, LIMNANTHES ALBA SEED OIL, HEXYLDECANOL, CITRUS LIMON PEEL POWDER, HYDROGENATED LECITHIN, LECITHIN, PENTYLENE GLYCOL, SCLEROTIUM GUM, CITRUS AURANTIFOLIA PEEL POWDER, PHYTOSTEROLS, COCO-GLUCOSIDE, ACETIC ACID, LACTIC ACID, P-ANISIC ACID, TOCOPHEROL, SODIUM CITRATE, POTASSIUM SORBATE, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [TAG_SLUGS.TONIQUE, TAG_SLUGS.LOTION, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.PREPARATION, TAG_SLUGS.HYDRATATION, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_SECHE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.SODIUM_PCA, notes: '3% - Hydratant naturel puissant, osmolyte',},
      { slug: INGREDIENT_SLUGS.PANTHENOL, notes: '3% - Provitamine B5, hydration et apaisement',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '2% - Soutien barrière cutanée',},
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '2% - Complexe céramides multi, restaure barrière',},
      { slug: INGREDIENT_SLUGS.BETA_GLUCAN, notes: '1% - Antioxydant et protecteur barrière',},
    ],
  },
  {
    slug: "theramid-ascorbic-c15",
    name: 'Ascorbic C15',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "bottle",
    totalAmount: 30,
    amountUnit: "ml",
    priceCents: 995,
    description: `Sérum antioxydant formulé avec 15% de vitamine C pure (acide L-ascorbique), l'un des plus efficaces pour traiter le vieillissement cutané. Réduit taches brunes, améliore l'éclat et adoucit les rides d'expression.`,
    notes: 'Contient 5% glutathion (antioxydant puissant) et 1% extrait thé vert. pH: 3.0-3.2. Très instable, PAO 3 mois. Conserver au frais (<5°C). Non recommandé peaux sensibles. Odeur perceptible normale.',
    inci: 'AQUA, DIMETHYL ISOSORBIDE, ASCORBIC ACID, PROPYLENE GLYCOL, GLUTATHIONE, PROPANEDIOL, ETHOXYDIGLYCOL, ARGININE FERULATE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, CAMELLIA SINENSIS LEAF WATER, FERULIC ACID, TOCOPHEROL, CAPRYLYL GLYCOL, CITRIC ACID, SODIUM PHYTATE, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_TACHES],
      secondary: [TAG_SLUGS.SERUM, TAG_SLUGS.MATIN, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.VITAMIN_C, notes: '15% - Acide L-ascorbique pur, antioxydant le plus puissant',},
      { slug: INGREDIENT_SLUGS.GLUTATHION, notes: '5% - Antioxydant maître, stabilise et amplifie vitamine C',},
      { slug: INGREDIENT_SLUGS.GREEN_TEA, notes: '1% - EGCG, antioxydant supplémentaire',},
    ],
  },
  {
    slug: "theramid-zi-k-cica-repairing-gel",
    name: 'Zi-K® Cica Repairing Gel',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "jar",
    totalAmount: 100,
    amountUnit: "ml",
    priceCents: 1495,
    description: 'Gel réparateur léger qui répare, apaise et protège les peaux abîmées ou irritées. Puissante combinaison de Centella Asiatica, madécassoside, T.E.CA, panthénol et madécasome pour hydratation et réparation cutanée.',
    notes: 'Texture légère gel idéale peaux normales à sèches. Hydrate, apaise, renforce et protège barrière cutanée. Soulage irritation, démangeaison, tiraillement. Favorise régénération et synthèse collagène.',
    inci: 'AQUA, PROPANEDIOL, NEOPENTYL GLYCOL DIHEPTANOATE, DIMETHICONE, PANTHENOL, CAPRYLYL METHICONE, CETYL PEG/PPG 10/1 DIMETHICONE, GLYCERIN, PEG/PPG-18/18 DIMETHICONE, ISODODECANE, CAPRYLYL GLYCOL, MADECASSOSIDE, ASIATICOSIDE, MADECCASSIC ACID, ASIATIC ACID, CENTELLA ASIATICA EXTRACT, CENTELLA ASIATICA CALLUS CONDITIONED MEDIA, ALPHA-GLUCAN OLIGOSACCHARIDE, POLYMNIA SONCHIFOLIA ROOT JUICE, COPPER GLUCONATE, MAGNESIUM ASPARTATE, ZINC GLUCONATE, GLYCERYL CAPRYLATE, PENTYLENE GLYCOL, DIMETHICONOL, PHENYLPROPANOL, MANNITOL, PHOSPHATIDYLCHOLINE, UBIQUINONE, POLYGLYCERYL-10 LAURATE, CETYL ALCOHOL, CITRIC ACID, SODIUM PHYTATE, POTASSIUM SORBATE, SODIUM BENZOATE, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.BARRIERE_CUTANEE],
      secondary: [TAG_SLUGS.GEL_CREME, TAG_SLUGS.CREME_HYDRATANTE, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.TRAITEMENT, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PEAU_REACTIVE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, notes: '2% - Extrait complet, puissant réparateur',},
      { slug: INGREDIENT_SLUGS.MADECASSOSIDE, notes: '0.5% - Centella isolée, cicatrisation accélérée',},
      { slug: INGREDIENT_SLUGS.PANTHENOL, notes: '5% - Hydration et apaisement',},
      { slug: INGREDIENT_SLUGS.ZINC_PCA, notes: '0.2% - Minéral de cicatrisation',},
    ],
  },
  {
    slug: "theramid-vitamin-enriched-body-lotion",
    name: 'Vitamin Enriched Body Lotion',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 2695,
    description: 'Lait corporel anti-âge unique enrichi en vitamines puissantes: rétinal (A), niacinamide (B3), panthénol (B5) et vitamine E. Nourrit, hydrate et rajeunit la peau, lui redonnant éclat et élasticité naturels.',
    notes: 'Stimule renouvellement cellulaire et synthèse collagène. Contient 4% niacinamide, 3% vitamine E, 0,06% rétinal liposomé. Idéal bras, jambes, ventre, cou, décolleté. pH: 5.5-6.',
    inci: 'AQUA, COCO-CAPRYLATE, GLYCERIN, PROPANEDIOL, NIACINAMIDE, TOCOPHERYL ACETATE, CETEARYL ALCOHOL, JOJOBA ESTERS, GLYCERYL STEARATE, PANTHENOL, RETINAL, SQUALENE, HELIANTHUS ANNUUS SEED WAX, GLYCINE SOJA OIL, BETA-SITOSTEROL, XANTHAN GUM, CETYL ALCOHOL, SODIUM STEAROYL GLUTAMATE, MANNITOL, PHOSPHATIDYLCHOLINE, POLYGLYCERIN-3, POTASSIUM CETYL PHOSPHATE, PHOSPHORIC ACID, SODIUM CHLORIDE, TOCOPHEROL, CAPRYLYL GLYCOL, SODIUM BENZOATE, POTASSIUM SORBATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL, CITRIC ACID',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
      secondary: [TAG_SLUGS.LAIT_CORPS, TAG_SLUGS.ZONE_CORPS, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.HYDRATATION, TAG_SLUGS.TEXTURE_RICHE, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.NIACINAMIDE, notes: '4% - Vitamine B3, renouvellement cellulaire et uniformité teint',},
      { slug: INGREDIENT_SLUGS.TOCOPHEROL, notes: '3% - Tocophéryl acétate, protection antioxydante contre radicaux libres',},
      { slug: INGREDIENT_SLUGS.RETINAL, notes: '0.06% - Liposomé encapsulé, stimule synthèse collagène, réduit rides',},
    ],
  },
  {
    slug: "theramid-aha-smoothing-body-lotion",
    name: 'AHA Smoothing Body Lotion',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 2495,
    description: `Lotion corporelle anti-imperfection avec 10% d'acide glycolique (AHA) pour exfolier doucement. Associe propriétés hydratantes à bénéfices exfoliation chimique pour peau plus lisse et lumineuse.`,
    notes: 'Exfolie, élimine cellules mortes, réduit rides, taches et imperfections. Enrichi peptides apaisants (1%) et ectoine (0,5%) pour renforcer barrière. pH: 3.8-4.2. Eviter peaux sensibles.',
    inci: 'AQUA, COCO-CAPRYLATE, GLYCOLIC ACID, GLYCERIN, PROPANEDIOL, CETYL ALCOHOL, SODIUM HYDROXIDE, GLYCERYL STEARATE, PALMITOYL TRIPEPTIDE-8, ECTOIN, GLYCINE SOJA OIL, CARYODENDRON ORINOCENSE SEED OIL, PHRAGMITES COMMUNIS EXTRACT, PORIA COCOS EXTRACT, SPHINGOMONAS FERMENT EXTRACT, BUTYLENE GLYCOL, SQUALENE, BETA-SITOSTEROL, DEXTRAN, STEARETH-20, CETETH-20, CETEARYL ALCOHOL, PEG-75 STEARATE, TOCOPHEROL, SODIUM BENZOATE, CAPRYLYL GLYCOL, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL, SODIUM CITRATE, CITRIC ACID',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.GRAIN_PEAU],
      secondary: [TAG_SLUGS.LAIT_CORPS, TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.ZONE_CORPS, TAG_SLUGS.SOIR, TAG_SLUGS.ECLAT, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.ANTI_TACHES],
      avoid: [TAG_SLUGS.PEAU_SENSIBLE],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.GLYCOLIC_ACID, notes: '10% - AHA puissant, exfolie et lisse texture, élimine cellules mortes',},
      { slug: INGREDIENT_SLUGS.PEPTIDE_COMPLEX, notes: '1% - Peptides apaisants (Palmitoyl Tripeptide-8), calme irritation post-exfoliation',},
      { slug: INGREDIENT_SLUGS.ECTOIN, notes: '0.5% - Apaisement et renforcement barrière après exfoliation chimique',},
    ],
  },
  {
    slug: "theramid-ceramide-barrier-body-treatment",
    name: 'Ceramide Barrier Body Treatment',
    brand: 'Theramid',
    kind: 'skincare',
    unit: "pump",
    totalAmount: 400,
    amountUnit: "ml",
    priceCents: 2695,
    description: 'Lotion corporelle riche en céramides formulée avec 1% céramides pures, actifs hydratants et pré/probiotiques. Hydratation profonde et durable qui renforce et répare la barrière cutanée.',
    notes: 'Contient 10% complexe hydratation, 3% pré & probiotiques, 1% céramides. Améliore rétention eau, protège contre dommages environnementaux. Favorise équilibre microbiome. pH: 5.5-6.0.',
    inci: 'AQUA, COCO-CAPRYLATE, GLYCERIN, PROPANEDIOL, BIFIDA FERMENT LYSATE, CETEARYL ALCOHOL, JOJOBA ESTERS, GLYCERYL STEARATE, PANTHENOL, CERAMIDE NG, CERAMIDE NP, CERAMIDE AP, CERAMIDE AS, CERAMIDE NS, CERAMIDE EOP, BETA-GLUCAN, INULIN, FRUCTOSE, CHOLESTEROL, LACTOBACILLUS FERMENT, SQUALENE, HELIANTHUS ANNUUS SEED WAX, HELIANTHUS ANNUUS SEED OIL, CARYODENDRON ORINOCENSE SEED OIL, AVENA SATIVA KERNEL FLOUR, BETA-SITOSTEROL, MALTODEXTRIN, PENTYLENE GLYCOL, DIPROPYLENE GLYCOL, XANTHAN GUM, SODIUM STEAROYL GLUTAMATE, HYDROGENATED LECITHIN, SUCROSE DISTEARATE, POLYGLYCERIN-3, LACTIC ACID, ACETIC ACID, TOCOPHEROL, CAPRYLYL GLYCOL, SODIUM BENZOATE, ETHYLHEXYLGLYCERIN, PHENOXYETHANOL',
    url: 'https://nichebeautylab.com',
    tags: {
      primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
      secondary: [TAG_SLUGS.LAIT_CORPS, TAG_SLUGS.ZONE_CORPS, TAG_SLUGS.MATIN, TAG_SLUGS.SOIR, TAG_SLUGS.HYDRATATION, TAG_SLUGS.EMOLLIENCE, TAG_SLUGS.PEAU_SECHE],
      avoid: [],
    },
    keyIngredients: [
      { slug: INGREDIENT_SLUGS.CERAMIDES, notes: '1% - Complexe céramides multi-types, restaure barrière lipidique',},
      { slug: INGREDIENT_SLUGS.POSTBIOTICS, notes: '3% - Pré et probiotiques (Bifida Ferment, Lactobacillus), équilibre microbiome',},
      { slug: INGREDIENT_SLUGS.GLYCERIN, notes: 'Humectant, maintient hydratation durable',},
      { slug: INGREDIENT_SLUGS.PANTHENOL, notes: 'Apaisement et soutien barrière cutanée',},
    ],
  },
];
