import { TAG_SLUGS } from '../../tags/seed-tags'
import { THERAMID_PRODUCT_SLUGS } from './theramid'

export interface ProductTagAssociation {
  /** Tags principaux : bénéfices majeurs prouvés de l'actif */
  primary: string[]
  /** Tags secondaires : bénéfices d'accompagnement ou cibles spécifiques */
  secondary: string[]
  /** Tags d'exclusion : types de peau ou conditions où l'actif est déconseillé */
  avoid: string[]
}

export type ProductTagMap = Record<string, ProductTagAssociation>

export const THERAMID_PRODUCT_TAGS: ProductTagMap = {
  [THERAMID_PRODUCT_SLUGS.THERAMID_EVEN_IN]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_TETRAMID_CEF]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.MATIN, TAG_SLUGS.POLLUTION, TAG_SLUGS.SERUM],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_A_RETINYL_RETINOATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.SOIR, TAG_SLUGS.BIOMIMETIQUE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_COPPER_PEPTIDE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CICATRISATION, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.REPARATEUR,
    ],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_CERAMIDE_TREATMENT]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.BAUME,
    ],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_CLINICAL_VITAMIN_A]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.SOIR, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.TRAITEMENT,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_AZID]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.ANTI_BACTERIEN,
      TAG_SLUGS.COUPEROSE,
    ],
    secondary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SPOT_TREATMENT],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_LINO_8]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.CERNES_POCHES,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_SMOOTHING_TREATMENT]: {
    primary: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    secondary: [
      TAG_SLUGS.SOIR,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.EXFOLIATION,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_DERMA_PEPTIDES]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ECLAT,
    ],
    avoid: [],
  },

  [THERAMID_PRODUCT_SLUGS.THERAMID_HAPCA_FILLER]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT, TAG_SLUGS.HUMECTANT],
    secondary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.PROTECTION_CUTANEE,
    ],
    avoid: [],
  },
  [THERAMID_PRODUCT_SLUGS.THERAMID_BAKUCHIOL_FIRMING_CREAM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,

      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [],
  },

  // ── TIME_REVERSE_BEAUTY_SLEEP_MASK ──────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_TIME_REVERSE_BEAUTY_SLEEP_MASK]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.SLEEPING_MASK,
      TAG_SLUGS.MASQUE_HYDRATANT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.OCCLUSION,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.REPULPANT,
    ],
    avoid: [TAG_SLUGS.MATIN],
  },

  // ── RETINAL_AGE_REVERSE_CREAM ───────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_RETINAL_AGE_REVERSE_CREAM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,

      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  // ── NIACINAMIDE_GLOW_CREAM ──────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_NIACINAMIDE_GLOW_CREAM]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.REPARATEUR,
    ],
    avoid: [],
  },

  // ── PROTEO_REPAIR_CREAM ─────────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_PROTEO_REPAIR_CREAM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,

      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.PEAU_SECHE,
    ],
    avoid: [],
  },

  // ── ZITBACK ─────────────────────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ZITBACK]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIATION],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ANTI_BACTERIEN,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.ZONE_VISAGE],
  },

  // ── PURE_GLYCERIN_FACE_SERUM ────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_PURE_GLYCERIN_FACE_SERUM]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.HYDRATATION],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ANTI_AGE,
    ],
    avoid: [],
  },

  // ── BARRIER_RESTORING_HYDRATING_CREAM ───────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_BARRIER_RESTORING_HYDRATING_CREAM]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,

      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  // ── CERAMIDE_REPAIR_MOISTURIZER ─────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_CERAMIDE_REPAIR_MOISTURIZER]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    avoid: [],
  },

  // ── ZITCALM_CREAM ───────────────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ZITCALM_CREAM]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,

      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [TAG_SLUGS.BRILLANCE],
  },

  // ── ZITCONTROL ──────────────────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ZITCONTROL]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SEBO_REGULATEUR],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SPOT_TREATMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SOIN_LOCALISE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ANTI_BACTERIEN,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  // ── ZI_K_CICA_REPAIRING_BALM ────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ZI_K_CICA_REPAIRING_BALM]: {
    primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.OCCLUSION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  // ── C4_HYDRATING_MILKY_TONER ────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_C4_HYDRATING_MILKY_TONER]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.LOTION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
    ],
    avoid: [],
  },

  // ── ASCORBIC_C15 ────────────────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ASCORBIC_C15]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  // ── ZI_K_CICA_REPAIRING_GEL ─────────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_ZI_K_CICA_REPAIRING_GEL]: {
    primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    avoid: [],
  },

  // ── VITAMIN_ENRICHED_BODY_LOTION ────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_VITAMIN_ENRICHED_BODY_LOTION]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [],
  },

  // ── AHA_SMOOTHING_BODY_LOTION ───────────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_AHA_SMOOTHING_BODY_LOTION]: {
    primary: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.ANTI_TACHES,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  // ── CERAMIDE_BARRIER_BODY_TREATMENT ─────────────────────────────────
  [THERAMID_PRODUCT_SLUGS.THERAMID_CERAMIDE_BARRIER_BODY_TREATMENT]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.PEAU_SECHE,
    ],
    avoid: [],
  },
}
