import { TAG_SLUGS } from '../../tags/seed-tags'
import { BOJ_PDOCUT_SLUGS } from './beautyOfJoseon'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const BOJ_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.OCCLUSION,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
  },

  
  [BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.ESSENCE,
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [],
  },

  
  [BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BRILLANCE, TAG_SLUGS.MATIFIANT],
    secondary: [
      TAG_SLUGS.LOTION,
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PREPARATION,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_RUGUEUSE,
    ],
  },

  
  [BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH]: {
    primary: [TAG_SLUGS.CREME_SOLAIRE, TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },
}
