// ─── Core (HTTP constants, response types, schemas, factories, OpenAPI helpers) ──

export type { ApiError, ApiResponse, ApiSuccess } from './core'
export {
  baseErrorMapping,
  type CommonErrorCode,
  type ContentfulHttpStatus,
  ErrorResponseSchema,
  err,
  errorResponse,
  errorResponseWithOptionnalErrorCode,
  errorToStatus,
  type FieldChange,
  fieldChangeSchema,
  HTTP_STATUS,
  type HttpStatus,
  isApiError,
  isApiSuccess,
  ok,
  SuccessResponseSchema,
  successResponse,
} from './core'
export {
  type CreateProductIngredientInput,
  type CreateProductInput,
  createProductIngredientSchema,
  createProductSchema,
  type EditableProductKeys,
  type FilterTier,
  filterOptionsSchema,
  getProductTagCategory,
  type ListProductsFilters,
  listProductsQuery,
  PRODUCT_CATEGORIES,
  PRODUCT_CATEGORY_VALUES,
  PRODUCT_KINDS,
  PRODUCT_TAG_CATEGORIES,
  PRODUCT_TAG_CATEGORY_META,
  PRODUCT_TAG_SLUGS,
  PRODUCT_TAG_TAXONOMY,
  PRODUCT_UNITS,
  type Product,
  type ProductCategory,
  type ProductChanges,
  type ProductEdit,
  type ProductEditResponseSchema,
  type ProductErrorCode,
  type ProductIngredient,
  type ProductIngredientErrorCode,
  type ProductKind,
  type ProductKindsMap,
  type ProductSearchResult,
  type ProductsPage,
  type ProductTagCategory,
  type ProductTagMeta,
  type ProductTagSlug,
  type ProductUnit,
  type ProductWithStock,
  productChangesSchema,
  productEditResponseSchema,
  productErrorMapping,
  productFilterCategories,
  productIngredientErrorMapping,
  productIngredientResponseSchema,
  productResponseSchema,
  productsPageSchema,
  searchProductsQuery,
  type TagCategoryMeta,
  type UpdateProductInput,
  updateProductSchema,
} from './products'
// ─── Schemas (runtime validators + inferred types) ───────────────────────────
export {
  type AuthFieldErrors,
  type AuthInput,
  accessTokenPayloadSchema,
  authSchema,
  browserAuthResultSchema,
  type ChangePasswordInput,
  changePasswordSchema,
  type Email,
  emailSchema,
  type HashedPassword,
  loginSchema,
  mobileAuthResultSchema,
  mobileRefreshResultSchema,
  passwordSchema,
  type RawPassword,
  refreshTokenBodySchema,
  refreshTokenPayloadSchema,
  sessionResultSchema,
  signupSchema,
  userPublicSchema,
  verifyEmailBodySchema,
} from './schemas/auth'
export {
  type CreateReplyInput,
  type CreateThreadInput,
  createReplySchema,
  createThreadSchema,
  replyResponseSchema,
  threadResponseSchema,
  threadWithRepliesResponseSchema,
} from './schemas/discussions'
export {
  type CheckHabitInput,
  type CreateHabitInput,
  checkHabitSchema,
  checkProductHistoryResponseSchema,
  createHabitSchema,
  type DateRangeQuery,
  dateRangeQuerySchema,
  type Frequency,
  frequencySchema,
  type GetUserChecksQuery,
  getUserChecksQuerySchema,
  type HabitProductInput,
  habitCheckResponseSchema,
  habitFrequencyResponseSchema,
  habitPeriodResponseSchema,
  habitProductResponseSchema,
  habitProductSchema,
  habitReminderResponseSchema,
  habitResponseSchema,
  habitStatsResponseSchema,
  habitTimingResponseSchema,
  habitWithRelationsResponseSchema,
  type Period,
  periodSchema,
  REMINDER_PRESETS,
  type Reminder,
  type ReorderHabitsInput,
  reminderSchema,
  reminderWithTimingSchema,
  reorderHabitsSchema,
  type SetPeriodInput,
  type SetProductsInput,
  type SetRemindersInput,
  type SetRemindersWithTimingInput,
  type SetTimingsInput,
  setPeriodSchema,
  setProductsSchema,
  setRemindersSchema,
  setTimingsSchema,
  type Timing,
  type ToggleCheckInput,
  timingSchema,
  todayHabitResponseSchema,
  todayUserProductSchema,
  toggleCheckResultResponseSchema,
  toggleCheckSchema,
  type UpdateFrequencyInput,
  type UpdateHabitInput,
  uncheckByDateSchema,
  uncheckHabitSchema,
  updateFrequencySchema,
  updateHabitSchema,
} from './schemas/habits'
export {
  type CreateIngredientInput,
  createIngredientSchema,
  type EditableIngredientKeys,
  getIngredientTagCategory,
  type Ingredient,
  type IngredientCategory,
  INGREDIENT_CATEGORIES,
  INGREDIENT_CATEGORY_VALUES,
  type IngredientChanges,
  type IngredientEdit,
  type IngredientEditResponse,
  ingredientChangesSchema,
  ingredientEditResponseSchema,
  type IngredientErrorCode,
  ingredientErrorMapping,
  ingredientFilterCategories,
  type IngredientFilterOptions,
  ingredientFilterOptionsSchema,
  ingredientResponseSchema,
  ingredientSearchResultSchema,
  ingredientsSearchSchema,
  type IngredientResponse,
  type IngredientSearchFilters,
  type IngredientSearchResult,
  INGREDIENT_TAG_CATEGORIES,
  INGREDIENT_TAG_CATEGORY_META,
  INGREDIENT_TAG_SLUGS,
  INGREDIENT_TAG_TAXONOMY,
  type IngredientTagCategory,
  type IngredientTagMeta,
  type IngredientTagSlug,
  type UpdateIngredientInput,
  type UpdateIngredientRouteInput,
  updateIngredientRouteSchema,
  updateIngredientSchema,
} from './ingredients'
export {
  type HabitCheckProductResponse,
  type HabitCheckWithProductsResponse,
  habitCheckProductInputSchema,
  habitCheckProductResponseSchema,
  habitCheckWithProductsResponseSchema,
  type LogHabitCheckInput,
  type LogWellbeingInput,
  logHabitCheckSchema,
  logWellbeingSchema,
  type TodayLogsResponse,
  todayLogsQuerySchema,
  todayLogsResponseSchema,
  type WellbeingLogResponse,
  wellbeingLogResponseSchema,
  wellbeingMetricSchema,
  wellbeingMetrics,
} from './schemas/logs'
export {
  type PrivacySettings,
  privacySettingsSchema,
  type UpdatePrivacySettingsInput,
  updatePrivacySettingsSchema,
} from './schemas/privacy'
export {
  BIO_MAX_LENGTH,
  type ProfileLink,
  type ProfileStats,
  type ProfileUpdateInput,
  profileLinkSchema,
  profilePublicSchema,
  profileStatsSchema,
  profileUpdateSchema,
  SKIN_CONCERNS,
  SKIN_TYPES,
  type SkinConcern,
  type SkinType,
  USERNAME_MAX_LENGTH,
  type UserDermoProfile,
  type UserDermoProfileUpdateInput,
  userDermoProfileSchema,
  userDermoProfileUpdateSchema,
} from './schemas/profile'
export {
  type AddPurchaseInput,
  addPurchaseSchema,
  type FinishPurchaseInput,
  finishPurchaseSchema,
  type OpenPurchaseInput,
  openPurchaseSchema,
  type Purchase,
  purchaseSchema,
  type UpdatePurchaseInput,
  updatePurchaseSchema,
} from './schemas/purchases'
export {
  type AddIngredientTagInput,
  type AddProductTagInput,
  addIngredientTagSchema,
  addProductTagSchema,
  type CreateTagInput,
  createTagSchema,
  type IngredientTagResponse,
  ingredientTagResponseSchema,
  type Relevance,
  type ReplaceIngredientTagsInput,
  type ReplaceProductTagsInput,
  relevanceEnum,
  replaceIngredientTagsSchema,
  replaceProductTagsSchema,
  tagResponseSchema,
  type UpdateTagInput,
} from './schemas/tags'
export {
  type CreateSubtaskInput,
  type CreateTaskInput,
  createSubtaskSchema,
  createTaskSchema,
  type UpdateSubtaskInput,
  type UpdateTaskInput,
  updateSubtaskSchema,
  updateTaskSchema,
} from './schemas/tasks'
export {
  type CriteriaWeights,
  criteriaWeightsSchema,
  type DisplayScale,
  displayScale,
  displayScaleSchema,
  type UpdateUserPreferencesInput,
  type UserPreferences,
  updateUserPreferencesSchema,
  userPreferencesSchema,
} from './schemas/user-preferences'
export {
  type CreateUserProductInput,
  createUserProductSchema,
  type RepurchaseFlag,
  repurchaseFlag,
  repurchaseFlagSchema,
  type UpdateUserProductInput,
  type UpdateUserProductReviewInput,
  type UserProduct,
  type UserProductErrorCode,
  type UserProductReview,
  type UserProductStatus,
  updateUserProductReviewSchema,
  updateUserProductSchema,
  userProductErrorMapping,
  userProductReviewSchema,
  userProductSchema,
  userProductStatus,
  userProductStatusSchema,
} from './user-products'

// ─── Types (entity types, error codes, composed types) ───────────────────────

export type {
  AccessTokenPayload,
  AuthErrorCode,
  AuthenticatedResult,
  AuthTokens,
  BrowserAuthResult,
  ChangePasswordResult,
  CreateRefreshTokenArgs,
  GoogleCallbackResult,
  LoginResult,
  LogoutResult,
  MobileAuthResult,
  RefreshResult,
  RefreshTokenPayload,
  SignupResult,
  UserPublic,
} from './types/auth'
export type {
  DiscussionErrorCode,
  DiscussionReply,
  DiscussionThread,
  DiscussionThreadWithReplies,
} from './types/discussions'
export type {
  Habit,
  HabitCheck,
  HabitCheckProduct,
  HabitCheckStatus,
  HabitErrorCode,
  HabitFrequency,
  HabitPeriod,
  HabitProduct,
  HabitReminder,
  HabitStats,
  HabitTiming,
  HabitTimingWithReminders,
  HabitWithRelations,
  TodayHabit,
  TodayUserProduct,
  ToggleCheckResult,
} from './types/habits'
export type { LogsErrorCode } from './types/logs'
export type {
  MeResponse,
  ProfileErrorCode,
  ProfilePublic,
  ProfileStatsResponse,
  ProfileUpdateResponse,
} from './types/profile'
export type { PurchaseErrorCode } from './types/purchases'
export type {
  IngredientTag,
  ProductTag,
  Tag,
  TagErrorCode,
} from './types/tags'
export type {
  Subtask,
  Task,
  TaskEnergy,
  TaskErrorCode,
  TaskStatus,
} from './types/tasks'

// ─── Helpers (error mappings, constants, utilities) ──────────────────────────

export { authErrorMapping } from './helpers/auth'
export { discussionErrorMapping } from './helpers/discussions'
export { habitErrorMapping } from './helpers/habits'
export { logsErrorMapping } from './helpers/logs'
export { profileErrorMapping } from './helpers/profile'
export { purchaseErrorMapping } from './helpers/purchases'
export { tagErrorMapping } from './helpers/tags'
export { taskErrorMapping } from './helpers/tasks'
