import { TAG_SLUGS } from '../../tags/seed-tags'
import { MIXA_PRODUCT_SLUGS } from './mixa'

interface ProductTagGroups {
  primary: string[] 
  secondary: string[] 
  avoid: string[] 
}

export const MIXA_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  
  [MIXA_PRODUCT_SLUGS.NIACINAMIDE_CORRECTION_ECLAT]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.ACIDE_HYALURONIQUE_FRAICHE]: {
    primary: [TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.CREME_MAINS,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.PEAUX_SECHES_SENSIBLES]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.PANTHENOL_CONFORT]: {
    primary: [TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.CERAMIDE_PROTECTION]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.CICA_REPARATION]: {
    primary: [],
    secondary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
    ],
    avoid: [],
  },

  
  [MIXA_PRODUCT_SLUGS.PEAUX_TRES_SECHES_TERNES]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SECHE],
    secondary: [
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ZONE_MAINS,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    avoid: [],
  },
}
